/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type ResourcesAndPricingAPI interface {

	/*
	NetworkFeesCreateQuote Create a network-fee quote

	Preview bounded network fees for the requested resource prices and rails.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiNetworkFeesCreateQuoteRequest
	*/
	NetworkFeesCreateQuote(ctx context.Context) ApiNetworkFeesCreateQuoteRequest

	// NetworkFeesCreateQuoteExecute executes the request
	//  @return NetworkFeePreviewResponse
	NetworkFeesCreateQuoteExecute(r ApiNetworkFeesCreateQuoteRequest) (*NetworkFeePreviewResponse, *http.Response, error)

	/*
	ResourcesActivateVersion Activate a resource version

	Activate one immutable resource version idempotently.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param resourceId
	@param versionId
	@return ApiResourcesActivateVersionRequest
	*/
	ResourcesActivateVersion(ctx context.Context, resourceId string, versionId string) ApiResourcesActivateVersionRequest

	// ResourcesActivateVersionExecute executes the request
	//  @return ResourceVersion
	ResourcesActivateVersionExecute(r ApiResourcesActivateVersionRequest) (*ResourceVersion, *http.Response, error)

	/*
	ResourcesCreate Create a resource

	Create one tenant resource idempotently.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiResourcesCreateRequest
	*/
	ResourcesCreate(ctx context.Context) ApiResourcesCreateRequest

	// ResourcesCreateExecute executes the request
	//  @return Resource
	ResourcesCreateExecute(r ApiResourcesCreateRequest) (*Resource, *http.Response, error)

	/*
	ResourcesCreateVersion Create a resource version

	Create an immutable priced version of one tenant resource idempotently.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param resourceId
	@return ApiResourcesCreateVersionRequest
	*/
	ResourcesCreateVersion(ctx context.Context, resourceId string) ApiResourcesCreateVersionRequest

	// ResourcesCreateVersionExecute executes the request
	//  @return ResourceVersion
	ResourcesCreateVersionExecute(r ApiResourcesCreateVersionRequest) (*ResourceVersion, *http.Response, error)

	/*
	ResourcesList List resources

	List tenant resources and their visible versions using opaque cursor pagination.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiResourcesListRequest
	*/
	ResourcesList(ctx context.Context) ApiResourcesListRequest

	// ResourcesListExecute executes the request
	//  @return []Resource
	ResourcesListExecute(r ApiResourcesListRequest) ([]Resource, *http.Response, error)

	/*
	ResourcesListVersions List resource versions

	List immutable versions of one tenant resource using opaque cursor pagination.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param resourceId
	@return ApiResourcesListVersionsRequest
	*/
	ResourcesListVersions(ctx context.Context, resourceId string) ApiResourcesListVersionsRequest

	// ResourcesListVersionsExecute executes the request
	//  @return []ResourceVersion
	ResourcesListVersionsExecute(r ApiResourcesListVersionsRequest) ([]ResourceVersion, *http.Response, error)

	/*
	ResourcesRetireVersion Retire a resource version

	Retire one immutable resource version idempotently.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param resourceId
	@param versionId
	@return ApiResourcesRetireVersionRequest
	*/
	ResourcesRetireVersion(ctx context.Context, resourceId string, versionId string) ApiResourcesRetireVersionRequest

	// ResourcesRetireVersionExecute executes the request
	//  @return ResourceVersion
	ResourcesRetireVersionExecute(r ApiResourcesRetireVersionRequest) (*ResourceVersion, *http.Response, error)
}

// ResourcesAndPricingAPIService ResourcesAndPricingAPI service
type ResourcesAndPricingAPIService service

type ApiNetworkFeesCreateQuoteRequest struct {
	ctx context.Context
	ApiService ResourcesAndPricingAPI
	networkFeePreview *NetworkFeePreview
}

func (r ApiNetworkFeesCreateQuoteRequest) NetworkFeePreview(networkFeePreview NetworkFeePreview) ApiNetworkFeesCreateQuoteRequest {
	r.networkFeePreview = &networkFeePreview
	return r
}

func (r ApiNetworkFeesCreateQuoteRequest) Execute() (*NetworkFeePreviewResponse, *http.Response, error) {
	return r.ApiService.NetworkFeesCreateQuoteExecute(r)
}

/*
NetworkFeesCreateQuote Create a network-fee quote

Preview bounded network fees for the requested resource prices and rails.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiNetworkFeesCreateQuoteRequest
*/
func (a *ResourcesAndPricingAPIService) NetworkFeesCreateQuote(ctx context.Context) ApiNetworkFeesCreateQuoteRequest {
	return ApiNetworkFeesCreateQuoteRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return NetworkFeePreviewResponse
func (a *ResourcesAndPricingAPIService) NetworkFeesCreateQuoteExecute(r ApiNetworkFeesCreateQuoteRequest) (*NetworkFeePreviewResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *NetworkFeePreviewResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ResourcesAndPricingAPIService.NetworkFeesCreateQuote")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/network-fee-quotes"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.networkFeePreview == nil {
		return localVarReturnValue, nil, reportError("networkFeePreview is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.networkFeePreview
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiResourcesActivateVersionRequest struct {
	ctx context.Context
	ApiService ResourcesAndPricingAPI
	idempotencyKey *string
	resourceId string
	versionId string
	resourceVersionActivate *ResourceVersionActivate
}

// Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
func (r ApiResourcesActivateVersionRequest) IdempotencyKey(idempotencyKey string) ApiResourcesActivateVersionRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r ApiResourcesActivateVersionRequest) ResourceVersionActivate(resourceVersionActivate ResourceVersionActivate) ApiResourcesActivateVersionRequest {
	r.resourceVersionActivate = &resourceVersionActivate
	return r
}

func (r ApiResourcesActivateVersionRequest) Execute() (*ResourceVersion, *http.Response, error) {
	return r.ApiService.ResourcesActivateVersionExecute(r)
}

/*
ResourcesActivateVersion Activate a resource version

Activate one immutable resource version idempotently.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param resourceId
 @param versionId
 @return ApiResourcesActivateVersionRequest
*/
func (a *ResourcesAndPricingAPIService) ResourcesActivateVersion(ctx context.Context, resourceId string, versionId string) ApiResourcesActivateVersionRequest {
	return ApiResourcesActivateVersionRequest{
		ApiService: a,
		ctx: ctx,
		resourceId: resourceId,
		versionId: versionId,
	}
}

// Execute executes the request
//  @return ResourceVersion
func (a *ResourcesAndPricingAPIService) ResourcesActivateVersionExecute(r ApiResourcesActivateVersionRequest) (*ResourceVersion, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResourceVersion
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ResourcesAndPricingAPIService.ResourcesActivateVersion")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/resources/{resource_id}/versions/{version_id}/activate"
	localVarPath = strings.Replace(localVarPath, "{"+"resource_id"+"}", url.PathEscape(parameterValueToString(r.resourceId, "resourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"version_id"+"}", url.PathEscape(parameterValueToString(r.versionId, "versionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.idempotencyKey == nil {
		return localVarReturnValue, nil, reportError("idempotencyKey is required and must be specified")
	}
	if strlen(*r.idempotencyKey) < 8 {
		return localVarReturnValue, nil, reportError("idempotencyKey must have at least 8 elements")
	}
	if strlen(*r.idempotencyKey) > 160 {
		return localVarReturnValue, nil, reportError("idempotencyKey must have less than 160 elements")
	}
	if r.resourceVersionActivate == nil {
		return localVarReturnValue, nil, reportError("resourceVersionActivate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	// body params
	localVarPostBody = r.resourceVersionActivate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiResourcesCreateRequest struct {
	ctx context.Context
	ApiService ResourcesAndPricingAPI
	idempotencyKey *string
	resourceCreate *ResourceCreate
}

// Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
func (r ApiResourcesCreateRequest) IdempotencyKey(idempotencyKey string) ApiResourcesCreateRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r ApiResourcesCreateRequest) ResourceCreate(resourceCreate ResourceCreate) ApiResourcesCreateRequest {
	r.resourceCreate = &resourceCreate
	return r
}

func (r ApiResourcesCreateRequest) Execute() (*Resource, *http.Response, error) {
	return r.ApiService.ResourcesCreateExecute(r)
}

/*
ResourcesCreate Create a resource

Create one tenant resource idempotently.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiResourcesCreateRequest
*/
func (a *ResourcesAndPricingAPIService) ResourcesCreate(ctx context.Context) ApiResourcesCreateRequest {
	return ApiResourcesCreateRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Resource
func (a *ResourcesAndPricingAPIService) ResourcesCreateExecute(r ApiResourcesCreateRequest) (*Resource, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Resource
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ResourcesAndPricingAPIService.ResourcesCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/resources"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.idempotencyKey == nil {
		return localVarReturnValue, nil, reportError("idempotencyKey is required and must be specified")
	}
	if strlen(*r.idempotencyKey) < 8 {
		return localVarReturnValue, nil, reportError("idempotencyKey must have at least 8 elements")
	}
	if strlen(*r.idempotencyKey) > 160 {
		return localVarReturnValue, nil, reportError("idempotencyKey must have less than 160 elements")
	}
	if r.resourceCreate == nil {
		return localVarReturnValue, nil, reportError("resourceCreate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	// body params
	localVarPostBody = r.resourceCreate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiResourcesCreateVersionRequest struct {
	ctx context.Context
	ApiService ResourcesAndPricingAPI
	idempotencyKey *string
	resourceId string
	resourceVersionCreate *ResourceVersionCreate
}

// Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
func (r ApiResourcesCreateVersionRequest) IdempotencyKey(idempotencyKey string) ApiResourcesCreateVersionRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r ApiResourcesCreateVersionRequest) ResourceVersionCreate(resourceVersionCreate ResourceVersionCreate) ApiResourcesCreateVersionRequest {
	r.resourceVersionCreate = &resourceVersionCreate
	return r
}

func (r ApiResourcesCreateVersionRequest) Execute() (*ResourceVersion, *http.Response, error) {
	return r.ApiService.ResourcesCreateVersionExecute(r)
}

/*
ResourcesCreateVersion Create a resource version

Create an immutable priced version of one tenant resource idempotently.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param resourceId
 @return ApiResourcesCreateVersionRequest
*/
func (a *ResourcesAndPricingAPIService) ResourcesCreateVersion(ctx context.Context, resourceId string) ApiResourcesCreateVersionRequest {
	return ApiResourcesCreateVersionRequest{
		ApiService: a,
		ctx: ctx,
		resourceId: resourceId,
	}
}

// Execute executes the request
//  @return ResourceVersion
func (a *ResourcesAndPricingAPIService) ResourcesCreateVersionExecute(r ApiResourcesCreateVersionRequest) (*ResourceVersion, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResourceVersion
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ResourcesAndPricingAPIService.ResourcesCreateVersion")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/resources/{resource_id}/versions"
	localVarPath = strings.Replace(localVarPath, "{"+"resource_id"+"}", url.PathEscape(parameterValueToString(r.resourceId, "resourceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.idempotencyKey == nil {
		return localVarReturnValue, nil, reportError("idempotencyKey is required and must be specified")
	}
	if strlen(*r.idempotencyKey) < 8 {
		return localVarReturnValue, nil, reportError("idempotencyKey must have at least 8 elements")
	}
	if strlen(*r.idempotencyKey) > 160 {
		return localVarReturnValue, nil, reportError("idempotencyKey must have less than 160 elements")
	}
	if r.resourceVersionCreate == nil {
		return localVarReturnValue, nil, reportError("resourceVersionCreate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	// body params
	localVarPostBody = r.resourceVersionCreate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiResourcesListRequest struct {
	ctx context.Context
	ApiService ResourcesAndPricingAPI
	cursor *string
	pageSize *int32
}

// Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link.
func (r ApiResourcesListRequest) Cursor(cursor string) ApiResourcesListRequest {
	r.cursor = &cursor
	return r
}

// Number of results in the bounded array page (default and maximum 100).
func (r ApiResourcesListRequest) PageSize(pageSize int32) ApiResourcesListRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiResourcesListRequest) Execute() ([]Resource, *http.Response, error) {
	return r.ApiService.ResourcesListExecute(r)
}

/*
ResourcesList List resources

List tenant resources and their visible versions using opaque cursor pagination.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiResourcesListRequest
*/
func (a *ResourcesAndPricingAPIService) ResourcesList(ctx context.Context) ApiResourcesListRequest {
	return ApiResourcesListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []Resource
func (a *ResourcesAndPricingAPIService) ResourcesListExecute(r ApiResourcesListRequest) ([]Resource, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []Resource
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ResourcesAndPricingAPIService.ResourcesList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/resources"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 100
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiResourcesListVersionsRequest struct {
	ctx context.Context
	ApiService ResourcesAndPricingAPI
	resourceId string
	cursor *string
	pageSize *int32
}

// Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link.
func (r ApiResourcesListVersionsRequest) Cursor(cursor string) ApiResourcesListVersionsRequest {
	r.cursor = &cursor
	return r
}

// Number of results in the bounded array page (default and maximum 100).
func (r ApiResourcesListVersionsRequest) PageSize(pageSize int32) ApiResourcesListVersionsRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiResourcesListVersionsRequest) Execute() ([]ResourceVersion, *http.Response, error) {
	return r.ApiService.ResourcesListVersionsExecute(r)
}

/*
ResourcesListVersions List resource versions

List immutable versions of one tenant resource using opaque cursor pagination.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param resourceId
 @return ApiResourcesListVersionsRequest
*/
func (a *ResourcesAndPricingAPIService) ResourcesListVersions(ctx context.Context, resourceId string) ApiResourcesListVersionsRequest {
	return ApiResourcesListVersionsRequest{
		ApiService: a,
		ctx: ctx,
		resourceId: resourceId,
	}
}

// Execute executes the request
//  @return []ResourceVersion
func (a *ResourcesAndPricingAPIService) ResourcesListVersionsExecute(r ApiResourcesListVersionsRequest) ([]ResourceVersion, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ResourceVersion
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ResourcesAndPricingAPIService.ResourcesListVersions")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/resources/{resource_id}/versions"
	localVarPath = strings.Replace(localVarPath, "{"+"resource_id"+"}", url.PathEscape(parameterValueToString(r.resourceId, "resourceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 100
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiResourcesRetireVersionRequest struct {
	ctx context.Context
	ApiService ResourcesAndPricingAPI
	idempotencyKey *string
	resourceId string
	versionId string
	resourceVersionRetire *ResourceVersionRetire
}

// Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
func (r ApiResourcesRetireVersionRequest) IdempotencyKey(idempotencyKey string) ApiResourcesRetireVersionRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r ApiResourcesRetireVersionRequest) ResourceVersionRetire(resourceVersionRetire ResourceVersionRetire) ApiResourcesRetireVersionRequest {
	r.resourceVersionRetire = &resourceVersionRetire
	return r
}

func (r ApiResourcesRetireVersionRequest) Execute() (*ResourceVersion, *http.Response, error) {
	return r.ApiService.ResourcesRetireVersionExecute(r)
}

/*
ResourcesRetireVersion Retire a resource version

Retire one immutable resource version idempotently.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param resourceId
 @param versionId
 @return ApiResourcesRetireVersionRequest
*/
func (a *ResourcesAndPricingAPIService) ResourcesRetireVersion(ctx context.Context, resourceId string, versionId string) ApiResourcesRetireVersionRequest {
	return ApiResourcesRetireVersionRequest{
		ApiService: a,
		ctx: ctx,
		resourceId: resourceId,
		versionId: versionId,
	}
}

// Execute executes the request
//  @return ResourceVersion
func (a *ResourcesAndPricingAPIService) ResourcesRetireVersionExecute(r ApiResourcesRetireVersionRequest) (*ResourceVersion, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResourceVersion
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ResourcesAndPricingAPIService.ResourcesRetireVersion")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/resources/{resource_id}/versions/{version_id}/retire"
	localVarPath = strings.Replace(localVarPath, "{"+"resource_id"+"}", url.PathEscape(parameterValueToString(r.resourceId, "resourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"version_id"+"}", url.PathEscape(parameterValueToString(r.versionId, "versionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.idempotencyKey == nil {
		return localVarReturnValue, nil, reportError("idempotencyKey is required and must be specified")
	}
	if strlen(*r.idempotencyKey) < 8 {
		return localVarReturnValue, nil, reportError("idempotencyKey must have at least 8 elements")
	}
	if strlen(*r.idempotencyKey) > 160 {
		return localVarReturnValue, nil, reportError("idempotencyKey must have less than 160 elements")
	}
	if r.resourceVersionRetire == nil {
		return localVarReturnValue, nil, reportError("resourceVersionRetire is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	// body params
	localVarPostBody = r.resourceVersionRetire
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
