/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type OrdersAndPaymentsAPI interface {

	/*
	V1OrdersList Method for V1OrdersList

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1OrdersListRequest
	*/
	V1OrdersList(ctx context.Context) ApiV1OrdersListRequest

	// V1OrdersListExecute executes the request
	//  @return []Order
	V1OrdersListExecute(r ApiV1OrdersListRequest) ([]Order, *http.Response, error)

	/*
	V1OrdersRetrieve Method for V1OrdersRetrieve

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return ApiV1OrdersRetrieveRequest
	*/
	V1OrdersRetrieve(ctx context.Context, id string) ApiV1OrdersRetrieveRequest

	// V1OrdersRetrieveExecute executes the request
	//  @return Order
	V1OrdersRetrieveExecute(r ApiV1OrdersRetrieveRequest) (*Order, *http.Response, error)

	/*
	V1PaymentReceiptVerificationKeysRetrieve Method for V1PaymentReceiptVerificationKeysRetrieve

	Public key history; authenticity still requires an out-of-band pin.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1PaymentReceiptVerificationKeysRetrieveRequest
	*/
	V1PaymentReceiptVerificationKeysRetrieve(ctx context.Context) ApiV1PaymentReceiptVerificationKeysRetrieveRequest

	// V1PaymentReceiptVerificationKeysRetrieveExecute executes the request
	//  @return ReceiptVerificationKeyHistory
	V1PaymentReceiptVerificationKeysRetrieveExecute(r ApiV1PaymentReceiptVerificationKeysRetrieveRequest) (*ReceiptVerificationKeyHistory, *http.Response, error)

	/*
	V1PaymentsList Method for V1PaymentsList

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1PaymentsListRequest
	*/
	V1PaymentsList(ctx context.Context) ApiV1PaymentsListRequest

	// V1PaymentsListExecute executes the request
	//  @return []SettlementJob
	V1PaymentsListExecute(r ApiV1PaymentsListRequest) ([]SettlementJob, *http.Response, error)

	/*
	V1PaymentsObservationsList Method for V1PaymentsObservationsList

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return ApiV1PaymentsObservationsListRequest
	*/
	V1PaymentsObservationsList(ctx context.Context, id string) ApiV1PaymentsObservationsListRequest

	// V1PaymentsObservationsListExecute executes the request
	//  @return []SettlementChainObservation
	V1PaymentsObservationsListExecute(r ApiV1PaymentsObservationsListRequest) ([]SettlementChainObservation, *http.Response, error)

	/*
	V1PaymentsReceiptRetrieve Method for V1PaymentsReceiptRetrieve

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return ApiV1PaymentsReceiptRetrieveRequest
	*/
	V1PaymentsReceiptRetrieve(ctx context.Context, id string) ApiV1PaymentsReceiptRetrieveRequest

	// V1PaymentsReceiptRetrieveExecute executes the request
	//  @return PaymentReceipt
	V1PaymentsReceiptRetrieveExecute(r ApiV1PaymentsReceiptRetrieveRequest) (*PaymentReceipt, *http.Response, error)

	/*
	V1PaymentsRetrieve Method for V1PaymentsRetrieve

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return ApiV1PaymentsRetrieveRequest
	*/
	V1PaymentsRetrieve(ctx context.Context, id string) ApiV1PaymentsRetrieveRequest

	// V1PaymentsRetrieveExecute executes the request
	//  @return SettlementJob
	V1PaymentsRetrieveExecute(r ApiV1PaymentsRetrieveRequest) (*SettlementJob, *http.Response, error)
}

// OrdersAndPaymentsAPIService OrdersAndPaymentsAPI service
type OrdersAndPaymentsAPIService service

type ApiV1OrdersListRequest struct {
	ctx context.Context
	ApiService OrdersAndPaymentsAPI
	cursor *string
	pageSize *int32
}

// Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link.
func (r ApiV1OrdersListRequest) Cursor(cursor string) ApiV1OrdersListRequest {
	r.cursor = &cursor
	return r
}

// Number of results in the bounded array page (default and maximum 100).
func (r ApiV1OrdersListRequest) PageSize(pageSize int32) ApiV1OrdersListRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiV1OrdersListRequest) Execute() ([]Order, *http.Response, error) {
	return r.ApiService.V1OrdersListExecute(r)
}

/*
V1OrdersList Method for V1OrdersList

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1OrdersListRequest
*/
func (a *OrdersAndPaymentsAPIService) V1OrdersList(ctx context.Context) ApiV1OrdersListRequest {
	return ApiV1OrdersListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []Order
func (a *OrdersAndPaymentsAPIService) V1OrdersListExecute(r ApiV1OrdersListRequest) ([]Order, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []Order
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrdersAndPaymentsAPIService.V1OrdersList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/orders"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 100
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1OrdersRetrieveRequest struct {
	ctx context.Context
	ApiService OrdersAndPaymentsAPI
	id string
}

func (r ApiV1OrdersRetrieveRequest) Execute() (*Order, *http.Response, error) {
	return r.ApiService.V1OrdersRetrieveExecute(r)
}

/*
V1OrdersRetrieve Method for V1OrdersRetrieve

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiV1OrdersRetrieveRequest
*/
func (a *OrdersAndPaymentsAPIService) V1OrdersRetrieve(ctx context.Context, id string) ApiV1OrdersRetrieveRequest {
	return ApiV1OrdersRetrieveRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return Order
func (a *OrdersAndPaymentsAPIService) V1OrdersRetrieveExecute(r ApiV1OrdersRetrieveRequest) (*Order, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Order
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrdersAndPaymentsAPIService.V1OrdersRetrieve")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/orders/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1PaymentReceiptVerificationKeysRetrieveRequest struct {
	ctx context.Context
	ApiService OrdersAndPaymentsAPI
}

func (r ApiV1PaymentReceiptVerificationKeysRetrieveRequest) Execute() (*ReceiptVerificationKeyHistory, *http.Response, error) {
	return r.ApiService.V1PaymentReceiptVerificationKeysRetrieveExecute(r)
}

/*
V1PaymentReceiptVerificationKeysRetrieve Method for V1PaymentReceiptVerificationKeysRetrieve

Public key history; authenticity still requires an out-of-band pin.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1PaymentReceiptVerificationKeysRetrieveRequest
*/
func (a *OrdersAndPaymentsAPIService) V1PaymentReceiptVerificationKeysRetrieve(ctx context.Context) ApiV1PaymentReceiptVerificationKeysRetrieveRequest {
	return ApiV1PaymentReceiptVerificationKeysRetrieveRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ReceiptVerificationKeyHistory
func (a *OrdersAndPaymentsAPIService) V1PaymentReceiptVerificationKeysRetrieveExecute(r ApiV1PaymentReceiptVerificationKeysRetrieveRequest) (*ReceiptVerificationKeyHistory, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ReceiptVerificationKeyHistory
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrdersAndPaymentsAPIService.V1PaymentReceiptVerificationKeysRetrieve")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/payment-receipt-verification-keys"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1PaymentsListRequest struct {
	ctx context.Context
	ApiService OrdersAndPaymentsAPI
	cursor *string
	pageSize *int32
}

// Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link.
func (r ApiV1PaymentsListRequest) Cursor(cursor string) ApiV1PaymentsListRequest {
	r.cursor = &cursor
	return r
}

// Number of results in the bounded array page (default and maximum 100).
func (r ApiV1PaymentsListRequest) PageSize(pageSize int32) ApiV1PaymentsListRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiV1PaymentsListRequest) Execute() ([]SettlementJob, *http.Response, error) {
	return r.ApiService.V1PaymentsListExecute(r)
}

/*
V1PaymentsList Method for V1PaymentsList

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1PaymentsListRequest
*/
func (a *OrdersAndPaymentsAPIService) V1PaymentsList(ctx context.Context) ApiV1PaymentsListRequest {
	return ApiV1PaymentsListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []SettlementJob
func (a *OrdersAndPaymentsAPIService) V1PaymentsListExecute(r ApiV1PaymentsListRequest) ([]SettlementJob, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []SettlementJob
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrdersAndPaymentsAPIService.V1PaymentsList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/payments"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 100
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1PaymentsObservationsListRequest struct {
	ctx context.Context
	ApiService OrdersAndPaymentsAPI
	id string
	cursor *string
	pageSize *int32
}

// Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link.
func (r ApiV1PaymentsObservationsListRequest) Cursor(cursor string) ApiV1PaymentsObservationsListRequest {
	r.cursor = &cursor
	return r
}

// Number of results in the bounded array page (default and maximum 100).
func (r ApiV1PaymentsObservationsListRequest) PageSize(pageSize int32) ApiV1PaymentsObservationsListRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiV1PaymentsObservationsListRequest) Execute() ([]SettlementChainObservation, *http.Response, error) {
	return r.ApiService.V1PaymentsObservationsListExecute(r)
}

/*
V1PaymentsObservationsList Method for V1PaymentsObservationsList

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiV1PaymentsObservationsListRequest
*/
func (a *OrdersAndPaymentsAPIService) V1PaymentsObservationsList(ctx context.Context, id string) ApiV1PaymentsObservationsListRequest {
	return ApiV1PaymentsObservationsListRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return []SettlementChainObservation
func (a *OrdersAndPaymentsAPIService) V1PaymentsObservationsListExecute(r ApiV1PaymentsObservationsListRequest) ([]SettlementChainObservation, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []SettlementChainObservation
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrdersAndPaymentsAPIService.V1PaymentsObservationsList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/payments/{id}/observations"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 100
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1PaymentsReceiptRetrieveRequest struct {
	ctx context.Context
	ApiService OrdersAndPaymentsAPI
	id string
}

func (r ApiV1PaymentsReceiptRetrieveRequest) Execute() (*PaymentReceipt, *http.Response, error) {
	return r.ApiService.V1PaymentsReceiptRetrieveExecute(r)
}

/*
V1PaymentsReceiptRetrieve Method for V1PaymentsReceiptRetrieve

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiV1PaymentsReceiptRetrieveRequest
*/
func (a *OrdersAndPaymentsAPIService) V1PaymentsReceiptRetrieve(ctx context.Context, id string) ApiV1PaymentsReceiptRetrieveRequest {
	return ApiV1PaymentsReceiptRetrieveRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return PaymentReceipt
func (a *OrdersAndPaymentsAPIService) V1PaymentsReceiptRetrieveExecute(r ApiV1PaymentsReceiptRetrieveRequest) (*PaymentReceipt, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PaymentReceipt
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrdersAndPaymentsAPIService.V1PaymentsReceiptRetrieve")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/payments/{id}/receipt"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1PaymentsRetrieveRequest struct {
	ctx context.Context
	ApiService OrdersAndPaymentsAPI
	id string
}

func (r ApiV1PaymentsRetrieveRequest) Execute() (*SettlementJob, *http.Response, error) {
	return r.ApiService.V1PaymentsRetrieveExecute(r)
}

/*
V1PaymentsRetrieve Method for V1PaymentsRetrieve

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiV1PaymentsRetrieveRequest
*/
func (a *OrdersAndPaymentsAPIService) V1PaymentsRetrieve(ctx context.Context, id string) ApiV1PaymentsRetrieveRequest {
	return ApiV1PaymentsRetrieveRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return SettlementJob
func (a *OrdersAndPaymentsAPIService) V1PaymentsRetrieveExecute(r ApiV1PaymentsRetrieveRequest) (*SettlementJob, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SettlementJob
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrdersAndPaymentsAPIService.V1PaymentsRetrieve")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/payments/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
