/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type ReceivingAddressesAPI interface {

	/*
	V1ReceivingAddressControlCapabilitiesRetrieve Method for V1ReceivingAddressControlCapabilitiesRetrieve

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1ReceivingAddressControlCapabilitiesRetrieveRequest
	*/
	V1ReceivingAddressControlCapabilitiesRetrieve(ctx context.Context) ApiV1ReceivingAddressControlCapabilitiesRetrieveRequest

	// V1ReceivingAddressControlCapabilitiesRetrieveExecute executes the request
	//  @return ExternalAddressControlCapabilities
	V1ReceivingAddressControlCapabilitiesRetrieveExecute(r ApiV1ReceivingAddressControlCapabilitiesRetrieveRequest) (*ExternalAddressControlCapabilities, *http.Response, error)

	/*
	V1ReceivingAddressControlChallengesCreate Method for V1ReceivingAddressControlChallengesCreate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1ReceivingAddressControlChallengesCreateRequest
	*/
	V1ReceivingAddressControlChallengesCreate(ctx context.Context) ApiV1ReceivingAddressControlChallengesCreateRequest

	// V1ReceivingAddressControlChallengesCreateExecute executes the request
	//  @return ExternalAddressControlChallenge
	V1ReceivingAddressControlChallengesCreateExecute(r ApiV1ReceivingAddressControlChallengesCreateRequest) (*ExternalAddressControlChallenge, *http.Response, error)

	/*
	V1ReceivingAddressesActivateCreate Method for V1ReceivingAddressesActivateCreate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param readinessId
	@return ApiV1ReceivingAddressesActivateCreateRequest
	*/
	V1ReceivingAddressesActivateCreate(ctx context.Context, readinessId string) ApiV1ReceivingAddressesActivateCreateRequest

	// V1ReceivingAddressesActivateCreateExecute executes the request
	//  @return ExternalReceivingAddress
	V1ReceivingAddressesActivateCreateExecute(r ApiV1ReceivingAddressesActivateCreateRequest) (*ExternalReceivingAddress, *http.Response, error)

	/*
	V1ReceivingAddressesCreate Method for V1ReceivingAddressesCreate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1ReceivingAddressesCreateRequest
	*/
	V1ReceivingAddressesCreate(ctx context.Context) ApiV1ReceivingAddressesCreateRequest

	// V1ReceivingAddressesCreateExecute executes the request
	//  @return ExternalReceivingAddress
	V1ReceivingAddressesCreateExecute(r ApiV1ReceivingAddressesCreateRequest) (*ExternalReceivingAddress, *http.Response, error)

	/*
	V1ReceivingAddressesList Method for V1ReceivingAddressesList

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1ReceivingAddressesListRequest
	*/
	V1ReceivingAddressesList(ctx context.Context) ApiV1ReceivingAddressesListRequest

	// V1ReceivingAddressesListExecute executes the request
	//  @return []ExternalReceivingAddress
	V1ReceivingAddressesListExecute(r ApiV1ReceivingAddressesListRequest) ([]ExternalReceivingAddress, *http.Response, error)

	/*
	V1ReceivingAddressesReadinessRefreshesCreate Method for V1ReceivingAddressesReadinessRefreshesCreate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param readinessId
	@return ApiV1ReceivingAddressesReadinessRefreshesCreateRequest
	*/
	V1ReceivingAddressesReadinessRefreshesCreate(ctx context.Context, readinessId string) ApiV1ReceivingAddressesReadinessRefreshesCreateRequest

	// V1ReceivingAddressesReadinessRefreshesCreateExecute executes the request
	//  @return ExternalReceivingAddress
	V1ReceivingAddressesReadinessRefreshesCreateExecute(r ApiV1ReceivingAddressesReadinessRefreshesCreateRequest) (*ExternalReceivingAddress, *http.Response, error)

	/*
	V1ReceivingAddressesRotationsCreate Method for V1ReceivingAddressesRotationsCreate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param readinessId
	@return ApiV1ReceivingAddressesRotationsCreateRequest
	*/
	V1ReceivingAddressesRotationsCreate(ctx context.Context, readinessId string) ApiV1ReceivingAddressesRotationsCreateRequest

	// V1ReceivingAddressesRotationsCreateExecute executes the request
	//  @return ExternalReceivingAddress
	V1ReceivingAddressesRotationsCreateExecute(r ApiV1ReceivingAddressesRotationsCreateRequest) (*ExternalReceivingAddress, *http.Response, error)
}

// ReceivingAddressesAPIService ReceivingAddressesAPI service
type ReceivingAddressesAPIService service

type ApiV1ReceivingAddressControlCapabilitiesRetrieveRequest struct {
	ctx context.Context
	ApiService ReceivingAddressesAPI
}

func (r ApiV1ReceivingAddressControlCapabilitiesRetrieveRequest) Execute() (*ExternalAddressControlCapabilities, *http.Response, error) {
	return r.ApiService.V1ReceivingAddressControlCapabilitiesRetrieveExecute(r)
}

/*
V1ReceivingAddressControlCapabilitiesRetrieve Method for V1ReceivingAddressControlCapabilitiesRetrieve

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1ReceivingAddressControlCapabilitiesRetrieveRequest
*/
func (a *ReceivingAddressesAPIService) V1ReceivingAddressControlCapabilitiesRetrieve(ctx context.Context) ApiV1ReceivingAddressControlCapabilitiesRetrieveRequest {
	return ApiV1ReceivingAddressControlCapabilitiesRetrieveRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ExternalAddressControlCapabilities
func (a *ReceivingAddressesAPIService) V1ReceivingAddressControlCapabilitiesRetrieveExecute(r ApiV1ReceivingAddressControlCapabilitiesRetrieveRequest) (*ExternalAddressControlCapabilities, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ExternalAddressControlCapabilities
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReceivingAddressesAPIService.V1ReceivingAddressControlCapabilitiesRetrieve")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/receiving-address-control-capabilities"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1ReceivingAddressControlChallengesCreateRequest struct {
	ctx context.Context
	ApiService ReceivingAddressesAPI
	idempotencyKey *string
	externalAddressControlChallengeCreate *ExternalAddressControlChallengeCreate
}

// Unique mutation key; replaying different content returns HTTP 409.
func (r ApiV1ReceivingAddressControlChallengesCreateRequest) IdempotencyKey(idempotencyKey string) ApiV1ReceivingAddressControlChallengesCreateRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r ApiV1ReceivingAddressControlChallengesCreateRequest) ExternalAddressControlChallengeCreate(externalAddressControlChallengeCreate ExternalAddressControlChallengeCreate) ApiV1ReceivingAddressControlChallengesCreateRequest {
	r.externalAddressControlChallengeCreate = &externalAddressControlChallengeCreate
	return r
}

func (r ApiV1ReceivingAddressControlChallengesCreateRequest) Execute() (*ExternalAddressControlChallenge, *http.Response, error) {
	return r.ApiService.V1ReceivingAddressControlChallengesCreateExecute(r)
}

/*
V1ReceivingAddressControlChallengesCreate Method for V1ReceivingAddressControlChallengesCreate

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1ReceivingAddressControlChallengesCreateRequest
*/
func (a *ReceivingAddressesAPIService) V1ReceivingAddressControlChallengesCreate(ctx context.Context) ApiV1ReceivingAddressControlChallengesCreateRequest {
	return ApiV1ReceivingAddressControlChallengesCreateRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ExternalAddressControlChallenge
func (a *ReceivingAddressesAPIService) V1ReceivingAddressControlChallengesCreateExecute(r ApiV1ReceivingAddressControlChallengesCreateRequest) (*ExternalAddressControlChallenge, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ExternalAddressControlChallenge
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReceivingAddressesAPIService.V1ReceivingAddressControlChallengesCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/receiving-address-control-challenges"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.idempotencyKey == nil {
		return localVarReturnValue, nil, reportError("idempotencyKey is required and must be specified")
	}
	if r.externalAddressControlChallengeCreate == nil {
		return localVarReturnValue, nil, reportError("externalAddressControlChallengeCreate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	// body params
	localVarPostBody = r.externalAddressControlChallengeCreate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1ReceivingAddressesActivateCreateRequest struct {
	ctx context.Context
	ApiService ReceivingAddressesAPI
	idempotencyKey *string
	readinessId string
}

// Unique mutation key; replaying different content returns HTTP 409.
func (r ApiV1ReceivingAddressesActivateCreateRequest) IdempotencyKey(idempotencyKey string) ApiV1ReceivingAddressesActivateCreateRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r ApiV1ReceivingAddressesActivateCreateRequest) Execute() (*ExternalReceivingAddress, *http.Response, error) {
	return r.ApiService.V1ReceivingAddressesActivateCreateExecute(r)
}

/*
V1ReceivingAddressesActivateCreate Method for V1ReceivingAddressesActivateCreate

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param readinessId
 @return ApiV1ReceivingAddressesActivateCreateRequest
*/
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesActivateCreate(ctx context.Context, readinessId string) ApiV1ReceivingAddressesActivateCreateRequest {
	return ApiV1ReceivingAddressesActivateCreateRequest{
		ApiService: a,
		ctx: ctx,
		readinessId: readinessId,
	}
}

// Execute executes the request
//  @return ExternalReceivingAddress
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesActivateCreateExecute(r ApiV1ReceivingAddressesActivateCreateRequest) (*ExternalReceivingAddress, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ExternalReceivingAddress
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReceivingAddressesAPIService.V1ReceivingAddressesActivateCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/receiving-addresses/{readiness_id}/activate"
	localVarPath = strings.Replace(localVarPath, "{"+"readiness_id"+"}", url.PathEscape(parameterValueToString(r.readinessId, "readinessId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.idempotencyKey == nil {
		return localVarReturnValue, nil, reportError("idempotencyKey is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1ReceivingAddressesCreateRequest struct {
	ctx context.Context
	ApiService ReceivingAddressesAPI
	idempotencyKey *string
	externalReceivingAddressCreate *ExternalReceivingAddressCreate
}

// Unique mutation key; replaying different content returns HTTP 409.
func (r ApiV1ReceivingAddressesCreateRequest) IdempotencyKey(idempotencyKey string) ApiV1ReceivingAddressesCreateRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r ApiV1ReceivingAddressesCreateRequest) ExternalReceivingAddressCreate(externalReceivingAddressCreate ExternalReceivingAddressCreate) ApiV1ReceivingAddressesCreateRequest {
	r.externalReceivingAddressCreate = &externalReceivingAddressCreate
	return r
}

func (r ApiV1ReceivingAddressesCreateRequest) Execute() (*ExternalReceivingAddress, *http.Response, error) {
	return r.ApiService.V1ReceivingAddressesCreateExecute(r)
}

/*
V1ReceivingAddressesCreate Method for V1ReceivingAddressesCreate

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1ReceivingAddressesCreateRequest
*/
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesCreate(ctx context.Context) ApiV1ReceivingAddressesCreateRequest {
	return ApiV1ReceivingAddressesCreateRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ExternalReceivingAddress
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesCreateExecute(r ApiV1ReceivingAddressesCreateRequest) (*ExternalReceivingAddress, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ExternalReceivingAddress
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReceivingAddressesAPIService.V1ReceivingAddressesCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/receiving-addresses"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.idempotencyKey == nil {
		return localVarReturnValue, nil, reportError("idempotencyKey is required and must be specified")
	}
	if r.externalReceivingAddressCreate == nil {
		return localVarReturnValue, nil, reportError("externalReceivingAddressCreate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	// body params
	localVarPostBody = r.externalReceivingAddressCreate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1ReceivingAddressesListRequest struct {
	ctx context.Context
	ApiService ReceivingAddressesAPI
	cursor *string
	pageSize *int32
}

// Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link.
func (r ApiV1ReceivingAddressesListRequest) Cursor(cursor string) ApiV1ReceivingAddressesListRequest {
	r.cursor = &cursor
	return r
}

// Number of results in the bounded array page (default and maximum 100).
func (r ApiV1ReceivingAddressesListRequest) PageSize(pageSize int32) ApiV1ReceivingAddressesListRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiV1ReceivingAddressesListRequest) Execute() ([]ExternalReceivingAddress, *http.Response, error) {
	return r.ApiService.V1ReceivingAddressesListExecute(r)
}

/*
V1ReceivingAddressesList Method for V1ReceivingAddressesList

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1ReceivingAddressesListRequest
*/
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesList(ctx context.Context) ApiV1ReceivingAddressesListRequest {
	return ApiV1ReceivingAddressesListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []ExternalReceivingAddress
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesListExecute(r ApiV1ReceivingAddressesListRequest) ([]ExternalReceivingAddress, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ExternalReceivingAddress
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReceivingAddressesAPIService.V1ReceivingAddressesList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/receiving-addresses"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 100
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1ReceivingAddressesReadinessRefreshesCreateRequest struct {
	ctx context.Context
	ApiService ReceivingAddressesAPI
	idempotencyKey *string
	readinessId string
}

// Unique mutation key; replaying different content returns HTTP 409.
func (r ApiV1ReceivingAddressesReadinessRefreshesCreateRequest) IdempotencyKey(idempotencyKey string) ApiV1ReceivingAddressesReadinessRefreshesCreateRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r ApiV1ReceivingAddressesReadinessRefreshesCreateRequest) Execute() (*ExternalReceivingAddress, *http.Response, error) {
	return r.ApiService.V1ReceivingAddressesReadinessRefreshesCreateExecute(r)
}

/*
V1ReceivingAddressesReadinessRefreshesCreate Method for V1ReceivingAddressesReadinessRefreshesCreate

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param readinessId
 @return ApiV1ReceivingAddressesReadinessRefreshesCreateRequest
*/
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesReadinessRefreshesCreate(ctx context.Context, readinessId string) ApiV1ReceivingAddressesReadinessRefreshesCreateRequest {
	return ApiV1ReceivingAddressesReadinessRefreshesCreateRequest{
		ApiService: a,
		ctx: ctx,
		readinessId: readinessId,
	}
}

// Execute executes the request
//  @return ExternalReceivingAddress
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesReadinessRefreshesCreateExecute(r ApiV1ReceivingAddressesReadinessRefreshesCreateRequest) (*ExternalReceivingAddress, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ExternalReceivingAddress
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReceivingAddressesAPIService.V1ReceivingAddressesReadinessRefreshesCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/receiving-addresses/{readiness_id}/readiness-refreshes"
	localVarPath = strings.Replace(localVarPath, "{"+"readiness_id"+"}", url.PathEscape(parameterValueToString(r.readinessId, "readinessId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.idempotencyKey == nil {
		return localVarReturnValue, nil, reportError("idempotencyKey is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1ReceivingAddressesRotationsCreateRequest struct {
	ctx context.Context
	ApiService ReceivingAddressesAPI
	idempotencyKey *string
	readinessId string
	externalReceivingAddressRotation *ExternalReceivingAddressRotation
}

// Unique mutation key; replaying different content returns HTTP 409.
func (r ApiV1ReceivingAddressesRotationsCreateRequest) IdempotencyKey(idempotencyKey string) ApiV1ReceivingAddressesRotationsCreateRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r ApiV1ReceivingAddressesRotationsCreateRequest) ExternalReceivingAddressRotation(externalReceivingAddressRotation ExternalReceivingAddressRotation) ApiV1ReceivingAddressesRotationsCreateRequest {
	r.externalReceivingAddressRotation = &externalReceivingAddressRotation
	return r
}

func (r ApiV1ReceivingAddressesRotationsCreateRequest) Execute() (*ExternalReceivingAddress, *http.Response, error) {
	return r.ApiService.V1ReceivingAddressesRotationsCreateExecute(r)
}

/*
V1ReceivingAddressesRotationsCreate Method for V1ReceivingAddressesRotationsCreate

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param readinessId
 @return ApiV1ReceivingAddressesRotationsCreateRequest
*/
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesRotationsCreate(ctx context.Context, readinessId string) ApiV1ReceivingAddressesRotationsCreateRequest {
	return ApiV1ReceivingAddressesRotationsCreateRequest{
		ApiService: a,
		ctx: ctx,
		readinessId: readinessId,
	}
}

// Execute executes the request
//  @return ExternalReceivingAddress
func (a *ReceivingAddressesAPIService) V1ReceivingAddressesRotationsCreateExecute(r ApiV1ReceivingAddressesRotationsCreateRequest) (*ExternalReceivingAddress, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ExternalReceivingAddress
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReceivingAddressesAPIService.V1ReceivingAddressesRotationsCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/receiving-addresses/{readiness_id}/rotations"
	localVarPath = strings.Replace(localVarPath, "{"+"readiness_id"+"}", url.PathEscape(parameterValueToString(r.readinessId, "readinessId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.idempotencyKey == nil {
		return localVarReturnValue, nil, reportError("idempotencyKey is required and must be specified")
	}
	if r.externalReceivingAddressRotation == nil {
		return localVarReturnValue, nil, reportError("externalReceivingAddressRotation is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	// body params
	localVarPostBody = r.externalReceivingAddressRotation
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
