/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the PriceInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceInput{}

// PriceInput struct for PriceInput
type PriceInput struct {
	AssetId string `json:"asset_id" validate:"regexp=^[-a-zA-Z0-9_]+$"`
	WalletVersionId string `json:"wallet_version_id"`
	AmountAtomic string `json:"amount_atomic" validate:"regexp=^(0|[1-9][0-9]*)$"`
	MaxTimeoutSeconds int32 `json:"max_timeout_seconds"`
	AdditionalProperties map[string]interface{}
}

type _PriceInput PriceInput

// NewPriceInput instantiates a new PriceInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceInput(assetId string, walletVersionId string, amountAtomic string, maxTimeoutSeconds int32) *PriceInput {
	this := PriceInput{}
	this.AssetId = assetId
	this.WalletVersionId = walletVersionId
	this.AmountAtomic = amountAtomic
	this.MaxTimeoutSeconds = maxTimeoutSeconds
	return &this
}

// NewPriceInputWithDefaults instantiates a new PriceInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceInputWithDefaults() *PriceInput {
	this := PriceInput{}
	return &this
}

// GetAssetId returns the AssetId field value
func (o *PriceInput) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *PriceInput) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *PriceInput) SetAssetId(v string) {
	o.AssetId = v
}

// GetWalletVersionId returns the WalletVersionId field value
func (o *PriceInput) GetWalletVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletVersionId
}

// GetWalletVersionIdOk returns a tuple with the WalletVersionId field value
// and a boolean to check if the value has been set.
func (o *PriceInput) GetWalletVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletVersionId, true
}

// SetWalletVersionId sets field value
func (o *PriceInput) SetWalletVersionId(v string) {
	o.WalletVersionId = v
}

// GetAmountAtomic returns the AmountAtomic field value
func (o *PriceInput) GetAmountAtomic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountAtomic
}

// GetAmountAtomicOk returns a tuple with the AmountAtomic field value
// and a boolean to check if the value has been set.
func (o *PriceInput) GetAmountAtomicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountAtomic, true
}

// SetAmountAtomic sets field value
func (o *PriceInput) SetAmountAtomic(v string) {
	o.AmountAtomic = v
}

// GetMaxTimeoutSeconds returns the MaxTimeoutSeconds field value
func (o *PriceInput) GetMaxTimeoutSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxTimeoutSeconds
}

// GetMaxTimeoutSecondsOk returns a tuple with the MaxTimeoutSeconds field value
// and a boolean to check if the value has been set.
func (o *PriceInput) GetMaxTimeoutSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxTimeoutSeconds, true
}

// SetMaxTimeoutSeconds sets field value
func (o *PriceInput) SetMaxTimeoutSeconds(v int32) {
	o.MaxTimeoutSeconds = v
}

func (o PriceInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_id"] = o.AssetId
	toSerialize["wallet_version_id"] = o.WalletVersionId
	toSerialize["amount_atomic"] = o.AmountAtomic
	toSerialize["max_timeout_seconds"] = o.MaxTimeoutSeconds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PriceInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_id",
		"wallet_version_id",
		"amount_atomic",
		"max_timeout_seconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPriceInput := _PriceInput{}

	err = json.Unmarshal(data, &varPriceInput)

	if err != nil {
		return err
	}

	*o = PriceInput(varPriceInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "asset_id")
		delete(additionalProperties, "wallet_version_id")
		delete(additionalProperties, "amount_atomic")
		delete(additionalProperties, "max_timeout_seconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePriceInput struct {
	value *PriceInput
	isSet bool
}

func (v NullablePriceInput) Get() *PriceInput {
	return v.value
}

func (v *NullablePriceInput) Set(val *PriceInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceInput(val *PriceInput) *NullablePriceInput {
	return &NullablePriceInput{value: val, isSet: true}
}

func (v NullablePriceInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
