/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the PaymentReceipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentReceipt{}

// PaymentReceipt struct for PaymentReceipt
type PaymentReceipt struct {
	Id string `json:"id"`
	OrderId string `json:"order_id"`
	SettlementJobId string `json:"settlement_job_id"`
	Receipt interface{} `json:"receipt"`
	ReceiptDigest string `json:"receipt_digest"`
	Signature string `json:"signature"`
	SigningKeyVersion string `json:"signing_key_version"`
	EligibleAlternatives []NetworkFeeAlternative `json:"eligible_alternatives"`
	FeePolicy NullableFeePolicyDocument `json:"fee_policy"`
	FeeEvidence NullableNetworkFeeEvidence `json:"fee_evidence"`
	FeeQuoteDigest NullableString `json:"fee_quote_digest"`
	FeeQuoteExpiresAt NullableTime `json:"fee_quote_expires_at"`
	SettlementAmountAtomic string `json:"settlement_amount_atomic"`
	CreatedAt time.Time `json:"created_at"`
	AdditionalProperties map[string]interface{}
}

type _PaymentReceipt PaymentReceipt

// NewPaymentReceipt instantiates a new PaymentReceipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentReceipt(id string, orderId string, settlementJobId string, receipt interface{}, receiptDigest string, signature string, signingKeyVersion string, eligibleAlternatives []NetworkFeeAlternative, feePolicy NullableFeePolicyDocument, feeEvidence NullableNetworkFeeEvidence, feeQuoteDigest NullableString, feeQuoteExpiresAt NullableTime, settlementAmountAtomic string, createdAt time.Time) *PaymentReceipt {
	this := PaymentReceipt{}
	this.Id = id
	this.OrderId = orderId
	this.SettlementJobId = settlementJobId
	this.Receipt = receipt
	this.ReceiptDigest = receiptDigest
	this.Signature = signature
	this.SigningKeyVersion = signingKeyVersion
	this.EligibleAlternatives = eligibleAlternatives
	this.FeePolicy = feePolicy
	this.FeeEvidence = feeEvidence
	this.FeeQuoteDigest = feeQuoteDigest
	this.FeeQuoteExpiresAt = feeQuoteExpiresAt
	this.SettlementAmountAtomic = settlementAmountAtomic
	this.CreatedAt = createdAt
	return &this
}

// NewPaymentReceiptWithDefaults instantiates a new PaymentReceipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentReceiptWithDefaults() *PaymentReceipt {
	this := PaymentReceipt{}
	return &this
}

// GetId returns the Id field value
func (o *PaymentReceipt) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PaymentReceipt) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PaymentReceipt) SetId(v string) {
	o.Id = v
}

// GetOrderId returns the OrderId field value
func (o *PaymentReceipt) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *PaymentReceipt) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *PaymentReceipt) SetOrderId(v string) {
	o.OrderId = v
}

// GetSettlementJobId returns the SettlementJobId field value
func (o *PaymentReceipt) GetSettlementJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SettlementJobId
}

// GetSettlementJobIdOk returns a tuple with the SettlementJobId field value
// and a boolean to check if the value has been set.
func (o *PaymentReceipt) GetSettlementJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementJobId, true
}

// SetSettlementJobId sets field value
func (o *PaymentReceipt) SetSettlementJobId(v string) {
	o.SettlementJobId = v
}

// GetReceipt returns the Receipt field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PaymentReceipt) GetReceipt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Receipt
}

// GetReceiptOk returns a tuple with the Receipt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentReceipt) GetReceiptOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Receipt) {
		return nil, false
	}
	return &o.Receipt, true
}

// SetReceipt sets field value
func (o *PaymentReceipt) SetReceipt(v interface{}) {
	o.Receipt = v
}

// GetReceiptDigest returns the ReceiptDigest field value
func (o *PaymentReceipt) GetReceiptDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReceiptDigest
}

// GetReceiptDigestOk returns a tuple with the ReceiptDigest field value
// and a boolean to check if the value has been set.
func (o *PaymentReceipt) GetReceiptDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceiptDigest, true
}

// SetReceiptDigest sets field value
func (o *PaymentReceipt) SetReceiptDigest(v string) {
	o.ReceiptDigest = v
}

// GetSignature returns the Signature field value
func (o *PaymentReceipt) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *PaymentReceipt) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *PaymentReceipt) SetSignature(v string) {
	o.Signature = v
}

// GetSigningKeyVersion returns the SigningKeyVersion field value
func (o *PaymentReceipt) GetSigningKeyVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SigningKeyVersion
}

// GetSigningKeyVersionOk returns a tuple with the SigningKeyVersion field value
// and a boolean to check if the value has been set.
func (o *PaymentReceipt) GetSigningKeyVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SigningKeyVersion, true
}

// SetSigningKeyVersion sets field value
func (o *PaymentReceipt) SetSigningKeyVersion(v string) {
	o.SigningKeyVersion = v
}

// GetEligibleAlternatives returns the EligibleAlternatives field value
func (o *PaymentReceipt) GetEligibleAlternatives() []NetworkFeeAlternative {
	if o == nil {
		var ret []NetworkFeeAlternative
		return ret
	}

	return o.EligibleAlternatives
}

// GetEligibleAlternativesOk returns a tuple with the EligibleAlternatives field value
// and a boolean to check if the value has been set.
func (o *PaymentReceipt) GetEligibleAlternativesOk() ([]NetworkFeeAlternative, bool) {
	if o == nil {
		return nil, false
	}
	return o.EligibleAlternatives, true
}

// SetEligibleAlternatives sets field value
func (o *PaymentReceipt) SetEligibleAlternatives(v []NetworkFeeAlternative) {
	o.EligibleAlternatives = v
}

// GetFeePolicy returns the FeePolicy field value
// If the value is explicit nil, the zero value for FeePolicyDocument will be returned
func (o *PaymentReceipt) GetFeePolicy() FeePolicyDocument {
	if o == nil || o.FeePolicy.Get() == nil {
		var ret FeePolicyDocument
		return ret
	}

	return *o.FeePolicy.Get()
}

// GetFeePolicyOk returns a tuple with the FeePolicy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentReceipt) GetFeePolicyOk() (*FeePolicyDocument, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeePolicy.Get(), o.FeePolicy.IsSet()
}

// SetFeePolicy sets field value
func (o *PaymentReceipt) SetFeePolicy(v FeePolicyDocument) {
	o.FeePolicy.Set(&v)
}

// GetFeeEvidence returns the FeeEvidence field value
// If the value is explicit nil, the zero value for NetworkFeeEvidence will be returned
func (o *PaymentReceipt) GetFeeEvidence() NetworkFeeEvidence {
	if o == nil || o.FeeEvidence.Get() == nil {
		var ret NetworkFeeEvidence
		return ret
	}

	return *o.FeeEvidence.Get()
}

// GetFeeEvidenceOk returns a tuple with the FeeEvidence field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentReceipt) GetFeeEvidenceOk() (*NetworkFeeEvidence, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeeEvidence.Get(), o.FeeEvidence.IsSet()
}

// SetFeeEvidence sets field value
func (o *PaymentReceipt) SetFeeEvidence(v NetworkFeeEvidence) {
	o.FeeEvidence.Set(&v)
}

// GetFeeQuoteDigest returns the FeeQuoteDigest field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentReceipt) GetFeeQuoteDigest() string {
	if o == nil || o.FeeQuoteDigest.Get() == nil {
		var ret string
		return ret
	}

	return *o.FeeQuoteDigest.Get()
}

// GetFeeQuoteDigestOk returns a tuple with the FeeQuoteDigest field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentReceipt) GetFeeQuoteDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeeQuoteDigest.Get(), o.FeeQuoteDigest.IsSet()
}

// SetFeeQuoteDigest sets field value
func (o *PaymentReceipt) SetFeeQuoteDigest(v string) {
	o.FeeQuoteDigest.Set(&v)
}

// GetFeeQuoteExpiresAt returns the FeeQuoteExpiresAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *PaymentReceipt) GetFeeQuoteExpiresAt() time.Time {
	if o == nil || o.FeeQuoteExpiresAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.FeeQuoteExpiresAt.Get()
}

// GetFeeQuoteExpiresAtOk returns a tuple with the FeeQuoteExpiresAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentReceipt) GetFeeQuoteExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeeQuoteExpiresAt.Get(), o.FeeQuoteExpiresAt.IsSet()
}

// SetFeeQuoteExpiresAt sets field value
func (o *PaymentReceipt) SetFeeQuoteExpiresAt(v time.Time) {
	o.FeeQuoteExpiresAt.Set(&v)
}

// GetSettlementAmountAtomic returns the SettlementAmountAtomic field value
func (o *PaymentReceipt) GetSettlementAmountAtomic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SettlementAmountAtomic
}

// GetSettlementAmountAtomicOk returns a tuple with the SettlementAmountAtomic field value
// and a boolean to check if the value has been set.
func (o *PaymentReceipt) GetSettlementAmountAtomicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementAmountAtomic, true
}

// SetSettlementAmountAtomic sets field value
func (o *PaymentReceipt) SetSettlementAmountAtomic(v string) {
	o.SettlementAmountAtomic = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PaymentReceipt) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PaymentReceipt) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PaymentReceipt) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o PaymentReceipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentReceipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["order_id"] = o.OrderId
	toSerialize["settlement_job_id"] = o.SettlementJobId
	if o.Receipt != nil {
		toSerialize["receipt"] = o.Receipt
	}
	toSerialize["receipt_digest"] = o.ReceiptDigest
	toSerialize["signature"] = o.Signature
	toSerialize["signing_key_version"] = o.SigningKeyVersion
	toSerialize["eligible_alternatives"] = o.EligibleAlternatives
	toSerialize["fee_policy"] = o.FeePolicy.Get()
	toSerialize["fee_evidence"] = o.FeeEvidence.Get()
	toSerialize["fee_quote_digest"] = o.FeeQuoteDigest.Get()
	toSerialize["fee_quote_expires_at"] = o.FeeQuoteExpiresAt.Get()
	toSerialize["settlement_amount_atomic"] = o.SettlementAmountAtomic
	toSerialize["created_at"] = o.CreatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentReceipt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"order_id",
		"settlement_job_id",
		"receipt",
		"receipt_digest",
		"signature",
		"signing_key_version",
		"eligible_alternatives",
		"fee_policy",
		"fee_evidence",
		"fee_quote_digest",
		"fee_quote_expires_at",
		"settlement_amount_atomic",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentReceipt := _PaymentReceipt{}

	err = json.Unmarshal(data, &varPaymentReceipt)

	if err != nil {
		return err
	}

	*o = PaymentReceipt(varPaymentReceipt)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "order_id")
		delete(additionalProperties, "settlement_job_id")
		delete(additionalProperties, "receipt")
		delete(additionalProperties, "receipt_digest")
		delete(additionalProperties, "signature")
		delete(additionalProperties, "signing_key_version")
		delete(additionalProperties, "eligible_alternatives")
		delete(additionalProperties, "fee_policy")
		delete(additionalProperties, "fee_evidence")
		delete(additionalProperties, "fee_quote_digest")
		delete(additionalProperties, "fee_quote_expires_at")
		delete(additionalProperties, "settlement_amount_atomic")
		delete(additionalProperties, "created_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaymentReceipt struct {
	value *PaymentReceipt
	isSet bool
}

func (v NullablePaymentReceipt) Get() *PaymentReceipt {
	return v.value
}

func (v *NullablePaymentReceipt) Set(val *PaymentReceipt) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentReceipt(val *PaymentReceipt) *NullablePaymentReceipt {
	return &NullablePaymentReceipt{value: val, isSet: true}
}

func (v NullablePaymentReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
