/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// PaymentReadinessStateEnum * `accepting` - accepting * `setup_required` - setup_required * `temporarily_unavailable` - temporarily_unavailable * `paused_by_tenant` - paused_by_tenant
type PaymentReadinessStateEnum string

// List of PaymentReadinessStateEnum
const (
	PAYMENTREADINESSSTATEENUM_ACCEPTING PaymentReadinessStateEnum = "accepting"
	PAYMENTREADINESSSTATEENUM_SETUP_REQUIRED PaymentReadinessStateEnum = "setup_required"
	PAYMENTREADINESSSTATEENUM_TEMPORARILY_UNAVAILABLE PaymentReadinessStateEnum = "temporarily_unavailable"
	PAYMENTREADINESSSTATEENUM_PAUSED_BY_TENANT PaymentReadinessStateEnum = "paused_by_tenant"
	PAYMENTREADINESSSTATEENUM_UNKNOWN_DEFAULT_OPEN_API PaymentReadinessStateEnum = "unknown_default_open_api"
)

// All allowed values of PaymentReadinessStateEnum enum
var AllowedPaymentReadinessStateEnumEnumValues = []PaymentReadinessStateEnum{
	"accepting",
	"setup_required",
	"temporarily_unavailable",
	"paused_by_tenant",
	"unknown_default_open_api",
}

func (v *PaymentReadinessStateEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PaymentReadinessStateEnum(value)
	for _, existing := range AllowedPaymentReadinessStateEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = PAYMENTREADINESSSTATEENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewPaymentReadinessStateEnumFromValue returns a pointer to a valid PaymentReadinessStateEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPaymentReadinessStateEnumFromValue(v string) (*PaymentReadinessStateEnum, error) {
	ev := PaymentReadinessStateEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PaymentReadinessStateEnum: valid values are %v", v, AllowedPaymentReadinessStateEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PaymentReadinessStateEnum) IsValid() bool {
	for _, existing := range AllowedPaymentReadinessStateEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PaymentReadinessStateEnum value
func (v PaymentReadinessStateEnum) Ptr() *PaymentReadinessStateEnum {
	return &v
}

type NullablePaymentReadinessStateEnum struct {
	value *PaymentReadinessStateEnum
	isSet bool
}

func (v NullablePaymentReadinessStateEnum) Get() *PaymentReadinessStateEnum {
	return v.value
}

func (v *NullablePaymentReadinessStateEnum) Set(val *PaymentReadinessStateEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentReadinessStateEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentReadinessStateEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentReadinessStateEnum(val *PaymentReadinessStateEnum) *NullablePaymentReadinessStateEnum {
	return &NullablePaymentReadinessStateEnum{value: val, isSet: true}
}

func (v NullablePaymentReadinessStateEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentReadinessStateEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
