/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Order type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Order{}

// Order struct for Order
type Order struct {
	Id string `json:"id"`
	ResourceVersionId string `json:"resource_version_id"`
	RequestFingerprint string `json:"request_fingerprint"`
	PaymentIdentifier string `json:"payment_identifier"`
	BuyerPaymentIdentifier NullableString `json:"buyer_payment_identifier"`
	Status OrderStatusEnum `json:"status"`
	PaidAt NullableTime `json:"paid_at"`
	FulfilledAt NullableTime `json:"fulfilled_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	AdditionalProperties map[string]interface{}
}

type _Order Order

// NewOrder instantiates a new Order object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrder(id string, resourceVersionId string, requestFingerprint string, paymentIdentifier string, buyerPaymentIdentifier NullableString, status OrderStatusEnum, paidAt NullableTime, fulfilledAt NullableTime, createdAt time.Time, updatedAt time.Time) *Order {
	this := Order{}
	this.Id = id
	this.ResourceVersionId = resourceVersionId
	this.RequestFingerprint = requestFingerprint
	this.PaymentIdentifier = paymentIdentifier
	this.BuyerPaymentIdentifier = buyerPaymentIdentifier
	this.Status = status
	this.PaidAt = paidAt
	this.FulfilledAt = fulfilledAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewOrderWithDefaults instantiates a new Order object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderWithDefaults() *Order {
	this := Order{}
	return &this
}

// GetId returns the Id field value
func (o *Order) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Order) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Order) SetId(v string) {
	o.Id = v
}

// GetResourceVersionId returns the ResourceVersionId field value
func (o *Order) GetResourceVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceVersionId
}

// GetResourceVersionIdOk returns a tuple with the ResourceVersionId field value
// and a boolean to check if the value has been set.
func (o *Order) GetResourceVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceVersionId, true
}

// SetResourceVersionId sets field value
func (o *Order) SetResourceVersionId(v string) {
	o.ResourceVersionId = v
}

// GetRequestFingerprint returns the RequestFingerprint field value
func (o *Order) GetRequestFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestFingerprint
}

// GetRequestFingerprintOk returns a tuple with the RequestFingerprint field value
// and a boolean to check if the value has been set.
func (o *Order) GetRequestFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestFingerprint, true
}

// SetRequestFingerprint sets field value
func (o *Order) SetRequestFingerprint(v string) {
	o.RequestFingerprint = v
}

// GetPaymentIdentifier returns the PaymentIdentifier field value
func (o *Order) GetPaymentIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentIdentifier
}

// GetPaymentIdentifierOk returns a tuple with the PaymentIdentifier field value
// and a boolean to check if the value has been set.
func (o *Order) GetPaymentIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentIdentifier, true
}

// SetPaymentIdentifier sets field value
func (o *Order) SetPaymentIdentifier(v string) {
	o.PaymentIdentifier = v
}

// GetBuyerPaymentIdentifier returns the BuyerPaymentIdentifier field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Order) GetBuyerPaymentIdentifier() string {
	if o == nil || o.BuyerPaymentIdentifier.Get() == nil {
		var ret string
		return ret
	}

	return *o.BuyerPaymentIdentifier.Get()
}

// GetBuyerPaymentIdentifierOk returns a tuple with the BuyerPaymentIdentifier field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Order) GetBuyerPaymentIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BuyerPaymentIdentifier.Get(), o.BuyerPaymentIdentifier.IsSet()
}

// SetBuyerPaymentIdentifier sets field value
func (o *Order) SetBuyerPaymentIdentifier(v string) {
	o.BuyerPaymentIdentifier.Set(&v)
}

// GetStatus returns the Status field value
func (o *Order) GetStatus() OrderStatusEnum {
	if o == nil {
		var ret OrderStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Order) GetStatusOk() (*OrderStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Order) SetStatus(v OrderStatusEnum) {
	o.Status = v
}

// GetPaidAt returns the PaidAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Order) GetPaidAt() time.Time {
	if o == nil || o.PaidAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.PaidAt.Get()
}

// GetPaidAtOk returns a tuple with the PaidAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Order) GetPaidAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaidAt.Get(), o.PaidAt.IsSet()
}

// SetPaidAt sets field value
func (o *Order) SetPaidAt(v time.Time) {
	o.PaidAt.Set(&v)
}

// GetFulfilledAt returns the FulfilledAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Order) GetFulfilledAt() time.Time {
	if o == nil || o.FulfilledAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.FulfilledAt.Get()
}

// GetFulfilledAtOk returns a tuple with the FulfilledAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Order) GetFulfilledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FulfilledAt.Get(), o.FulfilledAt.IsSet()
}

// SetFulfilledAt sets field value
func (o *Order) SetFulfilledAt(v time.Time) {
	o.FulfilledAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *Order) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Order) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Order) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Order) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Order) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Order) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Order) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Order) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["resource_version_id"] = o.ResourceVersionId
	toSerialize["request_fingerprint"] = o.RequestFingerprint
	toSerialize["payment_identifier"] = o.PaymentIdentifier
	toSerialize["buyer_payment_identifier"] = o.BuyerPaymentIdentifier.Get()
	toSerialize["status"] = o.Status
	toSerialize["paid_at"] = o.PaidAt.Get()
	toSerialize["fulfilled_at"] = o.FulfilledAt.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Order) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"resource_version_id",
		"request_fingerprint",
		"payment_identifier",
		"buyer_payment_identifier",
		"status",
		"paid_at",
		"fulfilled_at",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrder := _Order{}

	err = json.Unmarshal(data, &varOrder)

	if err != nil {
		return err
	}

	*o = Order(varOrder)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "resource_version_id")
		delete(additionalProperties, "request_fingerprint")
		delete(additionalProperties, "payment_identifier")
		delete(additionalProperties, "buyer_payment_identifier")
		delete(additionalProperties, "status")
		delete(additionalProperties, "paid_at")
		delete(additionalProperties, "fulfilled_at")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrder struct {
	value *Order
	isSet bool
}

func (v NullableOrder) Get() *Order {
	return v.value
}

func (v *NullableOrder) Set(val *Order) {
	v.value = val
	v.isSet = true
}

func (v NullableOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrder(val *Order) *NullableOrder {
	return &NullableOrder{value: val, isSet: true}
}

func (v NullableOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
