/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourceVersionActivate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceVersionActivate{}

// ResourceVersionActivate struct for ResourceVersionActivate
type ResourceVersionActivate struct {
	ExpectedTargetVersion int32 `json:"expected_target_version"`
	ExpectedActiveVersionId NullableString `json:"expected_active_version_id"`
	AdditionalProperties map[string]interface{}
}

type _ResourceVersionActivate ResourceVersionActivate

// NewResourceVersionActivate instantiates a new ResourceVersionActivate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceVersionActivate(expectedTargetVersion int32, expectedActiveVersionId NullableString) *ResourceVersionActivate {
	this := ResourceVersionActivate{}
	this.ExpectedTargetVersion = expectedTargetVersion
	this.ExpectedActiveVersionId = expectedActiveVersionId
	return &this
}

// NewResourceVersionActivateWithDefaults instantiates a new ResourceVersionActivate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceVersionActivateWithDefaults() *ResourceVersionActivate {
	this := ResourceVersionActivate{}
	return &this
}

// GetExpectedTargetVersion returns the ExpectedTargetVersion field value
func (o *ResourceVersionActivate) GetExpectedTargetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpectedTargetVersion
}

// GetExpectedTargetVersionOk returns a tuple with the ExpectedTargetVersion field value
// and a boolean to check if the value has been set.
func (o *ResourceVersionActivate) GetExpectedTargetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedTargetVersion, true
}

// SetExpectedTargetVersion sets field value
func (o *ResourceVersionActivate) SetExpectedTargetVersion(v int32) {
	o.ExpectedTargetVersion = v
}

// GetExpectedActiveVersionId returns the ExpectedActiveVersionId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ResourceVersionActivate) GetExpectedActiveVersionId() string {
	if o == nil || o.ExpectedActiveVersionId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExpectedActiveVersionId.Get()
}

// GetExpectedActiveVersionIdOk returns a tuple with the ExpectedActiveVersionId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResourceVersionActivate) GetExpectedActiveVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedActiveVersionId.Get(), o.ExpectedActiveVersionId.IsSet()
}

// SetExpectedActiveVersionId sets field value
func (o *ResourceVersionActivate) SetExpectedActiveVersionId(v string) {
	o.ExpectedActiveVersionId.Set(&v)
}

func (o ResourceVersionActivate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceVersionActivate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expected_target_version"] = o.ExpectedTargetVersion
	toSerialize["expected_active_version_id"] = o.ExpectedActiveVersionId.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResourceVersionActivate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expected_target_version",
		"expected_active_version_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceVersionActivate := _ResourceVersionActivate{}

	err = json.Unmarshal(data, &varResourceVersionActivate)

	if err != nil {
		return err
	}

	*o = ResourceVersionActivate(varResourceVersionActivate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "expected_target_version")
		delete(additionalProperties, "expected_active_version_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResourceVersionActivate struct {
	value *ResourceVersionActivate
	isSet bool
}

func (v NullableResourceVersionActivate) Get() *ResourceVersionActivate {
	return v.value
}

func (v *NullableResourceVersionActivate) Set(val *ResourceVersionActivate) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceVersionActivate) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceVersionActivate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceVersionActivate(val *ResourceVersionActivate) *NullableResourceVersionActivate {
	return &NullableResourceVersionActivate{value: val, isSet: true}
}

func (v NullableResourceVersionActivate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceVersionActivate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
