/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// ObservationStateEnum * `healthy` - healthy * `degraded` - degraded * `unavailable` - unavailable
type ObservationStateEnum string

// List of ObservationStateEnum
const (
	OBSERVATIONSTATEENUM_HEALTHY ObservationStateEnum = "healthy"
	OBSERVATIONSTATEENUM_DEGRADED ObservationStateEnum = "degraded"
	OBSERVATIONSTATEENUM_UNAVAILABLE ObservationStateEnum = "unavailable"
	OBSERVATIONSTATEENUM_UNKNOWN_DEFAULT_OPEN_API ObservationStateEnum = "unknown_default_open_api"
)

// All allowed values of ObservationStateEnum enum
var AllowedObservationStateEnumEnumValues = []ObservationStateEnum{
	"healthy",
	"degraded",
	"unavailable",
	"unknown_default_open_api",
}

func (v *ObservationStateEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ObservationStateEnum(value)
	for _, existing := range AllowedObservationStateEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = OBSERVATIONSTATEENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewObservationStateEnumFromValue returns a pointer to a valid ObservationStateEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewObservationStateEnumFromValue(v string) (*ObservationStateEnum, error) {
	ev := ObservationStateEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ObservationStateEnum: valid values are %v", v, AllowedObservationStateEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ObservationStateEnum) IsValid() bool {
	for _, existing := range AllowedObservationStateEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ObservationStateEnum value
func (v ObservationStateEnum) Ptr() *ObservationStateEnum {
	return &v
}

type NullableObservationStateEnum struct {
	value *ObservationStateEnum
	isSet bool
}

func (v NullableObservationStateEnum) Get() *ObservationStateEnum {
	return v.value
}

func (v *NullableObservationStateEnum) Set(val *ObservationStateEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableObservationStateEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableObservationStateEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservationStateEnum(val *ObservationStateEnum) *NullableObservationStateEnum {
	return &NullableObservationStateEnum{value: val, isSet: true}
}

func (v NullableObservationStateEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservationStateEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
