/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourceCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceCreate{}

// ResourceCreate struct for ResourceCreate
type ResourceCreate struct {
	FeeMode *FeePolicyModeInputEnum `json:"fee_mode,omitempty"`
	QuoteCurrency *FeePolicyQuoteCurrencyInputEnum `json:"quote_currency,omitempty"`
	FeeAllowanceCapQuoteMicros *string `json:"fee_allowance_cap_quote_micros,omitempty" validate:"regexp=^(0|[1-9][0-9]*)$"`
	Key string `json:"key" validate:"regexp=^[-a-zA-Z0-9_]+$"`
	Name string `json:"name"`
	Method HTTPMethodEnum `json:"method"`
	Path string `json:"path" validate:"regexp=^/[^\\s?#]*$"`
	Description string `json:"description"`
	MimeType *string `json:"mime_type,omitempty"`
	FulfillmentMode ResourceInputFulfillmentModeEnum `json:"fulfillment_mode"`
	FulfillmentConfig *ResourceCreateFulfillmentConfig `json:"fulfillment_config,omitempty"`
	Prices []PriceInput `json:"prices"`
	AdditionalProperties map[string]interface{}
}

type _ResourceCreate ResourceCreate

// NewResourceCreate instantiates a new ResourceCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceCreate(key string, name string, method HTTPMethodEnum, path string, description string, fulfillmentMode ResourceInputFulfillmentModeEnum, prices []PriceInput) *ResourceCreate {
	this := ResourceCreate{}
	var feeMode FeePolicyModeInputEnum = FEEPOLICYMODEINPUTENUM_BUYER_PAYS
	this.FeeMode = &feeMode
	var quoteCurrency FeePolicyQuoteCurrencyInputEnum = FEEPOLICYQUOTECURRENCYINPUTENUM_USD
	this.QuoteCurrency = &quoteCurrency
	var feeAllowanceCapQuoteMicros string = "0"
	this.FeeAllowanceCapQuoteMicros = &feeAllowanceCapQuoteMicros
	this.Key = key
	this.Name = name
	this.Method = method
	this.Path = path
	this.Description = description
	var mimeType string = "application/json"
	this.MimeType = &mimeType
	this.FulfillmentMode = fulfillmentMode
	this.Prices = prices
	return &this
}

// NewResourceCreateWithDefaults instantiates a new ResourceCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceCreateWithDefaults() *ResourceCreate {
	this := ResourceCreate{}
	var feeMode FeePolicyModeInputEnum = FEEPOLICYMODEINPUTENUM_BUYER_PAYS
	this.FeeMode = &feeMode
	var quoteCurrency FeePolicyQuoteCurrencyInputEnum = FEEPOLICYQUOTECURRENCYINPUTENUM_USD
	this.QuoteCurrency = &quoteCurrency
	var feeAllowanceCapQuoteMicros string = "0"
	this.FeeAllowanceCapQuoteMicros = &feeAllowanceCapQuoteMicros
	var mimeType string = "application/json"
	this.MimeType = &mimeType
	return &this
}

// GetFeeMode returns the FeeMode field value if set, zero value otherwise.
func (o *ResourceCreate) GetFeeMode() FeePolicyModeInputEnum {
	if o == nil || IsNil(o.FeeMode) {
		var ret FeePolicyModeInputEnum
		return ret
	}
	return *o.FeeMode
}

// GetFeeModeOk returns a tuple with the FeeMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetFeeModeOk() (*FeePolicyModeInputEnum, bool) {
	if o == nil || IsNil(o.FeeMode) {
		return nil, false
	}
	return o.FeeMode, true
}

// HasFeeMode returns a boolean if a field has been set.
func (o *ResourceCreate) HasFeeMode() bool {
	if o != nil && !IsNil(o.FeeMode) {
		return true
	}

	return false
}

// SetFeeMode gets a reference to the given FeePolicyModeInputEnum and assigns it to the FeeMode field.
func (o *ResourceCreate) SetFeeMode(v FeePolicyModeInputEnum) {
	o.FeeMode = &v
}

// GetQuoteCurrency returns the QuoteCurrency field value if set, zero value otherwise.
func (o *ResourceCreate) GetQuoteCurrency() FeePolicyQuoteCurrencyInputEnum {
	if o == nil || IsNil(o.QuoteCurrency) {
		var ret FeePolicyQuoteCurrencyInputEnum
		return ret
	}
	return *o.QuoteCurrency
}

// GetQuoteCurrencyOk returns a tuple with the QuoteCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetQuoteCurrencyOk() (*FeePolicyQuoteCurrencyInputEnum, bool) {
	if o == nil || IsNil(o.QuoteCurrency) {
		return nil, false
	}
	return o.QuoteCurrency, true
}

// HasQuoteCurrency returns a boolean if a field has been set.
func (o *ResourceCreate) HasQuoteCurrency() bool {
	if o != nil && !IsNil(o.QuoteCurrency) {
		return true
	}

	return false
}

// SetQuoteCurrency gets a reference to the given FeePolicyQuoteCurrencyInputEnum and assigns it to the QuoteCurrency field.
func (o *ResourceCreate) SetQuoteCurrency(v FeePolicyQuoteCurrencyInputEnum) {
	o.QuoteCurrency = &v
}

// GetFeeAllowanceCapQuoteMicros returns the FeeAllowanceCapQuoteMicros field value if set, zero value otherwise.
func (o *ResourceCreate) GetFeeAllowanceCapQuoteMicros() string {
	if o == nil || IsNil(o.FeeAllowanceCapQuoteMicros) {
		var ret string
		return ret
	}
	return *o.FeeAllowanceCapQuoteMicros
}

// GetFeeAllowanceCapQuoteMicrosOk returns a tuple with the FeeAllowanceCapQuoteMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetFeeAllowanceCapQuoteMicrosOk() (*string, bool) {
	if o == nil || IsNil(o.FeeAllowanceCapQuoteMicros) {
		return nil, false
	}
	return o.FeeAllowanceCapQuoteMicros, true
}

// HasFeeAllowanceCapQuoteMicros returns a boolean if a field has been set.
func (o *ResourceCreate) HasFeeAllowanceCapQuoteMicros() bool {
	if o != nil && !IsNil(o.FeeAllowanceCapQuoteMicros) {
		return true
	}

	return false
}

// SetFeeAllowanceCapQuoteMicros gets a reference to the given string and assigns it to the FeeAllowanceCapQuoteMicros field.
func (o *ResourceCreate) SetFeeAllowanceCapQuoteMicros(v string) {
	o.FeeAllowanceCapQuoteMicros = &v
}

// GetKey returns the Key field value
func (o *ResourceCreate) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ResourceCreate) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *ResourceCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ResourceCreate) SetName(v string) {
	o.Name = v
}

// GetMethod returns the Method field value
func (o *ResourceCreate) GetMethod() HTTPMethodEnum {
	if o == nil {
		var ret HTTPMethodEnum
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetMethodOk() (*HTTPMethodEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *ResourceCreate) SetMethod(v HTTPMethodEnum) {
	o.Method = v
}

// GetPath returns the Path field value
func (o *ResourceCreate) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ResourceCreate) SetPath(v string) {
	o.Path = v
}

// GetDescription returns the Description field value
func (o *ResourceCreate) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ResourceCreate) SetDescription(v string) {
	o.Description = v
}

// GetMimeType returns the MimeType field value if set, zero value otherwise.
func (o *ResourceCreate) GetMimeType() string {
	if o == nil || IsNil(o.MimeType) {
		var ret string
		return ret
	}
	return *o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetMimeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MimeType) {
		return nil, false
	}
	return o.MimeType, true
}

// HasMimeType returns a boolean if a field has been set.
func (o *ResourceCreate) HasMimeType() bool {
	if o != nil && !IsNil(o.MimeType) {
		return true
	}

	return false
}

// SetMimeType gets a reference to the given string and assigns it to the MimeType field.
func (o *ResourceCreate) SetMimeType(v string) {
	o.MimeType = &v
}

// GetFulfillmentMode returns the FulfillmentMode field value
func (o *ResourceCreate) GetFulfillmentMode() ResourceInputFulfillmentModeEnum {
	if o == nil {
		var ret ResourceInputFulfillmentModeEnum
		return ret
	}

	return o.FulfillmentMode
}

// GetFulfillmentModeOk returns a tuple with the FulfillmentMode field value
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetFulfillmentModeOk() (*ResourceInputFulfillmentModeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FulfillmentMode, true
}

// SetFulfillmentMode sets field value
func (o *ResourceCreate) SetFulfillmentMode(v ResourceInputFulfillmentModeEnum) {
	o.FulfillmentMode = v
}

// GetFulfillmentConfig returns the FulfillmentConfig field value if set, zero value otherwise.
func (o *ResourceCreate) GetFulfillmentConfig() ResourceCreateFulfillmentConfig {
	if o == nil || IsNil(o.FulfillmentConfig) {
		var ret ResourceCreateFulfillmentConfig
		return ret
	}
	return *o.FulfillmentConfig
}

// GetFulfillmentConfigOk returns a tuple with the FulfillmentConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetFulfillmentConfigOk() (*ResourceCreateFulfillmentConfig, bool) {
	if o == nil || IsNil(o.FulfillmentConfig) {
		return nil, false
	}
	return o.FulfillmentConfig, true
}

// HasFulfillmentConfig returns a boolean if a field has been set.
func (o *ResourceCreate) HasFulfillmentConfig() bool {
	if o != nil && !IsNil(o.FulfillmentConfig) {
		return true
	}

	return false
}

// SetFulfillmentConfig gets a reference to the given ResourceCreateFulfillmentConfig and assigns it to the FulfillmentConfig field.
func (o *ResourceCreate) SetFulfillmentConfig(v ResourceCreateFulfillmentConfig) {
	o.FulfillmentConfig = &v
}

// GetPrices returns the Prices field value
func (o *ResourceCreate) GetPrices() []PriceInput {
	if o == nil {
		var ret []PriceInput
		return ret
	}

	return o.Prices
}

// GetPricesOk returns a tuple with the Prices field value
// and a boolean to check if the value has been set.
func (o *ResourceCreate) GetPricesOk() ([]PriceInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prices, true
}

// SetPrices sets field value
func (o *ResourceCreate) SetPrices(v []PriceInput) {
	o.Prices = v
}

func (o ResourceCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeeMode) {
		toSerialize["fee_mode"] = o.FeeMode
	}
	if !IsNil(o.QuoteCurrency) {
		toSerialize["quote_currency"] = o.QuoteCurrency
	}
	if !IsNil(o.FeeAllowanceCapQuoteMicros) {
		toSerialize["fee_allowance_cap_quote_micros"] = o.FeeAllowanceCapQuoteMicros
	}
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	toSerialize["method"] = o.Method
	toSerialize["path"] = o.Path
	toSerialize["description"] = o.Description
	if !IsNil(o.MimeType) {
		toSerialize["mime_type"] = o.MimeType
	}
	toSerialize["fulfillment_mode"] = o.FulfillmentMode
	if !IsNil(o.FulfillmentConfig) {
		toSerialize["fulfillment_config"] = o.FulfillmentConfig
	}
	toSerialize["prices"] = o.Prices

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResourceCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"name",
		"method",
		"path",
		"description",
		"fulfillment_mode",
		"prices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceCreate := _ResourceCreate{}

	err = json.Unmarshal(data, &varResourceCreate)

	if err != nil {
		return err
	}

	*o = ResourceCreate(varResourceCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fee_mode")
		delete(additionalProperties, "quote_currency")
		delete(additionalProperties, "fee_allowance_cap_quote_micros")
		delete(additionalProperties, "key")
		delete(additionalProperties, "name")
		delete(additionalProperties, "method")
		delete(additionalProperties, "path")
		delete(additionalProperties, "description")
		delete(additionalProperties, "mime_type")
		delete(additionalProperties, "fulfillment_mode")
		delete(additionalProperties, "fulfillment_config")
		delete(additionalProperties, "prices")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResourceCreate struct {
	value *ResourceCreate
	isSet bool
}

func (v NullableResourceCreate) Get() *ResourceCreate {
	return v.value
}

func (v *NullableResourceCreate) Set(val *ResourceCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceCreate(val *ResourceCreate) *NullableResourceCreate {
	return &NullableResourceCreate{value: val, isSet: true}
}

func (v NullableResourceCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
