/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// ReceiptStatusEnum * `pending_confirmation` - pending_confirmation * `pending_finality` - pending_finality
type ReceiptStatusEnum string

// List of ReceiptStatusEnum
const (
	RECEIPTSTATUSENUM_PENDING_CONFIRMATION ReceiptStatusEnum = "pending_confirmation"
	RECEIPTSTATUSENUM_PENDING_FINALITY ReceiptStatusEnum = "pending_finality"
	RECEIPTSTATUSENUM_UNKNOWN_DEFAULT_OPEN_API ReceiptStatusEnum = "unknown_default_open_api"
)

// All allowed values of ReceiptStatusEnum enum
var AllowedReceiptStatusEnumEnumValues = []ReceiptStatusEnum{
	"pending_confirmation",
	"pending_finality",
	"unknown_default_open_api",
}

func (v *ReceiptStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ReceiptStatusEnum(value)
	for _, existing := range AllowedReceiptStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = RECEIPTSTATUSENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewReceiptStatusEnumFromValue returns a pointer to a valid ReceiptStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewReceiptStatusEnumFromValue(v string) (*ReceiptStatusEnum, error) {
	ev := ReceiptStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ReceiptStatusEnum: valid values are %v", v, AllowedReceiptStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ReceiptStatusEnum) IsValid() bool {
	for _, existing := range AllowedReceiptStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ReceiptStatusEnum value
func (v ReceiptStatusEnum) Ptr() *ReceiptStatusEnum {
	return &v
}

type NullableReceiptStatusEnum struct {
	value *ReceiptStatusEnum
	isSet bool
}

func (v NullableReceiptStatusEnum) Get() *ReceiptStatusEnum {
	return v.value
}

func (v *NullableReceiptStatusEnum) Set(val *ReceiptStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptStatusEnum(val *ReceiptStatusEnum) *NullableReceiptStatusEnum {
	return &NullableReceiptStatusEnum{value: val, isSet: true}
}

func (v NullableReceiptStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
