/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the SettlementChainObservation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettlementChainObservation{}

// SettlementChainObservation struct for SettlementChainObservation
type SettlementChainObservation struct {
	Id string `json:"id"`
	SettlementJobId string `json:"settlement_job_id"`
	Network string `json:"network"`
	TransactionHash string `json:"transaction_hash"`
	State SettlementChainObservationStateEnum `json:"state"`
	ObservationDigest string `json:"observation_digest"`
	LogIndex NullableInt32 `json:"log_index"`
	BlockNumber NullableString `json:"block_number" validate:"regexp=^-?\\d{0\\,78}(?:\\.\\d{0\\,0})?$"`
	BlockHash string `json:"block_hash"`
	AssetContract string `json:"asset_contract"`
	Payer string `json:"payer"`
	Recipient string `json:"recipient"`
	AmountAtomic NullableString `json:"amount_atomic" validate:"regexp=^-?\\d{0\\,78}(?:\\.\\d{0\\,0})?$"`
	ExecutionSuccess NullableBool `json:"execution_success"`
	ObservedAt time.Time `json:"observed_at"`
	CreatedAt time.Time `json:"created_at"`
	AdditionalProperties map[string]interface{}
}

type _SettlementChainObservation SettlementChainObservation

// NewSettlementChainObservation instantiates a new SettlementChainObservation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettlementChainObservation(id string, settlementJobId string, network string, transactionHash string, state SettlementChainObservationStateEnum, observationDigest string, logIndex NullableInt32, blockNumber NullableString, blockHash string, assetContract string, payer string, recipient string, amountAtomic NullableString, executionSuccess NullableBool, observedAt time.Time, createdAt time.Time) *SettlementChainObservation {
	this := SettlementChainObservation{}
	this.Id = id
	this.SettlementJobId = settlementJobId
	this.Network = network
	this.TransactionHash = transactionHash
	this.State = state
	this.ObservationDigest = observationDigest
	this.LogIndex = logIndex
	this.BlockNumber = blockNumber
	this.BlockHash = blockHash
	this.AssetContract = assetContract
	this.Payer = payer
	this.Recipient = recipient
	this.AmountAtomic = amountAtomic
	this.ExecutionSuccess = executionSuccess
	this.ObservedAt = observedAt
	this.CreatedAt = createdAt
	return &this
}

// NewSettlementChainObservationWithDefaults instantiates a new SettlementChainObservation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettlementChainObservationWithDefaults() *SettlementChainObservation {
	this := SettlementChainObservation{}
	return &this
}

// GetId returns the Id field value
func (o *SettlementChainObservation) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SettlementChainObservation) SetId(v string) {
	o.Id = v
}

// GetSettlementJobId returns the SettlementJobId field value
func (o *SettlementChainObservation) GetSettlementJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SettlementJobId
}

// GetSettlementJobIdOk returns a tuple with the SettlementJobId field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetSettlementJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementJobId, true
}

// SetSettlementJobId sets field value
func (o *SettlementChainObservation) SetSettlementJobId(v string) {
	o.SettlementJobId = v
}

// GetNetwork returns the Network field value
func (o *SettlementChainObservation) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *SettlementChainObservation) SetNetwork(v string) {
	o.Network = v
}

// GetTransactionHash returns the TransactionHash field value
func (o *SettlementChainObservation) GetTransactionHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionHash
}

// GetTransactionHashOk returns a tuple with the TransactionHash field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetTransactionHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionHash, true
}

// SetTransactionHash sets field value
func (o *SettlementChainObservation) SetTransactionHash(v string) {
	o.TransactionHash = v
}

// GetState returns the State field value
func (o *SettlementChainObservation) GetState() SettlementChainObservationStateEnum {
	if o == nil {
		var ret SettlementChainObservationStateEnum
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetStateOk() (*SettlementChainObservationStateEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *SettlementChainObservation) SetState(v SettlementChainObservationStateEnum) {
	o.State = v
}

// GetObservationDigest returns the ObservationDigest field value
func (o *SettlementChainObservation) GetObservationDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObservationDigest
}

// GetObservationDigestOk returns a tuple with the ObservationDigest field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetObservationDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservationDigest, true
}

// SetObservationDigest sets field value
func (o *SettlementChainObservation) SetObservationDigest(v string) {
	o.ObservationDigest = v
}

// GetLogIndex returns the LogIndex field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *SettlementChainObservation) GetLogIndex() int32 {
	if o == nil || o.LogIndex.Get() == nil {
		var ret int32
		return ret
	}

	return *o.LogIndex.Get()
}

// GetLogIndexOk returns a tuple with the LogIndex field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettlementChainObservation) GetLogIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogIndex.Get(), o.LogIndex.IsSet()
}

// SetLogIndex sets field value
func (o *SettlementChainObservation) SetLogIndex(v int32) {
	o.LogIndex.Set(&v)
}

// GetBlockNumber returns the BlockNumber field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SettlementChainObservation) GetBlockNumber() string {
	if o == nil || o.BlockNumber.Get() == nil {
		var ret string
		return ret
	}

	return *o.BlockNumber.Get()
}

// GetBlockNumberOk returns a tuple with the BlockNumber field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettlementChainObservation) GetBlockNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockNumber.Get(), o.BlockNumber.IsSet()
}

// SetBlockNumber sets field value
func (o *SettlementChainObservation) SetBlockNumber(v string) {
	o.BlockNumber.Set(&v)
}

// GetBlockHash returns the BlockHash field value
func (o *SettlementChainObservation) GetBlockHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlockHash
}

// GetBlockHashOk returns a tuple with the BlockHash field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetBlockHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockHash, true
}

// SetBlockHash sets field value
func (o *SettlementChainObservation) SetBlockHash(v string) {
	o.BlockHash = v
}

// GetAssetContract returns the AssetContract field value
func (o *SettlementChainObservation) GetAssetContract() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetContract
}

// GetAssetContractOk returns a tuple with the AssetContract field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetAssetContractOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetContract, true
}

// SetAssetContract sets field value
func (o *SettlementChainObservation) SetAssetContract(v string) {
	o.AssetContract = v
}

// GetPayer returns the Payer field value
func (o *SettlementChainObservation) GetPayer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Payer
}

// GetPayerOk returns a tuple with the Payer field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetPayerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payer, true
}

// SetPayer sets field value
func (o *SettlementChainObservation) SetPayer(v string) {
	o.Payer = v
}

// GetRecipient returns the Recipient field value
func (o *SettlementChainObservation) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *SettlementChainObservation) SetRecipient(v string) {
	o.Recipient = v
}

// GetAmountAtomic returns the AmountAtomic field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SettlementChainObservation) GetAmountAtomic() string {
	if o == nil || o.AmountAtomic.Get() == nil {
		var ret string
		return ret
	}

	return *o.AmountAtomic.Get()
}

// GetAmountAtomicOk returns a tuple with the AmountAtomic field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettlementChainObservation) GetAmountAtomicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AmountAtomic.Get(), o.AmountAtomic.IsSet()
}

// SetAmountAtomic sets field value
func (o *SettlementChainObservation) SetAmountAtomic(v string) {
	o.AmountAtomic.Set(&v)
}

// GetExecutionSuccess returns the ExecutionSuccess field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *SettlementChainObservation) GetExecutionSuccess() bool {
	if o == nil || o.ExecutionSuccess.Get() == nil {
		var ret bool
		return ret
	}

	return *o.ExecutionSuccess.Get()
}

// GetExecutionSuccessOk returns a tuple with the ExecutionSuccess field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettlementChainObservation) GetExecutionSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExecutionSuccess.Get(), o.ExecutionSuccess.IsSet()
}

// SetExecutionSuccess sets field value
func (o *SettlementChainObservation) SetExecutionSuccess(v bool) {
	o.ExecutionSuccess.Set(&v)
}

// GetObservedAt returns the ObservedAt field value
func (o *SettlementChainObservation) GetObservedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ObservedAt
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedAt, true
}

// SetObservedAt sets field value
func (o *SettlementChainObservation) SetObservedAt(v time.Time) {
	o.ObservedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SettlementChainObservation) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SettlementChainObservation) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SettlementChainObservation) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o SettlementChainObservation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettlementChainObservation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["settlement_job_id"] = o.SettlementJobId
	toSerialize["network"] = o.Network
	toSerialize["transaction_hash"] = o.TransactionHash
	toSerialize["state"] = o.State
	toSerialize["observation_digest"] = o.ObservationDigest
	toSerialize["log_index"] = o.LogIndex.Get()
	toSerialize["block_number"] = o.BlockNumber.Get()
	toSerialize["block_hash"] = o.BlockHash
	toSerialize["asset_contract"] = o.AssetContract
	toSerialize["payer"] = o.Payer
	toSerialize["recipient"] = o.Recipient
	toSerialize["amount_atomic"] = o.AmountAtomic.Get()
	toSerialize["execution_success"] = o.ExecutionSuccess.Get()
	toSerialize["observed_at"] = o.ObservedAt
	toSerialize["created_at"] = o.CreatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SettlementChainObservation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"settlement_job_id",
		"network",
		"transaction_hash",
		"state",
		"observation_digest",
		"log_index",
		"block_number",
		"block_hash",
		"asset_contract",
		"payer",
		"recipient",
		"amount_atomic",
		"execution_success",
		"observed_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettlementChainObservation := _SettlementChainObservation{}

	err = json.Unmarshal(data, &varSettlementChainObservation)

	if err != nil {
		return err
	}

	*o = SettlementChainObservation(varSettlementChainObservation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "settlement_job_id")
		delete(additionalProperties, "network")
		delete(additionalProperties, "transaction_hash")
		delete(additionalProperties, "state")
		delete(additionalProperties, "observation_digest")
		delete(additionalProperties, "log_index")
		delete(additionalProperties, "block_number")
		delete(additionalProperties, "block_hash")
		delete(additionalProperties, "asset_contract")
		delete(additionalProperties, "payer")
		delete(additionalProperties, "recipient")
		delete(additionalProperties, "amount_atomic")
		delete(additionalProperties, "execution_success")
		delete(additionalProperties, "observed_at")
		delete(additionalProperties, "created_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSettlementChainObservation struct {
	value *SettlementChainObservation
	isSet bool
}

func (v NullableSettlementChainObservation) Get() *SettlementChainObservation {
	return v.value
}

func (v *NullableSettlementChainObservation) Set(val *SettlementChainObservation) {
	v.value = val
	v.isSet = true
}

func (v NullableSettlementChainObservation) IsSet() bool {
	return v.isSet
}

func (v *NullableSettlementChainObservation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettlementChainObservation(val *SettlementChainObservation) *NullableSettlementChainObservation {
	return &NullableSettlementChainObservation{value: val, isSet: true}
}

func (v NullableSettlementChainObservation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettlementChainObservation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
