/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the NativeFeeObservationEvidence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NativeFeeObservationEvidence{}

// NativeFeeObservationEvidence struct for NativeFeeObservationEvidence
type NativeFeeObservationEvidence struct {
	Source string `json:"source"`
	NativeFeeAtomic string `json:"nativeFeeAtomic" validate:"regexp=^(0|[1-9][0-9]*)$"`
	ObservedAt time.Time `json:"observedAt"`
	AdditionalProperties map[string]interface{}
}

type _NativeFeeObservationEvidence NativeFeeObservationEvidence

// NewNativeFeeObservationEvidence instantiates a new NativeFeeObservationEvidence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNativeFeeObservationEvidence(source string, nativeFeeAtomic string, observedAt time.Time) *NativeFeeObservationEvidence {
	this := NativeFeeObservationEvidence{}
	this.Source = source
	this.NativeFeeAtomic = nativeFeeAtomic
	this.ObservedAt = observedAt
	return &this
}

// NewNativeFeeObservationEvidenceWithDefaults instantiates a new NativeFeeObservationEvidence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNativeFeeObservationEvidenceWithDefaults() *NativeFeeObservationEvidence {
	this := NativeFeeObservationEvidence{}
	return &this
}

// GetSource returns the Source field value
func (o *NativeFeeObservationEvidence) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *NativeFeeObservationEvidence) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *NativeFeeObservationEvidence) SetSource(v string) {
	o.Source = v
}

// GetNativeFeeAtomic returns the NativeFeeAtomic field value
func (o *NativeFeeObservationEvidence) GetNativeFeeAtomic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NativeFeeAtomic
}

// GetNativeFeeAtomicOk returns a tuple with the NativeFeeAtomic field value
// and a boolean to check if the value has been set.
func (o *NativeFeeObservationEvidence) GetNativeFeeAtomicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NativeFeeAtomic, true
}

// SetNativeFeeAtomic sets field value
func (o *NativeFeeObservationEvidence) SetNativeFeeAtomic(v string) {
	o.NativeFeeAtomic = v
}

// GetObservedAt returns the ObservedAt field value
func (o *NativeFeeObservationEvidence) GetObservedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ObservedAt
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
func (o *NativeFeeObservationEvidence) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedAt, true
}

// SetObservedAt sets field value
func (o *NativeFeeObservationEvidence) SetObservedAt(v time.Time) {
	o.ObservedAt = v
}

func (o NativeFeeObservationEvidence) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NativeFeeObservationEvidence) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["nativeFeeAtomic"] = o.NativeFeeAtomic
	toSerialize["observedAt"] = o.ObservedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NativeFeeObservationEvidence) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"nativeFeeAtomic",
		"observedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNativeFeeObservationEvidence := _NativeFeeObservationEvidence{}

	err = json.Unmarshal(data, &varNativeFeeObservationEvidence)

	if err != nil {
		return err
	}

	*o = NativeFeeObservationEvidence(varNativeFeeObservationEvidence)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source")
		delete(additionalProperties, "nativeFeeAtomic")
		delete(additionalProperties, "observedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNativeFeeObservationEvidence struct {
	value *NativeFeeObservationEvidence
	isSet bool
}

func (v NullableNativeFeeObservationEvidence) Get() *NativeFeeObservationEvidence {
	return v.value
}

func (v *NullableNativeFeeObservationEvidence) Set(val *NativeFeeObservationEvidence) {
	v.value = val
	v.isSet = true
}

func (v NullableNativeFeeObservationEvidence) IsSet() bool {
	return v.isSet
}

func (v *NullableNativeFeeObservationEvidence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNativeFeeObservationEvidence(val *NativeFeeObservationEvidence) *NullableNativeFeeObservationEvidence {
	return &NullableNativeFeeObservationEvidence{value: val, isSet: true}
}

func (v NullableNativeFeeObservationEvidence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNativeFeeObservationEvidence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
