/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the ReceiptVerificationKeyHistory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReceiptVerificationKeyHistory{}

// ReceiptVerificationKeyHistory struct for ReceiptVerificationKeyHistory
type ReceiptVerificationKeyHistory struct {
	Type string `json:"type"`
	Keys map[string]ReceiptVerificationKey `json:"keys"`
	AdditionalProperties map[string]interface{}
}

type _ReceiptVerificationKeyHistory ReceiptVerificationKeyHistory

// NewReceiptVerificationKeyHistory instantiates a new ReceiptVerificationKeyHistory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceiptVerificationKeyHistory(type_ string, keys map[string]ReceiptVerificationKey) *ReceiptVerificationKeyHistory {
	this := ReceiptVerificationKeyHistory{}
	this.Type = type_
	this.Keys = keys
	return &this
}

// NewReceiptVerificationKeyHistoryWithDefaults instantiates a new ReceiptVerificationKeyHistory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptVerificationKeyHistoryWithDefaults() *ReceiptVerificationKeyHistory {
	this := ReceiptVerificationKeyHistory{}
	return &this
}

// GetType returns the Type field value
func (o *ReceiptVerificationKeyHistory) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ReceiptVerificationKeyHistory) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ReceiptVerificationKeyHistory) SetType(v string) {
	o.Type = v
}

// GetKeys returns the Keys field value
func (o *ReceiptVerificationKeyHistory) GetKeys() map[string]ReceiptVerificationKey {
	if o == nil {
		var ret map[string]ReceiptVerificationKey
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *ReceiptVerificationKeyHistory) GetKeysOk() (*map[string]ReceiptVerificationKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Keys, true
}

// SetKeys sets field value
func (o *ReceiptVerificationKeyHistory) SetKeys(v map[string]ReceiptVerificationKey) {
	o.Keys = v
}

func (o ReceiptVerificationKeyHistory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReceiptVerificationKeyHistory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["keys"] = o.Keys

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReceiptVerificationKeyHistory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceiptVerificationKeyHistory := _ReceiptVerificationKeyHistory{}

	err = json.Unmarshal(data, &varReceiptVerificationKeyHistory)

	if err != nil {
		return err
	}

	*o = ReceiptVerificationKeyHistory(varReceiptVerificationKeyHistory)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "keys")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReceiptVerificationKeyHistory struct {
	value *ReceiptVerificationKeyHistory
	isSet bool
}

func (v NullableReceiptVerificationKeyHistory) Get() *ReceiptVerificationKeyHistory {
	return v.value
}

func (v *NullableReceiptVerificationKeyHistory) Set(val *ReceiptVerificationKeyHistory) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptVerificationKeyHistory) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptVerificationKeyHistory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptVerificationKeyHistory(val *ReceiptVerificationKeyHistory) *NullableReceiptVerificationKeyHistory {
	return &NullableReceiptVerificationKeyHistory{value: val, isSet: true}
}

func (v NullableReceiptVerificationKeyHistory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptVerificationKeyHistory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
