/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the PaymentReadiness type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentReadiness{}

// PaymentReadiness struct for PaymentReadiness
type PaymentReadiness struct {
	ObservedAt time.Time `json:"observed_at"`
	TenantStatus string `json:"tenant_status"`
	TenantAcceptingNewChallenges bool `json:"tenant_accepting_new_challenges"`
	GlobalChallengesEnabled bool `json:"global_challenges_enabled"`
	GlobalSettlementEnabled bool `json:"global_settlement_enabled"`
	ControlPlaneReadyForNewChallenges bool `json:"control_plane_ready_for_new_challenges"`
	ControlPlaneReadyForSettlement bool `json:"control_plane_ready_for_settlement"`
	ExternalOnboarding interface{} `json:"external_onboarding"`
	Rails []PaymentReadinessRail `json:"rails"`
	AdditionalProperties map[string]interface{}
}

type _PaymentReadiness PaymentReadiness

// NewPaymentReadiness instantiates a new PaymentReadiness object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentReadiness(observedAt time.Time, tenantStatus string, tenantAcceptingNewChallenges bool, globalChallengesEnabled bool, globalSettlementEnabled bool, controlPlaneReadyForNewChallenges bool, controlPlaneReadyForSettlement bool, externalOnboarding interface{}, rails []PaymentReadinessRail) *PaymentReadiness {
	this := PaymentReadiness{}
	this.ObservedAt = observedAt
	this.TenantStatus = tenantStatus
	this.TenantAcceptingNewChallenges = tenantAcceptingNewChallenges
	this.GlobalChallengesEnabled = globalChallengesEnabled
	this.GlobalSettlementEnabled = globalSettlementEnabled
	this.ControlPlaneReadyForNewChallenges = controlPlaneReadyForNewChallenges
	this.ControlPlaneReadyForSettlement = controlPlaneReadyForSettlement
	this.ExternalOnboarding = externalOnboarding
	this.Rails = rails
	return &this
}

// NewPaymentReadinessWithDefaults instantiates a new PaymentReadiness object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentReadinessWithDefaults() *PaymentReadiness {
	this := PaymentReadiness{}
	return &this
}

// GetObservedAt returns the ObservedAt field value
func (o *PaymentReadiness) GetObservedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ObservedAt
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
func (o *PaymentReadiness) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedAt, true
}

// SetObservedAt sets field value
func (o *PaymentReadiness) SetObservedAt(v time.Time) {
	o.ObservedAt = v
}

// GetTenantStatus returns the TenantStatus field value
func (o *PaymentReadiness) GetTenantStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantStatus
}

// GetTenantStatusOk returns a tuple with the TenantStatus field value
// and a boolean to check if the value has been set.
func (o *PaymentReadiness) GetTenantStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantStatus, true
}

// SetTenantStatus sets field value
func (o *PaymentReadiness) SetTenantStatus(v string) {
	o.TenantStatus = v
}

// GetTenantAcceptingNewChallenges returns the TenantAcceptingNewChallenges field value
func (o *PaymentReadiness) GetTenantAcceptingNewChallenges() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TenantAcceptingNewChallenges
}

// GetTenantAcceptingNewChallengesOk returns a tuple with the TenantAcceptingNewChallenges field value
// and a boolean to check if the value has been set.
func (o *PaymentReadiness) GetTenantAcceptingNewChallengesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantAcceptingNewChallenges, true
}

// SetTenantAcceptingNewChallenges sets field value
func (o *PaymentReadiness) SetTenantAcceptingNewChallenges(v bool) {
	o.TenantAcceptingNewChallenges = v
}

// GetGlobalChallengesEnabled returns the GlobalChallengesEnabled field value
func (o *PaymentReadiness) GetGlobalChallengesEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.GlobalChallengesEnabled
}

// GetGlobalChallengesEnabledOk returns a tuple with the GlobalChallengesEnabled field value
// and a boolean to check if the value has been set.
func (o *PaymentReadiness) GetGlobalChallengesEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GlobalChallengesEnabled, true
}

// SetGlobalChallengesEnabled sets field value
func (o *PaymentReadiness) SetGlobalChallengesEnabled(v bool) {
	o.GlobalChallengesEnabled = v
}

// GetGlobalSettlementEnabled returns the GlobalSettlementEnabled field value
func (o *PaymentReadiness) GetGlobalSettlementEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.GlobalSettlementEnabled
}

// GetGlobalSettlementEnabledOk returns a tuple with the GlobalSettlementEnabled field value
// and a boolean to check if the value has been set.
func (o *PaymentReadiness) GetGlobalSettlementEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GlobalSettlementEnabled, true
}

// SetGlobalSettlementEnabled sets field value
func (o *PaymentReadiness) SetGlobalSettlementEnabled(v bool) {
	o.GlobalSettlementEnabled = v
}

// GetControlPlaneReadyForNewChallenges returns the ControlPlaneReadyForNewChallenges field value
func (o *PaymentReadiness) GetControlPlaneReadyForNewChallenges() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ControlPlaneReadyForNewChallenges
}

// GetControlPlaneReadyForNewChallengesOk returns a tuple with the ControlPlaneReadyForNewChallenges field value
// and a boolean to check if the value has been set.
func (o *PaymentReadiness) GetControlPlaneReadyForNewChallengesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ControlPlaneReadyForNewChallenges, true
}

// SetControlPlaneReadyForNewChallenges sets field value
func (o *PaymentReadiness) SetControlPlaneReadyForNewChallenges(v bool) {
	o.ControlPlaneReadyForNewChallenges = v
}

// GetControlPlaneReadyForSettlement returns the ControlPlaneReadyForSettlement field value
func (o *PaymentReadiness) GetControlPlaneReadyForSettlement() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ControlPlaneReadyForSettlement
}

// GetControlPlaneReadyForSettlementOk returns a tuple with the ControlPlaneReadyForSettlement field value
// and a boolean to check if the value has been set.
func (o *PaymentReadiness) GetControlPlaneReadyForSettlementOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ControlPlaneReadyForSettlement, true
}

// SetControlPlaneReadyForSettlement sets field value
func (o *PaymentReadiness) SetControlPlaneReadyForSettlement(v bool) {
	o.ControlPlaneReadyForSettlement = v
}

// GetExternalOnboarding returns the ExternalOnboarding field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PaymentReadiness) GetExternalOnboarding() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ExternalOnboarding
}

// GetExternalOnboardingOk returns a tuple with the ExternalOnboarding field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentReadiness) GetExternalOnboardingOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ExternalOnboarding) {
		return nil, false
	}
	return &o.ExternalOnboarding, true
}

// SetExternalOnboarding sets field value
func (o *PaymentReadiness) SetExternalOnboarding(v interface{}) {
	o.ExternalOnboarding = v
}

// GetRails returns the Rails field value
func (o *PaymentReadiness) GetRails() []PaymentReadinessRail {
	if o == nil {
		var ret []PaymentReadinessRail
		return ret
	}

	return o.Rails
}

// GetRailsOk returns a tuple with the Rails field value
// and a boolean to check if the value has been set.
func (o *PaymentReadiness) GetRailsOk() ([]PaymentReadinessRail, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rails, true
}

// SetRails sets field value
func (o *PaymentReadiness) SetRails(v []PaymentReadinessRail) {
	o.Rails = v
}

func (o PaymentReadiness) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentReadiness) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["observed_at"] = o.ObservedAt
	toSerialize["tenant_status"] = o.TenantStatus
	toSerialize["tenant_accepting_new_challenges"] = o.TenantAcceptingNewChallenges
	toSerialize["global_challenges_enabled"] = o.GlobalChallengesEnabled
	toSerialize["global_settlement_enabled"] = o.GlobalSettlementEnabled
	toSerialize["control_plane_ready_for_new_challenges"] = o.ControlPlaneReadyForNewChallenges
	toSerialize["control_plane_ready_for_settlement"] = o.ControlPlaneReadyForSettlement
	if o.ExternalOnboarding != nil {
		toSerialize["external_onboarding"] = o.ExternalOnboarding
	}
	toSerialize["rails"] = o.Rails

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentReadiness) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"observed_at",
		"tenant_status",
		"tenant_accepting_new_challenges",
		"global_challenges_enabled",
		"global_settlement_enabled",
		"control_plane_ready_for_new_challenges",
		"control_plane_ready_for_settlement",
		"external_onboarding",
		"rails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentReadiness := _PaymentReadiness{}

	err = json.Unmarshal(data, &varPaymentReadiness)

	if err != nil {
		return err
	}

	*o = PaymentReadiness(varPaymentReadiness)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "observed_at")
		delete(additionalProperties, "tenant_status")
		delete(additionalProperties, "tenant_accepting_new_challenges")
		delete(additionalProperties, "global_challenges_enabled")
		delete(additionalProperties, "global_settlement_enabled")
		delete(additionalProperties, "control_plane_ready_for_new_challenges")
		delete(additionalProperties, "control_plane_ready_for_settlement")
		delete(additionalProperties, "external_onboarding")
		delete(additionalProperties, "rails")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaymentReadiness struct {
	value *PaymentReadiness
	isSet bool
}

func (v NullablePaymentReadiness) Get() *PaymentReadiness {
	return v.value
}

func (v *NullablePaymentReadiness) Set(val *PaymentReadiness) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentReadiness) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentReadiness) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentReadiness(val *PaymentReadiness) *NullablePaymentReadiness {
	return &NullablePaymentReadiness{value: val, isSet: true}
}

func (v NullablePaymentReadiness) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentReadiness) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
