/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the TenantPaymentChainProjection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantPaymentChainProjection{}

// TenantPaymentChainProjection struct for TenantPaymentChainProjection
type TenantPaymentChainProjection struct {
	State string `json:"state"`
	TransactionHash string `json:"transaction_hash"`
	BlockNumber NullableString `json:"block_number"`
	BlockHash string `json:"block_hash"`
	Confirmations int32 `json:"confirmations"`
	ConfirmationsRequired int32 `json:"confirmations_required"`
	ObservedAt NullableTime `json:"observed_at"`
	AdditionalProperties map[string]interface{}
}

type _TenantPaymentChainProjection TenantPaymentChainProjection

// NewTenantPaymentChainProjection instantiates a new TenantPaymentChainProjection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantPaymentChainProjection(state string, transactionHash string, blockNumber NullableString, blockHash string, confirmations int32, confirmationsRequired int32, observedAt NullableTime) *TenantPaymentChainProjection {
	this := TenantPaymentChainProjection{}
	this.State = state
	this.TransactionHash = transactionHash
	this.BlockNumber = blockNumber
	this.BlockHash = blockHash
	this.Confirmations = confirmations
	this.ConfirmationsRequired = confirmationsRequired
	this.ObservedAt = observedAt
	return &this
}

// NewTenantPaymentChainProjectionWithDefaults instantiates a new TenantPaymentChainProjection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantPaymentChainProjectionWithDefaults() *TenantPaymentChainProjection {
	this := TenantPaymentChainProjection{}
	return &this
}

// GetState returns the State field value
func (o *TenantPaymentChainProjection) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentChainProjection) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *TenantPaymentChainProjection) SetState(v string) {
	o.State = v
}

// GetTransactionHash returns the TransactionHash field value
func (o *TenantPaymentChainProjection) GetTransactionHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionHash
}

// GetTransactionHashOk returns a tuple with the TransactionHash field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentChainProjection) GetTransactionHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionHash, true
}

// SetTransactionHash sets field value
func (o *TenantPaymentChainProjection) SetTransactionHash(v string) {
	o.TransactionHash = v
}

// GetBlockNumber returns the BlockNumber field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TenantPaymentChainProjection) GetBlockNumber() string {
	if o == nil || o.BlockNumber.Get() == nil {
		var ret string
		return ret
	}

	return *o.BlockNumber.Get()
}

// GetBlockNumberOk returns a tuple with the BlockNumber field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantPaymentChainProjection) GetBlockNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockNumber.Get(), o.BlockNumber.IsSet()
}

// SetBlockNumber sets field value
func (o *TenantPaymentChainProjection) SetBlockNumber(v string) {
	o.BlockNumber.Set(&v)
}

// GetBlockHash returns the BlockHash field value
func (o *TenantPaymentChainProjection) GetBlockHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlockHash
}

// GetBlockHashOk returns a tuple with the BlockHash field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentChainProjection) GetBlockHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockHash, true
}

// SetBlockHash sets field value
func (o *TenantPaymentChainProjection) SetBlockHash(v string) {
	o.BlockHash = v
}

// GetConfirmations returns the Confirmations field value
func (o *TenantPaymentChainProjection) GetConfirmations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Confirmations
}

// GetConfirmationsOk returns a tuple with the Confirmations field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentChainProjection) GetConfirmationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confirmations, true
}

// SetConfirmations sets field value
func (o *TenantPaymentChainProjection) SetConfirmations(v int32) {
	o.Confirmations = v
}

// GetConfirmationsRequired returns the ConfirmationsRequired field value
func (o *TenantPaymentChainProjection) GetConfirmationsRequired() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ConfirmationsRequired
}

// GetConfirmationsRequiredOk returns a tuple with the ConfirmationsRequired field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentChainProjection) GetConfirmationsRequiredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfirmationsRequired, true
}

// SetConfirmationsRequired sets field value
func (o *TenantPaymentChainProjection) SetConfirmationsRequired(v int32) {
	o.ConfirmationsRequired = v
}

// GetObservedAt returns the ObservedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TenantPaymentChainProjection) GetObservedAt() time.Time {
	if o == nil || o.ObservedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ObservedAt.Get()
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantPaymentChainProjection) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ObservedAt.Get(), o.ObservedAt.IsSet()
}

// SetObservedAt sets field value
func (o *TenantPaymentChainProjection) SetObservedAt(v time.Time) {
	o.ObservedAt.Set(&v)
}

func (o TenantPaymentChainProjection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantPaymentChainProjection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["transaction_hash"] = o.TransactionHash
	toSerialize["block_number"] = o.BlockNumber.Get()
	toSerialize["block_hash"] = o.BlockHash
	toSerialize["confirmations"] = o.Confirmations
	toSerialize["confirmations_required"] = o.ConfirmationsRequired
	toSerialize["observed_at"] = o.ObservedAt.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TenantPaymentChainProjection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"transaction_hash",
		"block_number",
		"block_hash",
		"confirmations",
		"confirmations_required",
		"observed_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantPaymentChainProjection := _TenantPaymentChainProjection{}

	err = json.Unmarshal(data, &varTenantPaymentChainProjection)

	if err != nil {
		return err
	}

	*o = TenantPaymentChainProjection(varTenantPaymentChainProjection)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "state")
		delete(additionalProperties, "transaction_hash")
		delete(additionalProperties, "block_number")
		delete(additionalProperties, "block_hash")
		delete(additionalProperties, "confirmations")
		delete(additionalProperties, "confirmations_required")
		delete(additionalProperties, "observed_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTenantPaymentChainProjection struct {
	value *TenantPaymentChainProjection
	isSet bool
}

func (v NullableTenantPaymentChainProjection) Get() *TenantPaymentChainProjection {
	return v.value
}

func (v *NullableTenantPaymentChainProjection) Set(val *TenantPaymentChainProjection) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantPaymentChainProjection) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantPaymentChainProjection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantPaymentChainProjection(val *TenantPaymentChainProjection) *NullableTenantPaymentChainProjection {
	return &NullableTenantPaymentChainProjection{value: val, isSet: true}
}

func (v NullableTenantPaymentChainProjection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantPaymentChainProjection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
