/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// TenantPaymentReceiptProjectionStatusEnum * `not_issued` - not_issued * `issued` - issued * `integrity_failure` - integrity_failure
type TenantPaymentReceiptProjectionStatusEnum string

// List of TenantPaymentReceiptProjectionStatusEnum
const (
	TENANTPAYMENTRECEIPTPROJECTIONSTATUSENUM_NOT_ISSUED TenantPaymentReceiptProjectionStatusEnum = "not_issued"
	TENANTPAYMENTRECEIPTPROJECTIONSTATUSENUM_ISSUED TenantPaymentReceiptProjectionStatusEnum = "issued"
	TENANTPAYMENTRECEIPTPROJECTIONSTATUSENUM_INTEGRITY_FAILURE TenantPaymentReceiptProjectionStatusEnum = "integrity_failure"
	TENANTPAYMENTRECEIPTPROJECTIONSTATUSENUM_UNKNOWN_DEFAULT_OPEN_API TenantPaymentReceiptProjectionStatusEnum = "unknown_default_open_api"
)

// All allowed values of TenantPaymentReceiptProjectionStatusEnum enum
var AllowedTenantPaymentReceiptProjectionStatusEnumEnumValues = []TenantPaymentReceiptProjectionStatusEnum{
	"not_issued",
	"issued",
	"integrity_failure",
	"unknown_default_open_api",
}

func (v *TenantPaymentReceiptProjectionStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TenantPaymentReceiptProjectionStatusEnum(value)
	for _, existing := range AllowedTenantPaymentReceiptProjectionStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = TENANTPAYMENTRECEIPTPROJECTIONSTATUSENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewTenantPaymentReceiptProjectionStatusEnumFromValue returns a pointer to a valid TenantPaymentReceiptProjectionStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTenantPaymentReceiptProjectionStatusEnumFromValue(v string) (*TenantPaymentReceiptProjectionStatusEnum, error) {
	ev := TenantPaymentReceiptProjectionStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TenantPaymentReceiptProjectionStatusEnum: valid values are %v", v, AllowedTenantPaymentReceiptProjectionStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TenantPaymentReceiptProjectionStatusEnum) IsValid() bool {
	for _, existing := range AllowedTenantPaymentReceiptProjectionStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TenantPaymentReceiptProjectionStatusEnum value
func (v TenantPaymentReceiptProjectionStatusEnum) Ptr() *TenantPaymentReceiptProjectionStatusEnum {
	return &v
}

type NullableTenantPaymentReceiptProjectionStatusEnum struct {
	value *TenantPaymentReceiptProjectionStatusEnum
	isSet bool
}

func (v NullableTenantPaymentReceiptProjectionStatusEnum) Get() *TenantPaymentReceiptProjectionStatusEnum {
	return v.value
}

func (v *NullableTenantPaymentReceiptProjectionStatusEnum) Set(val *TenantPaymentReceiptProjectionStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantPaymentReceiptProjectionStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantPaymentReceiptProjectionStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantPaymentReceiptProjectionStatusEnum(val *TenantPaymentReceiptProjectionStatusEnum) *NullableTenantPaymentReceiptProjectionStatusEnum {
	return &NullableTenantPaymentReceiptProjectionStatusEnum{value: val, isSet: true}
}

func (v NullableTenantPaymentReceiptProjectionStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantPaymentReceiptProjectionStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
