/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// TenantPaymentFulfillmentProjectionStatusEnum * `not_created` - not_created * `created` - created
type TenantPaymentFulfillmentProjectionStatusEnum string

// List of TenantPaymentFulfillmentProjectionStatusEnum
const (
	TENANTPAYMENTFULFILLMENTPROJECTIONSTATUSENUM_NOT_CREATED TenantPaymentFulfillmentProjectionStatusEnum = "not_created"
	TENANTPAYMENTFULFILLMENTPROJECTIONSTATUSENUM_CREATED TenantPaymentFulfillmentProjectionStatusEnum = "created"
	TENANTPAYMENTFULFILLMENTPROJECTIONSTATUSENUM_UNKNOWN_DEFAULT_OPEN_API TenantPaymentFulfillmentProjectionStatusEnum = "unknown_default_open_api"
)

// All allowed values of TenantPaymentFulfillmentProjectionStatusEnum enum
var AllowedTenantPaymentFulfillmentProjectionStatusEnumEnumValues = []TenantPaymentFulfillmentProjectionStatusEnum{
	"not_created",
	"created",
	"unknown_default_open_api",
}

func (v *TenantPaymentFulfillmentProjectionStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TenantPaymentFulfillmentProjectionStatusEnum(value)
	for _, existing := range AllowedTenantPaymentFulfillmentProjectionStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = TENANTPAYMENTFULFILLMENTPROJECTIONSTATUSENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewTenantPaymentFulfillmentProjectionStatusEnumFromValue returns a pointer to a valid TenantPaymentFulfillmentProjectionStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTenantPaymentFulfillmentProjectionStatusEnumFromValue(v string) (*TenantPaymentFulfillmentProjectionStatusEnum, error) {
	ev := TenantPaymentFulfillmentProjectionStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TenantPaymentFulfillmentProjectionStatusEnum: valid values are %v", v, AllowedTenantPaymentFulfillmentProjectionStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TenantPaymentFulfillmentProjectionStatusEnum) IsValid() bool {
	for _, existing := range AllowedTenantPaymentFulfillmentProjectionStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TenantPaymentFulfillmentProjectionStatusEnum value
func (v TenantPaymentFulfillmentProjectionStatusEnum) Ptr() *TenantPaymentFulfillmentProjectionStatusEnum {
	return &v
}

type NullableTenantPaymentFulfillmentProjectionStatusEnum struct {
	value *TenantPaymentFulfillmentProjectionStatusEnum
	isSet bool
}

func (v NullableTenantPaymentFulfillmentProjectionStatusEnum) Get() *TenantPaymentFulfillmentProjectionStatusEnum {
	return v.value
}

func (v *NullableTenantPaymentFulfillmentProjectionStatusEnum) Set(val *TenantPaymentFulfillmentProjectionStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantPaymentFulfillmentProjectionStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantPaymentFulfillmentProjectionStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantPaymentFulfillmentProjectionStatusEnum(val *TenantPaymentFulfillmentProjectionStatusEnum) *NullableTenantPaymentFulfillmentProjectionStatusEnum {
	return &NullableTenantPaymentFulfillmentProjectionStatusEnum{value: val, isSet: true}
}

func (v NullableTenantPaymentFulfillmentProjectionStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantPaymentFulfillmentProjectionStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
