/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// WalletVersionStateEnum * `pending` - pending * `active` - active * `draining` - draining * `revoked` - revoked
type WalletVersionStateEnum string

// List of WalletVersionStateEnum
const (
	WALLETVERSIONSTATEENUM_PENDING WalletVersionStateEnum = "pending"
	WALLETVERSIONSTATEENUM_ACTIVE WalletVersionStateEnum = "active"
	WALLETVERSIONSTATEENUM_DRAINING WalletVersionStateEnum = "draining"
	WALLETVERSIONSTATEENUM_REVOKED WalletVersionStateEnum = "revoked"
	WALLETVERSIONSTATEENUM_UNKNOWN_DEFAULT_OPEN_API WalletVersionStateEnum = "unknown_default_open_api"
)

// All allowed values of WalletVersionStateEnum enum
var AllowedWalletVersionStateEnumEnumValues = []WalletVersionStateEnum{
	"pending",
	"active",
	"draining",
	"revoked",
	"unknown_default_open_api",
}

func (v *WalletVersionStateEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WalletVersionStateEnum(value)
	for _, existing := range AllowedWalletVersionStateEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = WALLETVERSIONSTATEENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewWalletVersionStateEnumFromValue returns a pointer to a valid WalletVersionStateEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWalletVersionStateEnumFromValue(v string) (*WalletVersionStateEnum, error) {
	ev := WalletVersionStateEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WalletVersionStateEnum: valid values are %v", v, AllowedWalletVersionStateEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WalletVersionStateEnum) IsValid() bool {
	for _, existing := range AllowedWalletVersionStateEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WalletVersionStateEnum value
func (v WalletVersionStateEnum) Ptr() *WalletVersionStateEnum {
	return &v
}

type NullableWalletVersionStateEnum struct {
	value *WalletVersionStateEnum
	isSet bool
}

func (v NullableWalletVersionStateEnum) Get() *WalletVersionStateEnum {
	return v.value
}

func (v *NullableWalletVersionStateEnum) Set(val *WalletVersionStateEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletVersionStateEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletVersionStateEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletVersionStateEnum(val *WalletVersionStateEnum) *NullableWalletVersionStateEnum {
	return &NullableWalletVersionStateEnum{value: val, isSet: true}
}

func (v NullableWalletVersionStateEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletVersionStateEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
