/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the ExternalReceivingAddressRotation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalReceivingAddressRotation{}

// ExternalReceivingAddressRotation Reject extra or missing JSON keys instead of silently projecting them.
type ExternalReceivingAddressRotation struct {
	ChallengeId string `json:"challenge_id"`
	Proof ExternalAddressControlProofInput `json:"proof"`
	Reason string `json:"reason"`
	AdditionalProperties map[string]interface{}
}

type _ExternalReceivingAddressRotation ExternalReceivingAddressRotation

// NewExternalReceivingAddressRotation instantiates a new ExternalReceivingAddressRotation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalReceivingAddressRotation(challengeId string, proof ExternalAddressControlProofInput, reason string) *ExternalReceivingAddressRotation {
	this := ExternalReceivingAddressRotation{}
	this.ChallengeId = challengeId
	this.Proof = proof
	this.Reason = reason
	return &this
}

// NewExternalReceivingAddressRotationWithDefaults instantiates a new ExternalReceivingAddressRotation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalReceivingAddressRotationWithDefaults() *ExternalReceivingAddressRotation {
	this := ExternalReceivingAddressRotation{}
	return &this
}

// GetChallengeId returns the ChallengeId field value
func (o *ExternalReceivingAddressRotation) GetChallengeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChallengeId
}

// GetChallengeIdOk returns a tuple with the ChallengeId field value
// and a boolean to check if the value has been set.
func (o *ExternalReceivingAddressRotation) GetChallengeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChallengeId, true
}

// SetChallengeId sets field value
func (o *ExternalReceivingAddressRotation) SetChallengeId(v string) {
	o.ChallengeId = v
}

// GetProof returns the Proof field value
func (o *ExternalReceivingAddressRotation) GetProof() ExternalAddressControlProofInput {
	if o == nil {
		var ret ExternalAddressControlProofInput
		return ret
	}

	return o.Proof
}

// GetProofOk returns a tuple with the Proof field value
// and a boolean to check if the value has been set.
func (o *ExternalReceivingAddressRotation) GetProofOk() (*ExternalAddressControlProofInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Proof, true
}

// SetProof sets field value
func (o *ExternalReceivingAddressRotation) SetProof(v ExternalAddressControlProofInput) {
	o.Proof = v
}

// GetReason returns the Reason field value
func (o *ExternalReceivingAddressRotation) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ExternalReceivingAddressRotation) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *ExternalReceivingAddressRotation) SetReason(v string) {
	o.Reason = v
}

func (o ExternalReceivingAddressRotation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalReceivingAddressRotation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["challenge_id"] = o.ChallengeId
	toSerialize["proof"] = o.Proof
	toSerialize["reason"] = o.Reason

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExternalReceivingAddressRotation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"challenge_id",
		"proof",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExternalReceivingAddressRotation := _ExternalReceivingAddressRotation{}

	err = json.Unmarshal(data, &varExternalReceivingAddressRotation)

	if err != nil {
		return err
	}

	*o = ExternalReceivingAddressRotation(varExternalReceivingAddressRotation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "challenge_id")
		delete(additionalProperties, "proof")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExternalReceivingAddressRotation struct {
	value *ExternalReceivingAddressRotation
	isSet bool
}

func (v NullableExternalReceivingAddressRotation) Get() *ExternalReceivingAddressRotation {
	return v.value
}

func (v *NullableExternalReceivingAddressRotation) Set(val *ExternalReceivingAddressRotation) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalReceivingAddressRotation) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalReceivingAddressRotation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalReceivingAddressRotation(val *ExternalReceivingAddressRotation) *NullableExternalReceivingAddressRotation {
	return &NullableExternalReceivingAddressRotation{value: val, isSet: true}
}

func (v NullableExternalReceivingAddressRotation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalReceivingAddressRotation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
