/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// GasModeEnum * `buyer_pays` - buyer_pays * `sponsored` - sponsored
type GasModeEnum string

// List of GasModeEnum
const (
	GASMODEENUM_BUYER_PAYS GasModeEnum = "buyer_pays"
	GASMODEENUM_SPONSORED GasModeEnum = "sponsored"
	GASMODEENUM_UNKNOWN_DEFAULT_OPEN_API GasModeEnum = "unknown_default_open_api"
)

// All allowed values of GasModeEnum enum
var AllowedGasModeEnumEnumValues = []GasModeEnum{
	"buyer_pays",
	"sponsored",
	"unknown_default_open_api",
}

func (v *GasModeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GasModeEnum(value)
	for _, existing := range AllowedGasModeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = GASMODEENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewGasModeEnumFromValue returns a pointer to a valid GasModeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGasModeEnumFromValue(v string) (*GasModeEnum, error) {
	ev := GasModeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GasModeEnum: valid values are %v", v, AllowedGasModeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GasModeEnum) IsValid() bool {
	for _, existing := range AllowedGasModeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GasModeEnum value
func (v GasModeEnum) Ptr() *GasModeEnum {
	return &v
}

type NullableGasModeEnum struct {
	value *GasModeEnum
	isSet bool
}

func (v NullableGasModeEnum) Get() *GasModeEnum {
	return v.value
}

func (v *NullableGasModeEnum) Set(val *GasModeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableGasModeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableGasModeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGasModeEnum(val *GasModeEnum) *NullableGasModeEnum {
	return &NullableGasModeEnum{value: val, isSet: true}
}

func (v NullableGasModeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGasModeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
