/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// ResourceFeeModeEnum * `buyer_pays` - Buyer pays * `tenant_absorbs_up_to_cap` - Tenant absorbs up to cap
type ResourceFeeModeEnum string

// List of ResourceFeeModeEnum
const (
	RESOURCEFEEMODEENUM_BUYER_PAYS ResourceFeeModeEnum = "buyer_pays"
	RESOURCEFEEMODEENUM_TENANT_ABSORBS_UP_TO_CAP ResourceFeeModeEnum = "tenant_absorbs_up_to_cap"
	RESOURCEFEEMODEENUM_UNKNOWN_DEFAULT_OPEN_API ResourceFeeModeEnum = "unknown_default_open_api"
)

// All allowed values of ResourceFeeModeEnum enum
var AllowedResourceFeeModeEnumEnumValues = []ResourceFeeModeEnum{
	"buyer_pays",
	"tenant_absorbs_up_to_cap",
	"unknown_default_open_api",
}

func (v *ResourceFeeModeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResourceFeeModeEnum(value)
	for _, existing := range AllowedResourceFeeModeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = RESOURCEFEEMODEENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewResourceFeeModeEnumFromValue returns a pointer to a valid ResourceFeeModeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResourceFeeModeEnumFromValue(v string) (*ResourceFeeModeEnum, error) {
	ev := ResourceFeeModeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ResourceFeeModeEnum: valid values are %v", v, AllowedResourceFeeModeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ResourceFeeModeEnum) IsValid() bool {
	for _, existing := range AllowedResourceFeeModeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ResourceFeeModeEnum value
func (v ResourceFeeModeEnum) Ptr() *ResourceFeeModeEnum {
	return &v
}

type NullableResourceFeeModeEnum struct {
	value *ResourceFeeModeEnum
	isSet bool
}

func (v NullableResourceFeeModeEnum) Get() *ResourceFeeModeEnum {
	return v.value
}

func (v *NullableResourceFeeModeEnum) Set(val *ResourceFeeModeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceFeeModeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceFeeModeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceFeeModeEnum(val *ResourceFeeModeEnum) *NullableResourceFeeModeEnum {
	return &NullableResourceFeeModeEnum{value: val, isSet: true}
}

func (v NullableResourceFeeModeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceFeeModeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
