/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// ExternalAddressProofMethodEnum * `signed_message` - Signed message * `onchain_canary` - On-chain canary
type ExternalAddressProofMethodEnum string

// List of ExternalAddressProofMethodEnum
const (
	EXTERNALADDRESSPROOFMETHODENUM_SIGNED_MESSAGE ExternalAddressProofMethodEnum = "signed_message"
	EXTERNALADDRESSPROOFMETHODENUM_ONCHAIN_CANARY ExternalAddressProofMethodEnum = "onchain_canary"
	EXTERNALADDRESSPROOFMETHODENUM_UNKNOWN_DEFAULT_OPEN_API ExternalAddressProofMethodEnum = "unknown_default_open_api"
)

// All allowed values of ExternalAddressProofMethodEnum enum
var AllowedExternalAddressProofMethodEnumEnumValues = []ExternalAddressProofMethodEnum{
	"signed_message",
	"onchain_canary",
	"unknown_default_open_api",
}

func (v *ExternalAddressProofMethodEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ExternalAddressProofMethodEnum(value)
	for _, existing := range AllowedExternalAddressProofMethodEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = EXTERNALADDRESSPROOFMETHODENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewExternalAddressProofMethodEnumFromValue returns a pointer to a valid ExternalAddressProofMethodEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewExternalAddressProofMethodEnumFromValue(v string) (*ExternalAddressProofMethodEnum, error) {
	ev := ExternalAddressProofMethodEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ExternalAddressProofMethodEnum: valid values are %v", v, AllowedExternalAddressProofMethodEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ExternalAddressProofMethodEnum) IsValid() bool {
	for _, existing := range AllowedExternalAddressProofMethodEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ExternalAddressProofMethodEnum value
func (v ExternalAddressProofMethodEnum) Ptr() *ExternalAddressProofMethodEnum {
	return &v
}

type NullableExternalAddressProofMethodEnum struct {
	value *ExternalAddressProofMethodEnum
	isSet bool
}

func (v NullableExternalAddressProofMethodEnum) Get() *ExternalAddressProofMethodEnum {
	return v.value
}

func (v *NullableExternalAddressProofMethodEnum) Set(val *ExternalAddressProofMethodEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalAddressProofMethodEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalAddressProofMethodEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalAddressProofMethodEnum(val *ExternalAddressProofMethodEnum) *NullableExternalAddressProofMethodEnum {
	return &NullableExternalAddressProofMethodEnum{value: val, isSet: true}
}

func (v NullableExternalAddressProofMethodEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalAddressProofMethodEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
