/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// IdempotencyOutcomeStateEnum * `absent` - absent * `in_progress` - in_progress * `completed` - completed
type IdempotencyOutcomeStateEnum string

// List of IdempotencyOutcomeStateEnum
const (
	IDEMPOTENCYOUTCOMESTATEENUM_ABSENT IdempotencyOutcomeStateEnum = "absent"
	IDEMPOTENCYOUTCOMESTATEENUM_IN_PROGRESS IdempotencyOutcomeStateEnum = "in_progress"
	IDEMPOTENCYOUTCOMESTATEENUM_COMPLETED IdempotencyOutcomeStateEnum = "completed"
	IDEMPOTENCYOUTCOMESTATEENUM_UNKNOWN_DEFAULT_OPEN_API IdempotencyOutcomeStateEnum = "unknown_default_open_api"
)

// All allowed values of IdempotencyOutcomeStateEnum enum
var AllowedIdempotencyOutcomeStateEnumEnumValues = []IdempotencyOutcomeStateEnum{
	"absent",
	"in_progress",
	"completed",
	"unknown_default_open_api",
}

func (v *IdempotencyOutcomeStateEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IdempotencyOutcomeStateEnum(value)
	for _, existing := range AllowedIdempotencyOutcomeStateEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = IDEMPOTENCYOUTCOMESTATEENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewIdempotencyOutcomeStateEnumFromValue returns a pointer to a valid IdempotencyOutcomeStateEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIdempotencyOutcomeStateEnumFromValue(v string) (*IdempotencyOutcomeStateEnum, error) {
	ev := IdempotencyOutcomeStateEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IdempotencyOutcomeStateEnum: valid values are %v", v, AllowedIdempotencyOutcomeStateEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IdempotencyOutcomeStateEnum) IsValid() bool {
	for _, existing := range AllowedIdempotencyOutcomeStateEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IdempotencyOutcomeStateEnum value
func (v IdempotencyOutcomeStateEnum) Ptr() *IdempotencyOutcomeStateEnum {
	return &v
}

type NullableIdempotencyOutcomeStateEnum struct {
	value *IdempotencyOutcomeStateEnum
	isSet bool
}

func (v NullableIdempotencyOutcomeStateEnum) Get() *IdempotencyOutcomeStateEnum {
	return v.value
}

func (v *NullableIdempotencyOutcomeStateEnum) Set(val *IdempotencyOutcomeStateEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableIdempotencyOutcomeStateEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableIdempotencyOutcomeStateEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdempotencyOutcomeStateEnum(val *IdempotencyOutcomeStateEnum) *NullableIdempotencyOutcomeStateEnum {
	return &NullableIdempotencyOutcomeStateEnum{value: val, isSet: true}
}

func (v NullableIdempotencyOutcomeStateEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdempotencyOutcomeStateEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
