/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// ResourceCreateFulfillmentConfig - struct for ResourceCreateFulfillmentConfig
type ResourceCreateFulfillmentConfig struct {
	ResourceCreateFulfillmentConfigOneOf *ResourceCreateFulfillmentConfigOneOf
	ResourceCreateFulfillmentConfigOneOf1 *ResourceCreateFulfillmentConfigOneOf1
	MapmapOfStringAny *map[string]interface{}
}

// ResourceCreateFulfillmentConfigOneOfAsResourceCreateFulfillmentConfig is a convenience function that returns ResourceCreateFulfillmentConfigOneOf wrapped in ResourceCreateFulfillmentConfig
func ResourceCreateFulfillmentConfigOneOfAsResourceCreateFulfillmentConfig(v *ResourceCreateFulfillmentConfigOneOf) ResourceCreateFulfillmentConfig {
	return ResourceCreateFulfillmentConfig{
		ResourceCreateFulfillmentConfigOneOf: v,
	}
}

// ResourceCreateFulfillmentConfigOneOf1AsResourceCreateFulfillmentConfig is a convenience function that returns ResourceCreateFulfillmentConfigOneOf1 wrapped in ResourceCreateFulfillmentConfig
func ResourceCreateFulfillmentConfigOneOf1AsResourceCreateFulfillmentConfig(v *ResourceCreateFulfillmentConfigOneOf1) ResourceCreateFulfillmentConfig {
	return ResourceCreateFulfillmentConfig{
		ResourceCreateFulfillmentConfigOneOf1: v,
	}
}

// map[string]interface{}AsResourceCreateFulfillmentConfig is a convenience function that returns map[string]interface{} wrapped in ResourceCreateFulfillmentConfig
func MapmapOfStringAnyAsResourceCreateFulfillmentConfig(v *map[string]interface{}) ResourceCreateFulfillmentConfig {
	return ResourceCreateFulfillmentConfig{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ResourceCreateFulfillmentConfig) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ResourceCreateFulfillmentConfigOneOf
	err = json.Unmarshal(data, &dst.ResourceCreateFulfillmentConfigOneOf)
	if err == nil {
		jsonResourceCreateFulfillmentConfigOneOf, _ := json.Marshal(dst.ResourceCreateFulfillmentConfigOneOf)
		if string(jsonResourceCreateFulfillmentConfigOneOf) == "{}" { // empty struct
			dst.ResourceCreateFulfillmentConfigOneOf = nil
		} else {
			match++
		}
	} else {
		dst.ResourceCreateFulfillmentConfigOneOf = nil
	}

	// try to unmarshal data into ResourceCreateFulfillmentConfigOneOf1
	err = json.Unmarshal(data, &dst.ResourceCreateFulfillmentConfigOneOf1)
	if err == nil {
		jsonResourceCreateFulfillmentConfigOneOf1, _ := json.Marshal(dst.ResourceCreateFulfillmentConfigOneOf1)
		if string(jsonResourceCreateFulfillmentConfigOneOf1) == "{}" { // empty struct
			dst.ResourceCreateFulfillmentConfigOneOf1 = nil
		} else {
			match++
		}
	} else {
		dst.ResourceCreateFulfillmentConfigOneOf1 = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			match++
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ResourceCreateFulfillmentConfigOneOf = nil
		dst.ResourceCreateFulfillmentConfigOneOf1 = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ResourceCreateFulfillmentConfig)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
        if err != nil {
		   return fmt.Errorf("data failed to match schemas in oneOf(ResourceCreateFulfillmentConfig): %v", err)
        } else {
           return fmt.Errorf("data failed to match schemas in oneOf(ResourceCreateFulfillmentConfig)")
        }
        if err != nil {
		   return fmt.Errorf("data failed to match schemas in oneOf(ResourceCreateFulfillmentConfig): %v", err)
        } else {
           return fmt.Errorf("data failed to match schemas in oneOf(ResourceCreateFulfillmentConfig)")
        }
        if err != nil {
		   return fmt.Errorf("data failed to match schemas in oneOf(ResourceCreateFulfillmentConfig): %v", err)
        } else {
           return fmt.Errorf("data failed to match schemas in oneOf(ResourceCreateFulfillmentConfig)")
        }
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ResourceCreateFulfillmentConfig) MarshalJSON() ([]byte, error) {
	if src.ResourceCreateFulfillmentConfigOneOf != nil {
		return json.Marshal(&src.ResourceCreateFulfillmentConfigOneOf)
	}

	if src.ResourceCreateFulfillmentConfigOneOf1 != nil {
		return json.Marshal(&src.ResourceCreateFulfillmentConfigOneOf1)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ResourceCreateFulfillmentConfig) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ResourceCreateFulfillmentConfigOneOf != nil {
		return obj.ResourceCreateFulfillmentConfigOneOf
	}

	if obj.ResourceCreateFulfillmentConfigOneOf1 != nil {
		return obj.ResourceCreateFulfillmentConfigOneOf1
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ResourceCreateFulfillmentConfig) GetActualInstanceValue() (interface{}) {
	if obj.ResourceCreateFulfillmentConfigOneOf != nil {
		return *obj.ResourceCreateFulfillmentConfigOneOf
	}

	if obj.ResourceCreateFulfillmentConfigOneOf1 != nil {
		return *obj.ResourceCreateFulfillmentConfigOneOf1
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableResourceCreateFulfillmentConfig struct {
	value *ResourceCreateFulfillmentConfig
	isSet bool
}

func (v NullableResourceCreateFulfillmentConfig) Get() *ResourceCreateFulfillmentConfig {
	return v.value
}

func (v *NullableResourceCreateFulfillmentConfig) Set(val *ResourceCreateFulfillmentConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceCreateFulfillmentConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceCreateFulfillmentConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceCreateFulfillmentConfig(val *ResourceCreateFulfillmentConfig) *NullableResourceCreateFulfillmentConfig {
	return &NullableResourceCreateFulfillmentConfig{value: val, isSet: true}
}

func (v NullableResourceCreateFulfillmentConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceCreateFulfillmentConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
