/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the TenantPaymentResourceProjection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantPaymentResourceProjection{}

// TenantPaymentResourceProjection struct for TenantPaymentResourceProjection
type TenantPaymentResourceProjection struct {
	Id string `json:"id"`
	Key string `json:"key"`
	Name string `json:"name"`
	Version int32 `json:"version"`
	Method string `json:"method"`
	Path string `json:"path"`
	Description string `json:"description"`
	FulfillmentMode string `json:"fulfillment_mode"`
	AdditionalProperties map[string]interface{}
}

type _TenantPaymentResourceProjection TenantPaymentResourceProjection

// NewTenantPaymentResourceProjection instantiates a new TenantPaymentResourceProjection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantPaymentResourceProjection(id string, key string, name string, version int32, method string, path string, description string, fulfillmentMode string) *TenantPaymentResourceProjection {
	this := TenantPaymentResourceProjection{}
	this.Id = id
	this.Key = key
	this.Name = name
	this.Version = version
	this.Method = method
	this.Path = path
	this.Description = description
	this.FulfillmentMode = fulfillmentMode
	return &this
}

// NewTenantPaymentResourceProjectionWithDefaults instantiates a new TenantPaymentResourceProjection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantPaymentResourceProjectionWithDefaults() *TenantPaymentResourceProjection {
	this := TenantPaymentResourceProjection{}
	return &this
}

// GetId returns the Id field value
func (o *TenantPaymentResourceProjection) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentResourceProjection) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TenantPaymentResourceProjection) SetId(v string) {
	o.Id = v
}

// GetKey returns the Key field value
func (o *TenantPaymentResourceProjection) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentResourceProjection) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *TenantPaymentResourceProjection) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *TenantPaymentResourceProjection) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentResourceProjection) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TenantPaymentResourceProjection) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *TenantPaymentResourceProjection) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentResourceProjection) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *TenantPaymentResourceProjection) SetVersion(v int32) {
	o.Version = v
}

// GetMethod returns the Method field value
func (o *TenantPaymentResourceProjection) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentResourceProjection) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *TenantPaymentResourceProjection) SetMethod(v string) {
	o.Method = v
}

// GetPath returns the Path field value
func (o *TenantPaymentResourceProjection) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentResourceProjection) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *TenantPaymentResourceProjection) SetPath(v string) {
	o.Path = v
}

// GetDescription returns the Description field value
func (o *TenantPaymentResourceProjection) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentResourceProjection) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TenantPaymentResourceProjection) SetDescription(v string) {
	o.Description = v
}

// GetFulfillmentMode returns the FulfillmentMode field value
func (o *TenantPaymentResourceProjection) GetFulfillmentMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FulfillmentMode
}

// GetFulfillmentModeOk returns a tuple with the FulfillmentMode field value
// and a boolean to check if the value has been set.
func (o *TenantPaymentResourceProjection) GetFulfillmentModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FulfillmentMode, true
}

// SetFulfillmentMode sets field value
func (o *TenantPaymentResourceProjection) SetFulfillmentMode(v string) {
	o.FulfillmentMode = v
}

func (o TenantPaymentResourceProjection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantPaymentResourceProjection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["method"] = o.Method
	toSerialize["path"] = o.Path
	toSerialize["description"] = o.Description
	toSerialize["fulfillment_mode"] = o.FulfillmentMode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TenantPaymentResourceProjection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"key",
		"name",
		"version",
		"method",
		"path",
		"description",
		"fulfillment_mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantPaymentResourceProjection := _TenantPaymentResourceProjection{}

	err = json.Unmarshal(data, &varTenantPaymentResourceProjection)

	if err != nil {
		return err
	}

	*o = TenantPaymentResourceProjection(varTenantPaymentResourceProjection)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "key")
		delete(additionalProperties, "name")
		delete(additionalProperties, "version")
		delete(additionalProperties, "method")
		delete(additionalProperties, "path")
		delete(additionalProperties, "description")
		delete(additionalProperties, "fulfillment_mode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTenantPaymentResourceProjection struct {
	value *TenantPaymentResourceProjection
	isSet bool
}

func (v NullableTenantPaymentResourceProjection) Get() *TenantPaymentResourceProjection {
	return v.value
}

func (v *NullableTenantPaymentResourceProjection) Set(val *TenantPaymentResourceProjection) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantPaymentResourceProjection) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantPaymentResourceProjection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantPaymentResourceProjection(val *TenantPaymentResourceProjection) *NullableTenantPaymentResourceProjection {
	return &NullableTenantPaymentResourceProjection{value: val, isSet: true}
}

func (v NullableTenantPaymentResourceProjection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantPaymentResourceProjection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
