/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the NetworkFeePreviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkFeePreviewResponse{}

// NetworkFeePreviewResponse struct for NetworkFeePreviewResponse
type NetworkFeePreviewResponse struct {
	FeePolicy PublicFeePolicyDocument `json:"fee_policy"`
	Alternatives []PublicNetworkFeeAlternative `json:"alternatives"`
	FeeQuoteDigest string `json:"fee_quote_digest" validate:"regexp=^sha256:[0-9a-f]{64}$"`
	AdditionalProperties map[string]interface{}
}

type _NetworkFeePreviewResponse NetworkFeePreviewResponse

// NewNetworkFeePreviewResponse instantiates a new NetworkFeePreviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkFeePreviewResponse(feePolicy PublicFeePolicyDocument, alternatives []PublicNetworkFeeAlternative, feeQuoteDigest string) *NetworkFeePreviewResponse {
	this := NetworkFeePreviewResponse{}
	this.FeePolicy = feePolicy
	this.Alternatives = alternatives
	this.FeeQuoteDigest = feeQuoteDigest
	return &this
}

// NewNetworkFeePreviewResponseWithDefaults instantiates a new NetworkFeePreviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkFeePreviewResponseWithDefaults() *NetworkFeePreviewResponse {
	this := NetworkFeePreviewResponse{}
	return &this
}

// GetFeePolicy returns the FeePolicy field value
func (o *NetworkFeePreviewResponse) GetFeePolicy() PublicFeePolicyDocument {
	if o == nil {
		var ret PublicFeePolicyDocument
		return ret
	}

	return o.FeePolicy
}

// GetFeePolicyOk returns a tuple with the FeePolicy field value
// and a boolean to check if the value has been set.
func (o *NetworkFeePreviewResponse) GetFeePolicyOk() (*PublicFeePolicyDocument, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeePolicy, true
}

// SetFeePolicy sets field value
func (o *NetworkFeePreviewResponse) SetFeePolicy(v PublicFeePolicyDocument) {
	o.FeePolicy = v
}

// GetAlternatives returns the Alternatives field value
func (o *NetworkFeePreviewResponse) GetAlternatives() []PublicNetworkFeeAlternative {
	if o == nil {
		var ret []PublicNetworkFeeAlternative
		return ret
	}

	return o.Alternatives
}

// GetAlternativesOk returns a tuple with the Alternatives field value
// and a boolean to check if the value has been set.
func (o *NetworkFeePreviewResponse) GetAlternativesOk() ([]PublicNetworkFeeAlternative, bool) {
	if o == nil {
		return nil, false
	}
	return o.Alternatives, true
}

// SetAlternatives sets field value
func (o *NetworkFeePreviewResponse) SetAlternatives(v []PublicNetworkFeeAlternative) {
	o.Alternatives = v
}

// GetFeeQuoteDigest returns the FeeQuoteDigest field value
func (o *NetworkFeePreviewResponse) GetFeeQuoteDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeQuoteDigest
}

// GetFeeQuoteDigestOk returns a tuple with the FeeQuoteDigest field value
// and a boolean to check if the value has been set.
func (o *NetworkFeePreviewResponse) GetFeeQuoteDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeQuoteDigest, true
}

// SetFeeQuoteDigest sets field value
func (o *NetworkFeePreviewResponse) SetFeeQuoteDigest(v string) {
	o.FeeQuoteDigest = v
}

func (o NetworkFeePreviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkFeePreviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fee_policy"] = o.FeePolicy
	toSerialize["alternatives"] = o.Alternatives
	toSerialize["fee_quote_digest"] = o.FeeQuoteDigest

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NetworkFeePreviewResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fee_policy",
		"alternatives",
		"fee_quote_digest",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkFeePreviewResponse := _NetworkFeePreviewResponse{}

	err = json.Unmarshal(data, &varNetworkFeePreviewResponse)

	if err != nil {
		return err
	}

	*o = NetworkFeePreviewResponse(varNetworkFeePreviewResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fee_policy")
		delete(additionalProperties, "alternatives")
		delete(additionalProperties, "fee_quote_digest")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNetworkFeePreviewResponse struct {
	value *NetworkFeePreviewResponse
	isSet bool
}

func (v NullableNetworkFeePreviewResponse) Get() *NetworkFeePreviewResponse {
	return v.value
}

func (v *NullableNetworkFeePreviewResponse) Set(val *NetworkFeePreviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkFeePreviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkFeePreviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkFeePreviewResponse(val *NetworkFeePreviewResponse) *NullableNetworkFeePreviewResponse {
	return &NullableNetworkFeePreviewResponse{value: val, isSet: true}
}

func (v NullableNetworkFeePreviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkFeePreviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
