/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the WalletVersionBalance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletVersionBalance{}

// WalletVersionBalance struct for WalletVersionBalance
type WalletVersionBalance struct {
	WalletVersionId string `json:"wallet_version_id"`
	Version int32 `json:"version"`
	WalletAddress string `json:"wallet_address"`
	State WalletVersionBalanceStateEnum `json:"state"`
	ObservationState ObservationStateEnum `json:"observation_state"`
	TrackingStatus TrackingStatusEnum `json:"tracking_status"`
	ObservedAt NullableTime `json:"observed_at"`
	Assets []BalanceAsset `json:"assets"`
	ReseedContext NullableWalletChainReseedContext `json:"reseed_context"`
	AdditionalProperties map[string]interface{}
}

type _WalletVersionBalance WalletVersionBalance

// NewWalletVersionBalance instantiates a new WalletVersionBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletVersionBalance(walletVersionId string, version int32, walletAddress string, state WalletVersionBalanceStateEnum, observationState ObservationStateEnum, trackingStatus TrackingStatusEnum, observedAt NullableTime, assets []BalanceAsset, reseedContext NullableWalletChainReseedContext) *WalletVersionBalance {
	this := WalletVersionBalance{}
	this.WalletVersionId = walletVersionId
	this.Version = version
	this.WalletAddress = walletAddress
	this.State = state
	this.ObservationState = observationState
	this.TrackingStatus = trackingStatus
	this.ObservedAt = observedAt
	this.Assets = assets
	this.ReseedContext = reseedContext
	return &this
}

// NewWalletVersionBalanceWithDefaults instantiates a new WalletVersionBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletVersionBalanceWithDefaults() *WalletVersionBalance {
	this := WalletVersionBalance{}
	return &this
}

// GetWalletVersionId returns the WalletVersionId field value
func (o *WalletVersionBalance) GetWalletVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletVersionId
}

// GetWalletVersionIdOk returns a tuple with the WalletVersionId field value
// and a boolean to check if the value has been set.
func (o *WalletVersionBalance) GetWalletVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletVersionId, true
}

// SetWalletVersionId sets field value
func (o *WalletVersionBalance) SetWalletVersionId(v string) {
	o.WalletVersionId = v
}

// GetVersion returns the Version field value
func (o *WalletVersionBalance) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *WalletVersionBalance) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *WalletVersionBalance) SetVersion(v int32) {
	o.Version = v
}

// GetWalletAddress returns the WalletAddress field value
func (o *WalletVersionBalance) GetWalletAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletAddress
}

// GetWalletAddressOk returns a tuple with the WalletAddress field value
// and a boolean to check if the value has been set.
func (o *WalletVersionBalance) GetWalletAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletAddress, true
}

// SetWalletAddress sets field value
func (o *WalletVersionBalance) SetWalletAddress(v string) {
	o.WalletAddress = v
}

// GetState returns the State field value
func (o *WalletVersionBalance) GetState() WalletVersionBalanceStateEnum {
	if o == nil {
		var ret WalletVersionBalanceStateEnum
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *WalletVersionBalance) GetStateOk() (*WalletVersionBalanceStateEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *WalletVersionBalance) SetState(v WalletVersionBalanceStateEnum) {
	o.State = v
}

// GetObservationState returns the ObservationState field value
func (o *WalletVersionBalance) GetObservationState() ObservationStateEnum {
	if o == nil {
		var ret ObservationStateEnum
		return ret
	}

	return o.ObservationState
}

// GetObservationStateOk returns a tuple with the ObservationState field value
// and a boolean to check if the value has been set.
func (o *WalletVersionBalance) GetObservationStateOk() (*ObservationStateEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservationState, true
}

// SetObservationState sets field value
func (o *WalletVersionBalance) SetObservationState(v ObservationStateEnum) {
	o.ObservationState = v
}

// GetTrackingStatus returns the TrackingStatus field value
func (o *WalletVersionBalance) GetTrackingStatus() TrackingStatusEnum {
	if o == nil {
		var ret TrackingStatusEnum
		return ret
	}

	return o.TrackingStatus
}

// GetTrackingStatusOk returns a tuple with the TrackingStatus field value
// and a boolean to check if the value has been set.
func (o *WalletVersionBalance) GetTrackingStatusOk() (*TrackingStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingStatus, true
}

// SetTrackingStatus sets field value
func (o *WalletVersionBalance) SetTrackingStatus(v TrackingStatusEnum) {
	o.TrackingStatus = v
}

// GetObservedAt returns the ObservedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *WalletVersionBalance) GetObservedAt() time.Time {
	if o == nil || o.ObservedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ObservedAt.Get()
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WalletVersionBalance) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ObservedAt.Get(), o.ObservedAt.IsSet()
}

// SetObservedAt sets field value
func (o *WalletVersionBalance) SetObservedAt(v time.Time) {
	o.ObservedAt.Set(&v)
}

// GetAssets returns the Assets field value
func (o *WalletVersionBalance) GetAssets() []BalanceAsset {
	if o == nil {
		var ret []BalanceAsset
		return ret
	}

	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value
// and a boolean to check if the value has been set.
func (o *WalletVersionBalance) GetAssetsOk() ([]BalanceAsset, bool) {
	if o == nil {
		return nil, false
	}
	return o.Assets, true
}

// SetAssets sets field value
func (o *WalletVersionBalance) SetAssets(v []BalanceAsset) {
	o.Assets = v
}

// GetReseedContext returns the ReseedContext field value
// If the value is explicit nil, the zero value for WalletChainReseedContext will be returned
func (o *WalletVersionBalance) GetReseedContext() WalletChainReseedContext {
	if o == nil || o.ReseedContext.Get() == nil {
		var ret WalletChainReseedContext
		return ret
	}

	return *o.ReseedContext.Get()
}

// GetReseedContextOk returns a tuple with the ReseedContext field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WalletVersionBalance) GetReseedContextOk() (*WalletChainReseedContext, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReseedContext.Get(), o.ReseedContext.IsSet()
}

// SetReseedContext sets field value
func (o *WalletVersionBalance) SetReseedContext(v WalletChainReseedContext) {
	o.ReseedContext.Set(&v)
}

func (o WalletVersionBalance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletVersionBalance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["wallet_version_id"] = o.WalletVersionId
	toSerialize["version"] = o.Version
	toSerialize["wallet_address"] = o.WalletAddress
	toSerialize["state"] = o.State
	toSerialize["observation_state"] = o.ObservationState
	toSerialize["tracking_status"] = o.TrackingStatus
	toSerialize["observed_at"] = o.ObservedAt.Get()
	toSerialize["assets"] = o.Assets
	toSerialize["reseed_context"] = o.ReseedContext.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WalletVersionBalance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"wallet_version_id",
		"version",
		"wallet_address",
		"state",
		"observation_state",
		"tracking_status",
		"observed_at",
		"assets",
		"reseed_context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWalletVersionBalance := _WalletVersionBalance{}

	err = json.Unmarshal(data, &varWalletVersionBalance)

	if err != nil {
		return err
	}

	*o = WalletVersionBalance(varWalletVersionBalance)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "wallet_version_id")
		delete(additionalProperties, "version")
		delete(additionalProperties, "wallet_address")
		delete(additionalProperties, "state")
		delete(additionalProperties, "observation_state")
		delete(additionalProperties, "tracking_status")
		delete(additionalProperties, "observed_at")
		delete(additionalProperties, "assets")
		delete(additionalProperties, "reseed_context")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWalletVersionBalance struct {
	value *WalletVersionBalance
	isSet bool
}

func (v NullableWalletVersionBalance) Get() *WalletVersionBalance {
	return v.value
}

func (v *NullableWalletVersionBalance) Set(val *WalletVersionBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletVersionBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletVersionBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletVersionBalance(val *WalletVersionBalance) *NullableWalletVersionBalance {
	return &NullableWalletVersionBalance{value: val, isSet: true}
}

func (v NullableWalletVersionBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletVersionBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
