/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the BalanceAsset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BalanceAsset{}

// BalanceAsset struct for BalanceAsset
type BalanceAsset struct {
	AssetId string `json:"asset_id"`
	DisplayName string `json:"display_name"`
	Symbol string `json:"symbol"`
	ContractAddress string `json:"contract_address"`
	Decimals int32 `json:"decimals"`
	AmountAtomic string `json:"amount_atomic"`
	Amount string `json:"amount"`
	IssuerNative bool `json:"issuer_native"`
	ObservedAt time.Time `json:"observed_at"`
	NodeSource string `json:"node_source"`
	SourceConsensus string `json:"source_consensus"`
	Block ObservationBlock `json:"block"`
	AdditionalProperties map[string]interface{}
}

type _BalanceAsset BalanceAsset

// NewBalanceAsset instantiates a new BalanceAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBalanceAsset(assetId string, displayName string, symbol string, contractAddress string, decimals int32, amountAtomic string, amount string, issuerNative bool, observedAt time.Time, nodeSource string, sourceConsensus string, block ObservationBlock) *BalanceAsset {
	this := BalanceAsset{}
	this.AssetId = assetId
	this.DisplayName = displayName
	this.Symbol = symbol
	this.ContractAddress = contractAddress
	this.Decimals = decimals
	this.AmountAtomic = amountAtomic
	this.Amount = amount
	this.IssuerNative = issuerNative
	this.ObservedAt = observedAt
	this.NodeSource = nodeSource
	this.SourceConsensus = sourceConsensus
	this.Block = block
	return &this
}

// NewBalanceAssetWithDefaults instantiates a new BalanceAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBalanceAssetWithDefaults() *BalanceAsset {
	this := BalanceAsset{}
	return &this
}

// GetAssetId returns the AssetId field value
func (o *BalanceAsset) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *BalanceAsset) SetAssetId(v string) {
	o.AssetId = v
}

// GetDisplayName returns the DisplayName field value
func (o *BalanceAsset) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *BalanceAsset) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetSymbol returns the Symbol field value
func (o *BalanceAsset) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *BalanceAsset) SetSymbol(v string) {
	o.Symbol = v
}

// GetContractAddress returns the ContractAddress field value
func (o *BalanceAsset) GetContractAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetContractAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractAddress, true
}

// SetContractAddress sets field value
func (o *BalanceAsset) SetContractAddress(v string) {
	o.ContractAddress = v
}

// GetDecimals returns the Decimals field value
func (o *BalanceAsset) GetDecimals() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetDecimalsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decimals, true
}

// SetDecimals sets field value
func (o *BalanceAsset) SetDecimals(v int32) {
	o.Decimals = v
}

// GetAmountAtomic returns the AmountAtomic field value
func (o *BalanceAsset) GetAmountAtomic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountAtomic
}

// GetAmountAtomicOk returns a tuple with the AmountAtomic field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetAmountAtomicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountAtomic, true
}

// SetAmountAtomic sets field value
func (o *BalanceAsset) SetAmountAtomic(v string) {
	o.AmountAtomic = v
}

// GetAmount returns the Amount field value
func (o *BalanceAsset) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *BalanceAsset) SetAmount(v string) {
	o.Amount = v
}

// GetIssuerNative returns the IssuerNative field value
func (o *BalanceAsset) GetIssuerNative() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IssuerNative
}

// GetIssuerNativeOk returns a tuple with the IssuerNative field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetIssuerNativeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerNative, true
}

// SetIssuerNative sets field value
func (o *BalanceAsset) SetIssuerNative(v bool) {
	o.IssuerNative = v
}

// GetObservedAt returns the ObservedAt field value
func (o *BalanceAsset) GetObservedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ObservedAt
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedAt, true
}

// SetObservedAt sets field value
func (o *BalanceAsset) SetObservedAt(v time.Time) {
	o.ObservedAt = v
}

// GetNodeSource returns the NodeSource field value
func (o *BalanceAsset) GetNodeSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeSource
}

// GetNodeSourceOk returns a tuple with the NodeSource field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetNodeSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeSource, true
}

// SetNodeSource sets field value
func (o *BalanceAsset) SetNodeSource(v string) {
	o.NodeSource = v
}

// GetSourceConsensus returns the SourceConsensus field value
func (o *BalanceAsset) GetSourceConsensus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceConsensus
}

// GetSourceConsensusOk returns a tuple with the SourceConsensus field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetSourceConsensusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceConsensus, true
}

// SetSourceConsensus sets field value
func (o *BalanceAsset) SetSourceConsensus(v string) {
	o.SourceConsensus = v
}

// GetBlock returns the Block field value
func (o *BalanceAsset) GetBlock() ObservationBlock {
	if o == nil {
		var ret ObservationBlock
		return ret
	}

	return o.Block
}

// GetBlockOk returns a tuple with the Block field value
// and a boolean to check if the value has been set.
func (o *BalanceAsset) GetBlockOk() (*ObservationBlock, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Block, true
}

// SetBlock sets field value
func (o *BalanceAsset) SetBlock(v ObservationBlock) {
	o.Block = v
}

func (o BalanceAsset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BalanceAsset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_id"] = o.AssetId
	toSerialize["display_name"] = o.DisplayName
	toSerialize["symbol"] = o.Symbol
	toSerialize["contract_address"] = o.ContractAddress
	toSerialize["decimals"] = o.Decimals
	toSerialize["amount_atomic"] = o.AmountAtomic
	toSerialize["amount"] = o.Amount
	toSerialize["issuer_native"] = o.IssuerNative
	toSerialize["observed_at"] = o.ObservedAt
	toSerialize["node_source"] = o.NodeSource
	toSerialize["source_consensus"] = o.SourceConsensus
	toSerialize["block"] = o.Block

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BalanceAsset) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_id",
		"display_name",
		"symbol",
		"contract_address",
		"decimals",
		"amount_atomic",
		"amount",
		"issuer_native",
		"observed_at",
		"node_source",
		"source_consensus",
		"block",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBalanceAsset := _BalanceAsset{}

	err = json.Unmarshal(data, &varBalanceAsset)

	if err != nil {
		return err
	}

	*o = BalanceAsset(varBalanceAsset)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "asset_id")
		delete(additionalProperties, "display_name")
		delete(additionalProperties, "symbol")
		delete(additionalProperties, "contract_address")
		delete(additionalProperties, "decimals")
		delete(additionalProperties, "amount_atomic")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "issuer_native")
		delete(additionalProperties, "observed_at")
		delete(additionalProperties, "node_source")
		delete(additionalProperties, "source_consensus")
		delete(additionalProperties, "block")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBalanceAsset struct {
	value *BalanceAsset
	isSet bool
}

func (v NullableBalanceAsset) Get() *BalanceAsset {
	return v.value
}

func (v *NullableBalanceAsset) Set(val *BalanceAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableBalanceAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableBalanceAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalanceAsset(val *BalanceAsset) *NullableBalanceAsset {
	return &NullableBalanceAsset{value: val, isSet: true}
}

func (v NullableBalanceAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalanceAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
