/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the PaymentReadinessRail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentReadinessRail{}

// PaymentReadinessRail struct for PaymentReadinessRail
type PaymentReadinessRail struct {
	AssetId string `json:"asset_id"`
	Network string `json:"network"`
	Symbol string `json:"symbol"`
	Selected bool `json:"selected"`
	WalletReady bool `json:"wallet_ready"`
	PlatformAvailable bool `json:"platform_available"`
	AcceptingNewPayments bool `json:"accepting_new_payments"`
	ReadyForNewPayment bool `json:"ready_for_new_payment"`
	ReadinessValidUntil NullableTime `json:"readiness_valid_until"`
	FeeQuoteReady bool `json:"fee_quote_ready"`
	FeeQuoteValidUntil NullableTime `json:"fee_quote_valid_until"`
	Status string `json:"status"`
	Blockers []PaymentReadinessBlocker `json:"blockers"`
	TenantChallengesEnabled bool `json:"tenant_challenges_enabled"`
	TenantSettlementEnabled bool `json:"tenant_settlement_enabled"`
	NetworkAssistanceEnabled bool `json:"network_assistance_enabled"`
	ChallengeControlReady bool `json:"challenge_control_ready"`
	SettlementControlReady bool `json:"settlement_control_ready"`
	Assets []PaymentReadinessAsset `json:"assets"`
	AdditionalProperties map[string]interface{}
}

type _PaymentReadinessRail PaymentReadinessRail

// NewPaymentReadinessRail instantiates a new PaymentReadinessRail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentReadinessRail(assetId string, network string, symbol string, selected bool, walletReady bool, platformAvailable bool, acceptingNewPayments bool, readyForNewPayment bool, readinessValidUntil NullableTime, feeQuoteReady bool, feeQuoteValidUntil NullableTime, status string, blockers []PaymentReadinessBlocker, tenantChallengesEnabled bool, tenantSettlementEnabled bool, networkAssistanceEnabled bool, challengeControlReady bool, settlementControlReady bool, assets []PaymentReadinessAsset) *PaymentReadinessRail {
	this := PaymentReadinessRail{}
	this.AssetId = assetId
	this.Network = network
	this.Symbol = symbol
	this.Selected = selected
	this.WalletReady = walletReady
	this.PlatformAvailable = platformAvailable
	this.AcceptingNewPayments = acceptingNewPayments
	this.ReadyForNewPayment = readyForNewPayment
	this.ReadinessValidUntil = readinessValidUntil
	this.FeeQuoteReady = feeQuoteReady
	this.FeeQuoteValidUntil = feeQuoteValidUntil
	this.Status = status
	this.Blockers = blockers
	this.TenantChallengesEnabled = tenantChallengesEnabled
	this.TenantSettlementEnabled = tenantSettlementEnabled
	this.NetworkAssistanceEnabled = networkAssistanceEnabled
	this.ChallengeControlReady = challengeControlReady
	this.SettlementControlReady = settlementControlReady
	this.Assets = assets
	return &this
}

// NewPaymentReadinessRailWithDefaults instantiates a new PaymentReadinessRail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentReadinessRailWithDefaults() *PaymentReadinessRail {
	this := PaymentReadinessRail{}
	return &this
}

// GetAssetId returns the AssetId field value
func (o *PaymentReadinessRail) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *PaymentReadinessRail) SetAssetId(v string) {
	o.AssetId = v
}

// GetNetwork returns the Network field value
func (o *PaymentReadinessRail) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *PaymentReadinessRail) SetNetwork(v string) {
	o.Network = v
}

// GetSymbol returns the Symbol field value
func (o *PaymentReadinessRail) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *PaymentReadinessRail) SetSymbol(v string) {
	o.Symbol = v
}

// GetSelected returns the Selected field value
func (o *PaymentReadinessRail) GetSelected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Selected
}

// GetSelectedOk returns a tuple with the Selected field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetSelectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Selected, true
}

// SetSelected sets field value
func (o *PaymentReadinessRail) SetSelected(v bool) {
	o.Selected = v
}

// GetWalletReady returns the WalletReady field value
func (o *PaymentReadinessRail) GetWalletReady() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.WalletReady
}

// GetWalletReadyOk returns a tuple with the WalletReady field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetWalletReadyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletReady, true
}

// SetWalletReady sets field value
func (o *PaymentReadinessRail) SetWalletReady(v bool) {
	o.WalletReady = v
}

// GetPlatformAvailable returns the PlatformAvailable field value
func (o *PaymentReadinessRail) GetPlatformAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PlatformAvailable
}

// GetPlatformAvailableOk returns a tuple with the PlatformAvailable field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetPlatformAvailableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlatformAvailable, true
}

// SetPlatformAvailable sets field value
func (o *PaymentReadinessRail) SetPlatformAvailable(v bool) {
	o.PlatformAvailable = v
}

// GetAcceptingNewPayments returns the AcceptingNewPayments field value
func (o *PaymentReadinessRail) GetAcceptingNewPayments() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AcceptingNewPayments
}

// GetAcceptingNewPaymentsOk returns a tuple with the AcceptingNewPayments field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetAcceptingNewPaymentsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AcceptingNewPayments, true
}

// SetAcceptingNewPayments sets field value
func (o *PaymentReadinessRail) SetAcceptingNewPayments(v bool) {
	o.AcceptingNewPayments = v
}

// GetReadyForNewPayment returns the ReadyForNewPayment field value
func (o *PaymentReadinessRail) GetReadyForNewPayment() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReadyForNewPayment
}

// GetReadyForNewPaymentOk returns a tuple with the ReadyForNewPayment field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetReadyForNewPaymentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReadyForNewPayment, true
}

// SetReadyForNewPayment sets field value
func (o *PaymentReadinessRail) SetReadyForNewPayment(v bool) {
	o.ReadyForNewPayment = v
}

// GetReadinessValidUntil returns the ReadinessValidUntil field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *PaymentReadinessRail) GetReadinessValidUntil() time.Time {
	if o == nil || o.ReadinessValidUntil.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ReadinessValidUntil.Get()
}

// GetReadinessValidUntilOk returns a tuple with the ReadinessValidUntil field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentReadinessRail) GetReadinessValidUntilOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReadinessValidUntil.Get(), o.ReadinessValidUntil.IsSet()
}

// SetReadinessValidUntil sets field value
func (o *PaymentReadinessRail) SetReadinessValidUntil(v time.Time) {
	o.ReadinessValidUntil.Set(&v)
}

// GetFeeQuoteReady returns the FeeQuoteReady field value
func (o *PaymentReadinessRail) GetFeeQuoteReady() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FeeQuoteReady
}

// GetFeeQuoteReadyOk returns a tuple with the FeeQuoteReady field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetFeeQuoteReadyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeQuoteReady, true
}

// SetFeeQuoteReady sets field value
func (o *PaymentReadinessRail) SetFeeQuoteReady(v bool) {
	o.FeeQuoteReady = v
}

// GetFeeQuoteValidUntil returns the FeeQuoteValidUntil field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *PaymentReadinessRail) GetFeeQuoteValidUntil() time.Time {
	if o == nil || o.FeeQuoteValidUntil.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.FeeQuoteValidUntil.Get()
}

// GetFeeQuoteValidUntilOk returns a tuple with the FeeQuoteValidUntil field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentReadinessRail) GetFeeQuoteValidUntilOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeeQuoteValidUntil.Get(), o.FeeQuoteValidUntil.IsSet()
}

// SetFeeQuoteValidUntil sets field value
func (o *PaymentReadinessRail) SetFeeQuoteValidUntil(v time.Time) {
	o.FeeQuoteValidUntil.Set(&v)
}

// GetStatus returns the Status field value
func (o *PaymentReadinessRail) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PaymentReadinessRail) SetStatus(v string) {
	o.Status = v
}

// GetBlockers returns the Blockers field value
func (o *PaymentReadinessRail) GetBlockers() []PaymentReadinessBlocker {
	if o == nil {
		var ret []PaymentReadinessBlocker
		return ret
	}

	return o.Blockers
}

// GetBlockersOk returns a tuple with the Blockers field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetBlockersOk() ([]PaymentReadinessBlocker, bool) {
	if o == nil {
		return nil, false
	}
	return o.Blockers, true
}

// SetBlockers sets field value
func (o *PaymentReadinessRail) SetBlockers(v []PaymentReadinessBlocker) {
	o.Blockers = v
}

// GetTenantChallengesEnabled returns the TenantChallengesEnabled field value
func (o *PaymentReadinessRail) GetTenantChallengesEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TenantChallengesEnabled
}

// GetTenantChallengesEnabledOk returns a tuple with the TenantChallengesEnabled field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetTenantChallengesEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantChallengesEnabled, true
}

// SetTenantChallengesEnabled sets field value
func (o *PaymentReadinessRail) SetTenantChallengesEnabled(v bool) {
	o.TenantChallengesEnabled = v
}

// GetTenantSettlementEnabled returns the TenantSettlementEnabled field value
func (o *PaymentReadinessRail) GetTenantSettlementEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TenantSettlementEnabled
}

// GetTenantSettlementEnabledOk returns a tuple with the TenantSettlementEnabled field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetTenantSettlementEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantSettlementEnabled, true
}

// SetTenantSettlementEnabled sets field value
func (o *PaymentReadinessRail) SetTenantSettlementEnabled(v bool) {
	o.TenantSettlementEnabled = v
}

// GetNetworkAssistanceEnabled returns the NetworkAssistanceEnabled field value
func (o *PaymentReadinessRail) GetNetworkAssistanceEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.NetworkAssistanceEnabled
}

// GetNetworkAssistanceEnabledOk returns a tuple with the NetworkAssistanceEnabled field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetNetworkAssistanceEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkAssistanceEnabled, true
}

// SetNetworkAssistanceEnabled sets field value
func (o *PaymentReadinessRail) SetNetworkAssistanceEnabled(v bool) {
	o.NetworkAssistanceEnabled = v
}

// GetChallengeControlReady returns the ChallengeControlReady field value
func (o *PaymentReadinessRail) GetChallengeControlReady() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ChallengeControlReady
}

// GetChallengeControlReadyOk returns a tuple with the ChallengeControlReady field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetChallengeControlReadyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChallengeControlReady, true
}

// SetChallengeControlReady sets field value
func (o *PaymentReadinessRail) SetChallengeControlReady(v bool) {
	o.ChallengeControlReady = v
}

// GetSettlementControlReady returns the SettlementControlReady field value
func (o *PaymentReadinessRail) GetSettlementControlReady() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SettlementControlReady
}

// GetSettlementControlReadyOk returns a tuple with the SettlementControlReady field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetSettlementControlReadyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementControlReady, true
}

// SetSettlementControlReady sets field value
func (o *PaymentReadinessRail) SetSettlementControlReady(v bool) {
	o.SettlementControlReady = v
}

// GetAssets returns the Assets field value
func (o *PaymentReadinessRail) GetAssets() []PaymentReadinessAsset {
	if o == nil {
		var ret []PaymentReadinessAsset
		return ret
	}

	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value
// and a boolean to check if the value has been set.
func (o *PaymentReadinessRail) GetAssetsOk() ([]PaymentReadinessAsset, bool) {
	if o == nil {
		return nil, false
	}
	return o.Assets, true
}

// SetAssets sets field value
func (o *PaymentReadinessRail) SetAssets(v []PaymentReadinessAsset) {
	o.Assets = v
}

func (o PaymentReadinessRail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentReadinessRail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_id"] = o.AssetId
	toSerialize["network"] = o.Network
	toSerialize["symbol"] = o.Symbol
	toSerialize["selected"] = o.Selected
	toSerialize["wallet_ready"] = o.WalletReady
	toSerialize["platform_available"] = o.PlatformAvailable
	toSerialize["accepting_new_payments"] = o.AcceptingNewPayments
	toSerialize["ready_for_new_payment"] = o.ReadyForNewPayment
	toSerialize["readiness_valid_until"] = o.ReadinessValidUntil.Get()
	toSerialize["fee_quote_ready"] = o.FeeQuoteReady
	toSerialize["fee_quote_valid_until"] = o.FeeQuoteValidUntil.Get()
	toSerialize["status"] = o.Status
	toSerialize["blockers"] = o.Blockers
	toSerialize["tenant_challenges_enabled"] = o.TenantChallengesEnabled
	toSerialize["tenant_settlement_enabled"] = o.TenantSettlementEnabled
	toSerialize["network_assistance_enabled"] = o.NetworkAssistanceEnabled
	toSerialize["challenge_control_ready"] = o.ChallengeControlReady
	toSerialize["settlement_control_ready"] = o.SettlementControlReady
	toSerialize["assets"] = o.Assets

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentReadinessRail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_id",
		"network",
		"symbol",
		"selected",
		"wallet_ready",
		"platform_available",
		"accepting_new_payments",
		"ready_for_new_payment",
		"readiness_valid_until",
		"fee_quote_ready",
		"fee_quote_valid_until",
		"status",
		"blockers",
		"tenant_challenges_enabled",
		"tenant_settlement_enabled",
		"network_assistance_enabled",
		"challenge_control_ready",
		"settlement_control_ready",
		"assets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentReadinessRail := _PaymentReadinessRail{}

	err = json.Unmarshal(data, &varPaymentReadinessRail)

	if err != nil {
		return err
	}

	*o = PaymentReadinessRail(varPaymentReadinessRail)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "asset_id")
		delete(additionalProperties, "network")
		delete(additionalProperties, "symbol")
		delete(additionalProperties, "selected")
		delete(additionalProperties, "wallet_ready")
		delete(additionalProperties, "platform_available")
		delete(additionalProperties, "accepting_new_payments")
		delete(additionalProperties, "ready_for_new_payment")
		delete(additionalProperties, "readiness_valid_until")
		delete(additionalProperties, "fee_quote_ready")
		delete(additionalProperties, "fee_quote_valid_until")
		delete(additionalProperties, "status")
		delete(additionalProperties, "blockers")
		delete(additionalProperties, "tenant_challenges_enabled")
		delete(additionalProperties, "tenant_settlement_enabled")
		delete(additionalProperties, "network_assistance_enabled")
		delete(additionalProperties, "challenge_control_ready")
		delete(additionalProperties, "settlement_control_ready")
		delete(additionalProperties, "assets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaymentReadinessRail struct {
	value *PaymentReadinessRail
	isSet bool
}

func (v NullablePaymentReadinessRail) Get() *PaymentReadinessRail {
	return v.value
}

func (v *NullablePaymentReadinessRail) Set(val *PaymentReadinessRail) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentReadinessRail) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentReadinessRail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentReadinessRail(val *PaymentReadinessRail) *NullablePaymentReadinessRail {
	return &NullablePaymentReadinessRail{value: val, isSet: true}
}

func (v NullablePaymentReadinessRail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentReadinessRail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
