/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the PublicFeePolicyDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicFeePolicyDocument{}

// PublicFeePolicyDocument struct for PublicFeePolicyDocument
type PublicFeePolicyDocument struct {
	Type string `json:"type"`
	Version int32 `json:"version"`
	FeeMode FeePolicyModeInputEnum `json:"feeMode"`
	QuoteCurrency FeePolicyQuoteCurrencyInputEnum `json:"quoteCurrency"`
	AdditionalProperties map[string]interface{}
}

type _PublicFeePolicyDocument PublicFeePolicyDocument

// NewPublicFeePolicyDocument instantiates a new PublicFeePolicyDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicFeePolicyDocument(type_ string, version int32, feeMode FeePolicyModeInputEnum, quoteCurrency FeePolicyQuoteCurrencyInputEnum) *PublicFeePolicyDocument {
	this := PublicFeePolicyDocument{}
	this.Type = type_
	this.Version = version
	this.FeeMode = feeMode
	this.QuoteCurrency = quoteCurrency
	return &this
}

// NewPublicFeePolicyDocumentWithDefaults instantiates a new PublicFeePolicyDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicFeePolicyDocumentWithDefaults() *PublicFeePolicyDocument {
	this := PublicFeePolicyDocument{}
	return &this
}

// GetType returns the Type field value
func (o *PublicFeePolicyDocument) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PublicFeePolicyDocument) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PublicFeePolicyDocument) SetType(v string) {
	o.Type = v
}

// GetVersion returns the Version field value
func (o *PublicFeePolicyDocument) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PublicFeePolicyDocument) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PublicFeePolicyDocument) SetVersion(v int32) {
	o.Version = v
}

// GetFeeMode returns the FeeMode field value
func (o *PublicFeePolicyDocument) GetFeeMode() FeePolicyModeInputEnum {
	if o == nil {
		var ret FeePolicyModeInputEnum
		return ret
	}

	return o.FeeMode
}

// GetFeeModeOk returns a tuple with the FeeMode field value
// and a boolean to check if the value has been set.
func (o *PublicFeePolicyDocument) GetFeeModeOk() (*FeePolicyModeInputEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeMode, true
}

// SetFeeMode sets field value
func (o *PublicFeePolicyDocument) SetFeeMode(v FeePolicyModeInputEnum) {
	o.FeeMode = v
}

// GetQuoteCurrency returns the QuoteCurrency field value
func (o *PublicFeePolicyDocument) GetQuoteCurrency() FeePolicyQuoteCurrencyInputEnum {
	if o == nil {
		var ret FeePolicyQuoteCurrencyInputEnum
		return ret
	}

	return o.QuoteCurrency
}

// GetQuoteCurrencyOk returns a tuple with the QuoteCurrency field value
// and a boolean to check if the value has been set.
func (o *PublicFeePolicyDocument) GetQuoteCurrencyOk() (*FeePolicyQuoteCurrencyInputEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteCurrency, true
}

// SetQuoteCurrency sets field value
func (o *PublicFeePolicyDocument) SetQuoteCurrency(v FeePolicyQuoteCurrencyInputEnum) {
	o.QuoteCurrency = v
}

func (o PublicFeePolicyDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicFeePolicyDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["version"] = o.Version
	toSerialize["feeMode"] = o.FeeMode
	toSerialize["quoteCurrency"] = o.QuoteCurrency

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PublicFeePolicyDocument) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"version",
		"feeMode",
		"quoteCurrency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicFeePolicyDocument := _PublicFeePolicyDocument{}

	err = json.Unmarshal(data, &varPublicFeePolicyDocument)

	if err != nil {
		return err
	}

	*o = PublicFeePolicyDocument(varPublicFeePolicyDocument)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "version")
		delete(additionalProperties, "feeMode")
		delete(additionalProperties, "quoteCurrency")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePublicFeePolicyDocument struct {
	value *PublicFeePolicyDocument
	isSet bool
}

func (v NullablePublicFeePolicyDocument) Get() *PublicFeePolicyDocument {
	return v.value
}

func (v *NullablePublicFeePolicyDocument) Set(val *PublicFeePolicyDocument) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicFeePolicyDocument) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicFeePolicyDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicFeePolicyDocument(val *PublicFeePolicyDocument) *NullablePublicFeePolicyDocument {
	return &NullablePublicFeePolicyDocument{value: val, isSet: true}
}

func (v NullablePublicFeePolicyDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicFeePolicyDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
