/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the ExternalAddressControlChallengeCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalAddressControlChallengeCreate{}

// ExternalAddressControlChallengeCreate Reject extra or missing JSON keys instead of silently projecting them.
type ExternalAddressControlChallengeCreate struct {
	Network string `json:"network"`
	AssetId string `json:"asset_id" validate:"regexp=^[-a-zA-Z0-9_]+$"`
	Address string `json:"address"`
	ProofMethod ExternalAddressProofInputMethodEnum `json:"proof_method"`
	AdditionalProperties map[string]interface{}
}

type _ExternalAddressControlChallengeCreate ExternalAddressControlChallengeCreate

// NewExternalAddressControlChallengeCreate instantiates a new ExternalAddressControlChallengeCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalAddressControlChallengeCreate(network string, assetId string, address string, proofMethod ExternalAddressProofInputMethodEnum) *ExternalAddressControlChallengeCreate {
	this := ExternalAddressControlChallengeCreate{}
	this.Network = network
	this.AssetId = assetId
	this.Address = address
	this.ProofMethod = proofMethod
	return &this
}

// NewExternalAddressControlChallengeCreateWithDefaults instantiates a new ExternalAddressControlChallengeCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalAddressControlChallengeCreateWithDefaults() *ExternalAddressControlChallengeCreate {
	this := ExternalAddressControlChallengeCreate{}
	return &this
}

// GetNetwork returns the Network field value
func (o *ExternalAddressControlChallengeCreate) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *ExternalAddressControlChallengeCreate) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *ExternalAddressControlChallengeCreate) SetNetwork(v string) {
	o.Network = v
}

// GetAssetId returns the AssetId field value
func (o *ExternalAddressControlChallengeCreate) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *ExternalAddressControlChallengeCreate) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *ExternalAddressControlChallengeCreate) SetAssetId(v string) {
	o.AssetId = v
}

// GetAddress returns the Address field value
func (o *ExternalAddressControlChallengeCreate) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *ExternalAddressControlChallengeCreate) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *ExternalAddressControlChallengeCreate) SetAddress(v string) {
	o.Address = v
}

// GetProofMethod returns the ProofMethod field value
func (o *ExternalAddressControlChallengeCreate) GetProofMethod() ExternalAddressProofInputMethodEnum {
	if o == nil {
		var ret ExternalAddressProofInputMethodEnum
		return ret
	}

	return o.ProofMethod
}

// GetProofMethodOk returns a tuple with the ProofMethod field value
// and a boolean to check if the value has been set.
func (o *ExternalAddressControlChallengeCreate) GetProofMethodOk() (*ExternalAddressProofInputMethodEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProofMethod, true
}

// SetProofMethod sets field value
func (o *ExternalAddressControlChallengeCreate) SetProofMethod(v ExternalAddressProofInputMethodEnum) {
	o.ProofMethod = v
}

func (o ExternalAddressControlChallengeCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalAddressControlChallengeCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	toSerialize["asset_id"] = o.AssetId
	toSerialize["address"] = o.Address
	toSerialize["proof_method"] = o.ProofMethod

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExternalAddressControlChallengeCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network",
		"asset_id",
		"address",
		"proof_method",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExternalAddressControlChallengeCreate := _ExternalAddressControlChallengeCreate{}

	err = json.Unmarshal(data, &varExternalAddressControlChallengeCreate)

	if err != nil {
		return err
	}

	*o = ExternalAddressControlChallengeCreate(varExternalAddressControlChallengeCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "network")
		delete(additionalProperties, "asset_id")
		delete(additionalProperties, "address")
		delete(additionalProperties, "proof_method")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExternalAddressControlChallengeCreate struct {
	value *ExternalAddressControlChallengeCreate
	isSet bool
}

func (v NullableExternalAddressControlChallengeCreate) Get() *ExternalAddressControlChallengeCreate {
	return v.value
}

func (v *NullableExternalAddressControlChallengeCreate) Set(val *ExternalAddressControlChallengeCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalAddressControlChallengeCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalAddressControlChallengeCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalAddressControlChallengeCreate(val *ExternalAddressControlChallengeCreate) *NullableExternalAddressControlChallengeCreate {
	return &NullableExternalAddressControlChallengeCreate{value: val, isSet: true}
}

func (v NullableExternalAddressControlChallengeCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalAddressControlChallengeCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
