/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// ResourceInputFulfillmentModeEnum * `webhook` - webhook * `static` - static * `entitlement` - entitlement
type ResourceInputFulfillmentModeEnum string

// List of ResourceInputFulfillmentModeEnum
const (
	RESOURCEINPUTFULFILLMENTMODEENUM_WEBHOOK ResourceInputFulfillmentModeEnum = "webhook"
	RESOURCEINPUTFULFILLMENTMODEENUM_STATIC ResourceInputFulfillmentModeEnum = "static"
	RESOURCEINPUTFULFILLMENTMODEENUM_ENTITLEMENT ResourceInputFulfillmentModeEnum = "entitlement"
	RESOURCEINPUTFULFILLMENTMODEENUM_UNKNOWN_DEFAULT_OPEN_API ResourceInputFulfillmentModeEnum = "unknown_default_open_api"
)

// All allowed values of ResourceInputFulfillmentModeEnum enum
var AllowedResourceInputFulfillmentModeEnumEnumValues = []ResourceInputFulfillmentModeEnum{
	"webhook",
	"static",
	"entitlement",
	"unknown_default_open_api",
}

func (v *ResourceInputFulfillmentModeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResourceInputFulfillmentModeEnum(value)
	for _, existing := range AllowedResourceInputFulfillmentModeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = RESOURCEINPUTFULFILLMENTMODEENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewResourceInputFulfillmentModeEnumFromValue returns a pointer to a valid ResourceInputFulfillmentModeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResourceInputFulfillmentModeEnumFromValue(v string) (*ResourceInputFulfillmentModeEnum, error) {
	ev := ResourceInputFulfillmentModeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ResourceInputFulfillmentModeEnum: valid values are %v", v, AllowedResourceInputFulfillmentModeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ResourceInputFulfillmentModeEnum) IsValid() bool {
	for _, existing := range AllowedResourceInputFulfillmentModeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ResourceInputFulfillmentModeEnum value
func (v ResourceInputFulfillmentModeEnum) Ptr() *ResourceInputFulfillmentModeEnum {
	return &v
}

type NullableResourceInputFulfillmentModeEnum struct {
	value *ResourceInputFulfillmentModeEnum
	isSet bool
}

func (v NullableResourceInputFulfillmentModeEnum) Get() *ResourceInputFulfillmentModeEnum {
	return v.value
}

func (v *NullableResourceInputFulfillmentModeEnum) Set(val *ResourceInputFulfillmentModeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceInputFulfillmentModeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceInputFulfillmentModeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceInputFulfillmentModeEnum(val *ResourceInputFulfillmentModeEnum) *NullableResourceInputFulfillmentModeEnum {
	return &NullableResourceInputFulfillmentModeEnum{value: val, isSet: true}
}

func (v NullableResourceInputFulfillmentModeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceInputFulfillmentModeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
