/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourceVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceVersion{}

// ResourceVersion struct for ResourceVersion
type ResourceVersion struct {
	Id string `json:"id"`
	Version int32 `json:"version"`
	Method string `json:"method"`
	Path string `json:"path"`
	Description string `json:"description"`
	MimeType string `json:"mime_type"`
	FulfillmentMode ResourceVersionFulfillmentModeEnum `json:"fulfillment_mode"`
	FulfillmentConfig ResourceVersionFulfillmentConfig `json:"fulfillment_config"`
	FeeMode ResourceFeeModeEnum `json:"fee_mode"`
	QuoteCurrency ResourceQuoteCurrencyEnum `json:"quote_currency"`
	FeeAllowanceCapQuoteMicros string `json:"fee_allowance_cap_quote_micros"`
	State ResourceVersionStateEnum `json:"state"`
	Prices []ResourcePrice `json:"prices"`
	AdditionalProperties map[string]interface{}
}

type _ResourceVersion ResourceVersion

// NewResourceVersion instantiates a new ResourceVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceVersion(id string, version int32, method string, path string, description string, mimeType string, fulfillmentMode ResourceVersionFulfillmentModeEnum, fulfillmentConfig ResourceVersionFulfillmentConfig, feeMode ResourceFeeModeEnum, quoteCurrency ResourceQuoteCurrencyEnum, feeAllowanceCapQuoteMicros string, state ResourceVersionStateEnum, prices []ResourcePrice) *ResourceVersion {
	this := ResourceVersion{}
	this.Id = id
	this.Version = version
	this.Method = method
	this.Path = path
	this.Description = description
	this.MimeType = mimeType
	this.FulfillmentMode = fulfillmentMode
	this.FulfillmentConfig = fulfillmentConfig
	this.FeeMode = feeMode
	this.QuoteCurrency = quoteCurrency
	this.FeeAllowanceCapQuoteMicros = feeAllowanceCapQuoteMicros
	this.State = state
	this.Prices = prices
	return &this
}

// NewResourceVersionWithDefaults instantiates a new ResourceVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceVersionWithDefaults() *ResourceVersion {
	this := ResourceVersion{}
	return &this
}

// GetId returns the Id field value
func (o *ResourceVersion) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResourceVersion) SetId(v string) {
	o.Id = v
}

// GetVersion returns the Version field value
func (o *ResourceVersion) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ResourceVersion) SetVersion(v int32) {
	o.Version = v
}

// GetMethod returns the Method field value
func (o *ResourceVersion) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *ResourceVersion) SetMethod(v string) {
	o.Method = v
}

// GetPath returns the Path field value
func (o *ResourceVersion) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ResourceVersion) SetPath(v string) {
	o.Path = v
}

// GetDescription returns the Description field value
func (o *ResourceVersion) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ResourceVersion) SetDescription(v string) {
	o.Description = v
}

// GetMimeType returns the MimeType field value
func (o *ResourceVersion) GetMimeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MimeType, true
}

// SetMimeType sets field value
func (o *ResourceVersion) SetMimeType(v string) {
	o.MimeType = v
}

// GetFulfillmentMode returns the FulfillmentMode field value
func (o *ResourceVersion) GetFulfillmentMode() ResourceVersionFulfillmentModeEnum {
	if o == nil {
		var ret ResourceVersionFulfillmentModeEnum
		return ret
	}

	return o.FulfillmentMode
}

// GetFulfillmentModeOk returns a tuple with the FulfillmentMode field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetFulfillmentModeOk() (*ResourceVersionFulfillmentModeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FulfillmentMode, true
}

// SetFulfillmentMode sets field value
func (o *ResourceVersion) SetFulfillmentMode(v ResourceVersionFulfillmentModeEnum) {
	o.FulfillmentMode = v
}

// GetFulfillmentConfig returns the FulfillmentConfig field value
func (o *ResourceVersion) GetFulfillmentConfig() ResourceVersionFulfillmentConfig {
	if o == nil {
		var ret ResourceVersionFulfillmentConfig
		return ret
	}

	return o.FulfillmentConfig
}

// GetFulfillmentConfigOk returns a tuple with the FulfillmentConfig field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetFulfillmentConfigOk() (*ResourceVersionFulfillmentConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FulfillmentConfig, true
}

// SetFulfillmentConfig sets field value
func (o *ResourceVersion) SetFulfillmentConfig(v ResourceVersionFulfillmentConfig) {
	o.FulfillmentConfig = v
}

// GetFeeMode returns the FeeMode field value
func (o *ResourceVersion) GetFeeMode() ResourceFeeModeEnum {
	if o == nil {
		var ret ResourceFeeModeEnum
		return ret
	}

	return o.FeeMode
}

// GetFeeModeOk returns a tuple with the FeeMode field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetFeeModeOk() (*ResourceFeeModeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeMode, true
}

// SetFeeMode sets field value
func (o *ResourceVersion) SetFeeMode(v ResourceFeeModeEnum) {
	o.FeeMode = v
}

// GetQuoteCurrency returns the QuoteCurrency field value
func (o *ResourceVersion) GetQuoteCurrency() ResourceQuoteCurrencyEnum {
	if o == nil {
		var ret ResourceQuoteCurrencyEnum
		return ret
	}

	return o.QuoteCurrency
}

// GetQuoteCurrencyOk returns a tuple with the QuoteCurrency field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetQuoteCurrencyOk() (*ResourceQuoteCurrencyEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteCurrency, true
}

// SetQuoteCurrency sets field value
func (o *ResourceVersion) SetQuoteCurrency(v ResourceQuoteCurrencyEnum) {
	o.QuoteCurrency = v
}

// GetFeeAllowanceCapQuoteMicros returns the FeeAllowanceCapQuoteMicros field value
func (o *ResourceVersion) GetFeeAllowanceCapQuoteMicros() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeAllowanceCapQuoteMicros
}

// GetFeeAllowanceCapQuoteMicrosOk returns a tuple with the FeeAllowanceCapQuoteMicros field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetFeeAllowanceCapQuoteMicrosOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeAllowanceCapQuoteMicros, true
}

// SetFeeAllowanceCapQuoteMicros sets field value
func (o *ResourceVersion) SetFeeAllowanceCapQuoteMicros(v string) {
	o.FeeAllowanceCapQuoteMicros = v
}

// GetState returns the State field value
func (o *ResourceVersion) GetState() ResourceVersionStateEnum {
	if o == nil {
		var ret ResourceVersionStateEnum
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetStateOk() (*ResourceVersionStateEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ResourceVersion) SetState(v ResourceVersionStateEnum) {
	o.State = v
}

// GetPrices returns the Prices field value
func (o *ResourceVersion) GetPrices() []ResourcePrice {
	if o == nil {
		var ret []ResourcePrice
		return ret
	}

	return o.Prices
}

// GetPricesOk returns a tuple with the Prices field value
// and a boolean to check if the value has been set.
func (o *ResourceVersion) GetPricesOk() ([]ResourcePrice, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prices, true
}

// SetPrices sets field value
func (o *ResourceVersion) SetPrices(v []ResourcePrice) {
	o.Prices = v
}

func (o ResourceVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["version"] = o.Version
	toSerialize["method"] = o.Method
	toSerialize["path"] = o.Path
	toSerialize["description"] = o.Description
	toSerialize["mime_type"] = o.MimeType
	toSerialize["fulfillment_mode"] = o.FulfillmentMode
	toSerialize["fulfillment_config"] = o.FulfillmentConfig
	toSerialize["fee_mode"] = o.FeeMode
	toSerialize["quote_currency"] = o.QuoteCurrency
	toSerialize["fee_allowance_cap_quote_micros"] = o.FeeAllowanceCapQuoteMicros
	toSerialize["state"] = o.State
	toSerialize["prices"] = o.Prices

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResourceVersion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"version",
		"method",
		"path",
		"description",
		"mime_type",
		"fulfillment_mode",
		"fulfillment_config",
		"fee_mode",
		"quote_currency",
		"fee_allowance_cap_quote_micros",
		"state",
		"prices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceVersion := _ResourceVersion{}

	err = json.Unmarshal(data, &varResourceVersion)

	if err != nil {
		return err
	}

	*o = ResourceVersion(varResourceVersion)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "version")
		delete(additionalProperties, "method")
		delete(additionalProperties, "path")
		delete(additionalProperties, "description")
		delete(additionalProperties, "mime_type")
		delete(additionalProperties, "fulfillment_mode")
		delete(additionalProperties, "fulfillment_config")
		delete(additionalProperties, "fee_mode")
		delete(additionalProperties, "quote_currency")
		delete(additionalProperties, "fee_allowance_cap_quote_micros")
		delete(additionalProperties, "state")
		delete(additionalProperties, "prices")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResourceVersion struct {
	value *ResourceVersion
	isSet bool
}

func (v NullableResourceVersion) Get() *ResourceVersion {
	return v.value
}

func (v *NullableResourceVersion) Set(val *ResourceVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceVersion(val *ResourceVersion) *NullableResourceVersion {
	return &NullableResourceVersion{value: val, isSet: true}
}

func (v NullableResourceVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
