/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the SupportedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportedResponse{}

// SupportedResponse struct for SupportedResponse
type SupportedResponse struct {
	Kinds []SupportedKind `json:"kinds"`
	Extensions []string `json:"extensions"`
	Signers map[string][]string `json:"signers"`
	AdditionalProperties map[string]interface{}
}

type _SupportedResponse SupportedResponse

// NewSupportedResponse instantiates a new SupportedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedResponse(kinds []SupportedKind, extensions []string, signers map[string][]string) *SupportedResponse {
	this := SupportedResponse{}
	this.Kinds = kinds
	this.Extensions = extensions
	this.Signers = signers
	return &this
}

// NewSupportedResponseWithDefaults instantiates a new SupportedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedResponseWithDefaults() *SupportedResponse {
	this := SupportedResponse{}
	return &this
}

// GetKinds returns the Kinds field value
func (o *SupportedResponse) GetKinds() []SupportedKind {
	if o == nil {
		var ret []SupportedKind
		return ret
	}

	return o.Kinds
}

// GetKindsOk returns a tuple with the Kinds field value
// and a boolean to check if the value has been set.
func (o *SupportedResponse) GetKindsOk() ([]SupportedKind, bool) {
	if o == nil {
		return nil, false
	}
	return o.Kinds, true
}

// SetKinds sets field value
func (o *SupportedResponse) SetKinds(v []SupportedKind) {
	o.Kinds = v
}

// GetExtensions returns the Extensions field value
func (o *SupportedResponse) GetExtensions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Extensions
}

// GetExtensionsOk returns a tuple with the Extensions field value
// and a boolean to check if the value has been set.
func (o *SupportedResponse) GetExtensionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Extensions, true
}

// SetExtensions sets field value
func (o *SupportedResponse) SetExtensions(v []string) {
	o.Extensions = v
}

// GetSigners returns the Signers field value
func (o *SupportedResponse) GetSigners() map[string][]string {
	if o == nil {
		var ret map[string][]string
		return ret
	}

	return o.Signers
}

// GetSignersOk returns a tuple with the Signers field value
// and a boolean to check if the value has been set.
func (o *SupportedResponse) GetSignersOk() (*map[string][]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signers, true
}

// SetSigners sets field value
func (o *SupportedResponse) SetSigners(v map[string][]string) {
	o.Signers = v
}

func (o SupportedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kinds"] = o.Kinds
	toSerialize["extensions"] = o.Extensions
	toSerialize["signers"] = o.Signers

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SupportedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kinds",
		"extensions",
		"signers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSupportedResponse := _SupportedResponse{}

	err = json.Unmarshal(data, &varSupportedResponse)

	if err != nil {
		return err
	}

	*o = SupportedResponse(varSupportedResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "kinds")
		delete(additionalProperties, "extensions")
		delete(additionalProperties, "signers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSupportedResponse struct {
	value *SupportedResponse
	isSet bool
}

func (v NullableSupportedResponse) Get() *SupportedResponse {
	return v.value
}

func (v *NullableSupportedResponse) Set(val *SupportedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedResponse(val *SupportedResponse) *NullableSupportedResponse {
	return &NullableSupportedResponse{value: val, isSet: true}
}

func (v NullableSupportedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
