/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// checks if the ExternalAddressControlCapability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalAddressControlCapability{}

// ExternalAddressControlCapability struct for ExternalAddressControlCapability
type ExternalAddressControlCapability struct {
	Network string `json:"network"`
	ProofMethods []ExternalAddressProofInputMethodEnum `json:"proof_methods"`
	AdditionalProperties map[string]interface{}
}

type _ExternalAddressControlCapability ExternalAddressControlCapability

// NewExternalAddressControlCapability instantiates a new ExternalAddressControlCapability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalAddressControlCapability(network string, proofMethods []ExternalAddressProofInputMethodEnum) *ExternalAddressControlCapability {
	this := ExternalAddressControlCapability{}
	this.Network = network
	this.ProofMethods = proofMethods
	return &this
}

// NewExternalAddressControlCapabilityWithDefaults instantiates a new ExternalAddressControlCapability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalAddressControlCapabilityWithDefaults() *ExternalAddressControlCapability {
	this := ExternalAddressControlCapability{}
	return &this
}

// GetNetwork returns the Network field value
func (o *ExternalAddressControlCapability) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *ExternalAddressControlCapability) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *ExternalAddressControlCapability) SetNetwork(v string) {
	o.Network = v
}

// GetProofMethods returns the ProofMethods field value
func (o *ExternalAddressControlCapability) GetProofMethods() []ExternalAddressProofInputMethodEnum {
	if o == nil {
		var ret []ExternalAddressProofInputMethodEnum
		return ret
	}

	return o.ProofMethods
}

// GetProofMethodsOk returns a tuple with the ProofMethods field value
// and a boolean to check if the value has been set.
func (o *ExternalAddressControlCapability) GetProofMethodsOk() ([]ExternalAddressProofInputMethodEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProofMethods, true
}

// SetProofMethods sets field value
func (o *ExternalAddressControlCapability) SetProofMethods(v []ExternalAddressProofInputMethodEnum) {
	o.ProofMethods = v
}

func (o ExternalAddressControlCapability) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalAddressControlCapability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	toSerialize["proof_methods"] = o.ProofMethods

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExternalAddressControlCapability) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network",
		"proof_methods",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExternalAddressControlCapability := _ExternalAddressControlCapability{}

	err = json.Unmarshal(data, &varExternalAddressControlCapability)

	if err != nil {
		return err
	}

	*o = ExternalAddressControlCapability(varExternalAddressControlCapability)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "network")
		delete(additionalProperties, "proof_methods")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExternalAddressControlCapability struct {
	value *ExternalAddressControlCapability
	isSet bool
}

func (v NullableExternalAddressControlCapability) Get() *ExternalAddressControlCapability {
	return v.value
}

func (v *NullableExternalAddressControlCapability) Set(val *ExternalAddressControlCapability) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalAddressControlCapability) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalAddressControlCapability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalAddressControlCapability(val *ExternalAddressControlCapability) *NullableExternalAddressControlCapability {
	return &NullableExternalAddressControlCapability{value: val, isSet: true}
}

func (v NullableExternalAddressControlCapability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalAddressControlCapability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
