/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// TrackingStatusEnum * `healthy` - healthy * `degraded` - degraded * `indexer_disabled` - indexer_disabled * `awaiting_first_observation` - awaiting_first_observation * `wallet_version_unavailable` - wallet_version_unavailable
type TrackingStatusEnum string

// List of TrackingStatusEnum
const (
	TRACKINGSTATUSENUM_HEALTHY TrackingStatusEnum = "healthy"
	TRACKINGSTATUSENUM_DEGRADED TrackingStatusEnum = "degraded"
	TRACKINGSTATUSENUM_INDEXER_DISABLED TrackingStatusEnum = "indexer_disabled"
	TRACKINGSTATUSENUM_AWAITING_FIRST_OBSERVATION TrackingStatusEnum = "awaiting_first_observation"
	TRACKINGSTATUSENUM_WALLET_VERSION_UNAVAILABLE TrackingStatusEnum = "wallet_version_unavailable"
	TRACKINGSTATUSENUM_UNKNOWN_DEFAULT_OPEN_API TrackingStatusEnum = "unknown_default_open_api"
)

// All allowed values of TrackingStatusEnum enum
var AllowedTrackingStatusEnumEnumValues = []TrackingStatusEnum{
	"healthy",
	"degraded",
	"indexer_disabled",
	"awaiting_first_observation",
	"wallet_version_unavailable",
	"unknown_default_open_api",
}

func (v *TrackingStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TrackingStatusEnum(value)
	for _, existing := range AllowedTrackingStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = TRACKINGSTATUSENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewTrackingStatusEnumFromValue returns a pointer to a valid TrackingStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTrackingStatusEnumFromValue(v string) (*TrackingStatusEnum, error) {
	ev := TrackingStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TrackingStatusEnum: valid values are %v", v, AllowedTrackingStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TrackingStatusEnum) IsValid() bool {
	for _, existing := range AllowedTrackingStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TrackingStatusEnum value
func (v TrackingStatusEnum) Ptr() *TrackingStatusEnum {
	return &v
}

type NullableTrackingStatusEnum struct {
	value *TrackingStatusEnum
	isSet bool
}

func (v NullableTrackingStatusEnum) Get() *TrackingStatusEnum {
	return v.value
}

func (v *NullableTrackingStatusEnum) Set(val *TrackingStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackingStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackingStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackingStatusEnum(val *TrackingStatusEnum) *NullableTrackingStatusEnum {
	return &NullableTrackingStatusEnum{value: val, isSet: true}
}

func (v NullableTrackingStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackingStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
