/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// ResourceVersionStateEnum * `draft` - Draft * `active` - Active * `retired` - Retired
type ResourceVersionStateEnum string

// List of ResourceVersionStateEnum
const (
	RESOURCEVERSIONSTATEENUM_DRAFT ResourceVersionStateEnum = "draft"
	RESOURCEVERSIONSTATEENUM_ACTIVE ResourceVersionStateEnum = "active"
	RESOURCEVERSIONSTATEENUM_RETIRED ResourceVersionStateEnum = "retired"
	RESOURCEVERSIONSTATEENUM_UNKNOWN_DEFAULT_OPEN_API ResourceVersionStateEnum = "unknown_default_open_api"
)

// All allowed values of ResourceVersionStateEnum enum
var AllowedResourceVersionStateEnumEnumValues = []ResourceVersionStateEnum{
	"draft",
	"active",
	"retired",
	"unknown_default_open_api",
}

func (v *ResourceVersionStateEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResourceVersionStateEnum(value)
	for _, existing := range AllowedResourceVersionStateEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = RESOURCEVERSIONSTATEENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewResourceVersionStateEnumFromValue returns a pointer to a valid ResourceVersionStateEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResourceVersionStateEnumFromValue(v string) (*ResourceVersionStateEnum, error) {
	ev := ResourceVersionStateEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ResourceVersionStateEnum: valid values are %v", v, AllowedResourceVersionStateEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ResourceVersionStateEnum) IsValid() bool {
	for _, existing := range AllowedResourceVersionStateEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ResourceVersionStateEnum value
func (v ResourceVersionStateEnum) Ptr() *ResourceVersionStateEnum {
	return &v
}

type NullableResourceVersionStateEnum struct {
	value *ResourceVersionStateEnum
	isSet bool
}

func (v NullableResourceVersionStateEnum) Get() *ResourceVersionStateEnum {
	return v.value
}

func (v *NullableResourceVersionStateEnum) Set(val *ResourceVersionStateEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceVersionStateEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceVersionStateEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceVersionStateEnum(val *ResourceVersionStateEnum) *NullableResourceVersionStateEnum {
	return &NullableResourceVersionStateEnum{value: val, isSet: true}
}

func (v NullableResourceVersionStateEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceVersionStateEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
