/*
x402api Public API

Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x402api

import (
	"encoding/json"
	"fmt"
)

// HTTPMethodEnum * `GET` - GET * `POST` - POST * `PUT` - PUT * `PATCH` - PATCH * `DELETE` - DELETE
type HTTPMethodEnum string

// List of HTTPMethodEnum
const (
	HTTPMETHODENUM_GET HTTPMethodEnum = "GET"
	HTTPMETHODENUM_POST HTTPMethodEnum = "POST"
	HTTPMETHODENUM_PUT HTTPMethodEnum = "PUT"
	HTTPMETHODENUM_PATCH HTTPMethodEnum = "PATCH"
	HTTPMETHODENUM_DELETE HTTPMethodEnum = "DELETE"
	HTTPMETHODENUM_UNKNOWN_DEFAULT_OPEN_API HTTPMethodEnum = "unknown_default_open_api"
)

// All allowed values of HTTPMethodEnum enum
var AllowedHTTPMethodEnumEnumValues = []HTTPMethodEnum{
	"GET",
	"POST",
	"PUT",
	"PATCH",
	"DELETE",
	"unknown_default_open_api",
}

func (v *HTTPMethodEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := HTTPMethodEnum(value)
	for _, existing := range AllowedHTTPMethodEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = HTTPMETHODENUM_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewHTTPMethodEnumFromValue returns a pointer to a valid HTTPMethodEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewHTTPMethodEnumFromValue(v string) (*HTTPMethodEnum, error) {
	ev := HTTPMethodEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for HTTPMethodEnum: valid values are %v", v, AllowedHTTPMethodEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v HTTPMethodEnum) IsValid() bool {
	for _, existing := range AllowedHTTPMethodEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to HTTPMethodEnum value
func (v HTTPMethodEnum) Ptr() *HTTPMethodEnum {
	return &v
}

type NullableHTTPMethodEnum struct {
	value *HTTPMethodEnum
	isSet bool
}

func (v NullableHTTPMethodEnum) Get() *HTTPMethodEnum {
	return v.value
}

func (v *NullableHTTPMethodEnum) Set(val *HTTPMethodEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableHTTPMethodEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableHTTPMethodEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHTTPMethodEnum(val *HTTPMethodEnum) *NullableHTTPMethodEnum {
	return &NullableHTTPMethodEnum{value: val, isSet: true}
}

func (v NullableHTTPMethodEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHTTPMethodEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
